// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package openrouter

// Generated from OpenAPI doc version 1.0.0 and generator version 2.879.6

import (
	"context"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/config"
	"github.com/OpenRouterTeam/go-sdk/internal/globals"
	"github.com/OpenRouterTeam/go-sdk/internal/hooks"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/models/components"
	"github.com/OpenRouterTeam/go-sdk/retry"
	"net/http"
	"time"
)

const (
	// Production server
	ServerProduction string = "production"
)

// ServerList contains the list of servers available to the SDK
var ServerList = map[string]string{
	ServerProduction: "https://openrouter.ai/api/v1",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// OpenRouter API: OpenAI-compatible API with additional OpenRouter features
//
// https://openrouter.ai/docs - OpenRouter Documentation
type OpenRouter struct {
	SDKVersion string
	Beta       *Beta
	// Analytics and usage endpoints
	Analytics *Analytics
	Chat      *Chat
	// Credit management endpoints
	Credits *Credits
	// Generation history endpoints
	Generations *Generations
	// Model information endpoints
	Models *Models
	// Endpoint information
	Endpoints *Endpoints
	// Provider information endpoints
	Providers *Providers
	// API key management endpoints
	APIKeys *APIKeys
	// Organization endpoints
	Organization *Organization
	// Guardrails endpoints
	Guardrails *Guardrails
	// OAuth authentication endpoints
	OAuth *OAuth
	// Text embedding endpoints
	Embeddings *Embeddings
	// Reranking endpoints
	Rerank *Rerank

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*OpenRouter)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *OpenRouter) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *OpenRouter) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServer allows the overriding of the default server by name
func WithServer(server string) SDKOption {
	return func(sdk *OpenRouter) {
		_, ok := ServerList[server]
		if !ok {
			panic(fmt.Errorf("server %s not found", server))
		}

		sdk.sdkConfiguration.Server = server
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *OpenRouter) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(apiKey string) SDKOption {
	return func(sdk *OpenRouter) {
		security := components.Security{APIKey: &apiKey}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *OpenRouter) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

// WithHTTPReferer allows setting the HTTPReferer parameter for all supported operations
func WithHTTPReferer(httpReferer string) SDKOption {
	return func(sdk *OpenRouter) {
		sdk.sdkConfiguration.Globals.HTTPReferer = &httpReferer
	}
}

// WithXTitle allows setting the XTitle parameter for all supported operations
func WithXTitle(xTitle string) SDKOption {
	return func(sdk *OpenRouter) {
		sdk.sdkConfiguration.Globals.XTitle = &xTitle
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *OpenRouter) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *OpenRouter) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *OpenRouter {
	sdk := &OpenRouter{
		SDKVersion: "0.3.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.3.0 2.879.6 1.0.0 github.com/OpenRouterTeam/go-sdk",
			Globals:    globals.Globals{},
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	sdk.sdkConfiguration.FillGlobalsFromEnv()

	if sdk.sdkConfiguration.Security == nil {
		var envVarSecurity components.Security
		if utils.PopulateSecurityFromEnv(&envVarSecurity) {
			sdk.sdkConfiguration.Security = utils.AsSecuritySource(envVarSecurity)
		}
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Beta = newBeta(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Analytics = newAnalytics(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Chat = newChat(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Credits = newCredits(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Generations = newGenerations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Models = newModels(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Endpoints = newEndpoints(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Providers = newProviders(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.APIKeys = newAPIKeys(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Organization = newOrganization(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Guardrails = newGuardrails(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.OAuth = newOAuth(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Embeddings = newEmbeddings(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Rerank = newRerank(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
