// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

type BulkUnassignMembersFromGuardrailRequest struct {
	// The unique identifier of the guardrail
	ID                         string                                `pathParam:"style=simple,explode=false,name=id"`
	BulkUnassignMembersRequest components.BulkUnassignMembersRequest `request:"mediaType=application/json"`
}

func (b *BulkUnassignMembersFromGuardrailRequest) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BulkUnassignMembersFromGuardrailRequest) GetBulkUnassignMembersRequest() components.BulkUnassignMembersRequest {
	if b == nil {
		return components.BulkUnassignMembersRequest{}
	}
	return b.BulkUnassignMembersRequest
}
