// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

type CreatePrivateEndpointRequest struct {
	// Retry-safe create: a repeated create with the same key from the same organization returns the endpoint the first request created instead of creating another. The endpoint is returned as it is now. Reusing a key with a different request body (model, provider, base URL, upstream model ID, declared ZDR or region, or pricing) is rejected with 422 `idempotency_key_reused`. `activate` is not compared, and later edits to the endpoint do not affect the comparison.
	IdempotencyKey               *string                                 `header:"style=simple,explode=false,name=idempotency-key"`
	CreatePrivateEndpointRequest components.CreatePrivateEndpointRequest `request:"mediaType=application/json"`
}

func (c *CreatePrivateEndpointRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreatePrivateEndpointRequest) GetCreatePrivateEndpointRequest() components.CreatePrivateEndpointRequest {
	if c == nil {
		return components.CreatePrivateEndpointRequest{}
	}
	return c.CreatePrivateEndpointRequest
}
