// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

// CreateGuardrailResetIntervalRequest - Interval at which the limit resets (daily, weekly, monthly)
type CreateGuardrailResetIntervalRequest string

const (
	CreateGuardrailResetIntervalRequestDaily   CreateGuardrailResetIntervalRequest = "daily"
	CreateGuardrailResetIntervalRequestWeekly  CreateGuardrailResetIntervalRequest = "weekly"
	CreateGuardrailResetIntervalRequestMonthly CreateGuardrailResetIntervalRequest = "monthly"
)

func (e CreateGuardrailResetIntervalRequest) ToPointer() *CreateGuardrailResetIntervalRequest {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreateGuardrailResetIntervalRequest) IsExact() bool {
	if e != nil {
		switch *e {
		case "daily", "weekly", "monthly":
			return true
		}
	}
	return false
}

type CreateGuardrailRequest struct {
	// Name for the new guardrail
	Name string `json:"name"`
	// Description of the guardrail
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Spending limit in USD
	LimitUsd *float64 `json:"limit_usd,omitzero"`
	// Interval at which the limit resets (daily, weekly, monthly)
	ResetInterval optionalnullable.OptionalNullable[CreateGuardrailResetIntervalRequest] `json:"reset_interval,omitzero"`
	// List of allowed provider IDs
	AllowedProviders optionalnullable.OptionalNullable[[]string] `json:"allowed_providers,omitzero"`
	// List of provider IDs to exclude from routing
	IgnoredProviders optionalnullable.OptionalNullable[[]string] `json:"ignored_providers,omitzero"`
	// Array of model identifiers (slug or canonical_slug accepted)
	AllowedModels optionalnullable.OptionalNullable[[]string] `json:"allowed_models,omitzero"`
	// Whether to enforce zero data retention
	EnforceZdr optionalnullable.OptionalNullable[bool] `json:"enforce_zdr,omitzero"`
}

func (c CreateGuardrailRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateGuardrailRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateGuardrailRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateGuardrailRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateGuardrailRequest) GetLimitUsd() *float64 {
	if c == nil {
		return nil
	}
	return c.LimitUsd
}

func (c *CreateGuardrailRequest) GetResetInterval() optionalnullable.OptionalNullable[CreateGuardrailResetIntervalRequest] {
	if c == nil {
		return nil
	}
	return c.ResetInterval
}

func (c *CreateGuardrailRequest) GetAllowedProviders() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.AllowedProviders
}

func (c *CreateGuardrailRequest) GetIgnoredProviders() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.IgnoredProviders
}

func (c *CreateGuardrailRequest) GetAllowedModels() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.AllowedModels
}

func (c *CreateGuardrailRequest) GetEnforceZdr() optionalnullable.OptionalNullable[bool] {
	if c == nil {
		return nil
	}
	return c.EnforceZdr
}

// CreateGuardrailResetIntervalResponse - Interval at which the limit resets (daily, weekly, monthly)
type CreateGuardrailResetIntervalResponse string

const (
	CreateGuardrailResetIntervalResponseDaily   CreateGuardrailResetIntervalResponse = "daily"
	CreateGuardrailResetIntervalResponseWeekly  CreateGuardrailResetIntervalResponse = "weekly"
	CreateGuardrailResetIntervalResponseMonthly CreateGuardrailResetIntervalResponse = "monthly"
)

func (e CreateGuardrailResetIntervalResponse) ToPointer() *CreateGuardrailResetIntervalResponse {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreateGuardrailResetIntervalResponse) IsExact() bool {
	if e != nil {
		switch *e {
		case "daily", "weekly", "monthly":
			return true
		}
	}
	return false
}

// CreateGuardrailData - The created guardrail
type CreateGuardrailData struct {
	// Unique identifier for the guardrail
	ID string `json:"id"`
	// Name of the guardrail
	Name string `json:"name"`
	// Description of the guardrail
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Spending limit in USD
	LimitUsd *float64 `json:"limit_usd,omitzero"`
	// Interval at which the limit resets (daily, weekly, monthly)
	ResetInterval optionalnullable.OptionalNullable[CreateGuardrailResetIntervalResponse] `json:"reset_interval,omitzero"`
	// List of allowed provider IDs
	AllowedProviders optionalnullable.OptionalNullable[[]string] `json:"allowed_providers,omitzero"`
	// List of provider IDs to exclude from routing
	IgnoredProviders optionalnullable.OptionalNullable[[]string] `json:"ignored_providers,omitzero"`
	// Array of model canonical_slugs (immutable identifiers)
	AllowedModels optionalnullable.OptionalNullable[[]string] `json:"allowed_models,omitzero"`
	// Whether to enforce zero data retention
	EnforceZdr optionalnullable.OptionalNullable[bool] `json:"enforce_zdr,omitzero"`
	// ISO 8601 timestamp of when the guardrail was created
	CreatedAt string `json:"created_at"`
	// ISO 8601 timestamp of when the guardrail was last updated
	UpdatedAt optionalnullable.OptionalNullable[string] `json:"updated_at,omitzero"`
}

func (c CreateGuardrailData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateGuardrailData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateGuardrailData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateGuardrailData) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateGuardrailData) GetDescription() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateGuardrailData) GetLimitUsd() *float64 {
	if c == nil {
		return nil
	}
	return c.LimitUsd
}

func (c *CreateGuardrailData) GetResetInterval() optionalnullable.OptionalNullable[CreateGuardrailResetIntervalResponse] {
	if c == nil {
		return nil
	}
	return c.ResetInterval
}

func (c *CreateGuardrailData) GetAllowedProviders() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.AllowedProviders
}

func (c *CreateGuardrailData) GetIgnoredProviders() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.IgnoredProviders
}

func (c *CreateGuardrailData) GetAllowedModels() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.AllowedModels
}

func (c *CreateGuardrailData) GetEnforceZdr() optionalnullable.OptionalNullable[bool] {
	if c == nil {
		return nil
	}
	return c.EnforceZdr
}

func (c *CreateGuardrailData) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateGuardrailData) GetUpdatedAt() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

// CreateGuardrailResponse - Guardrail created successfully
type CreateGuardrailResponse struct {
	// The created guardrail
	Data CreateGuardrailData `json:"data"`
}

func (c *CreateGuardrailResponse) GetData() CreateGuardrailData {
	if c == nil {
		return CreateGuardrailData{}
	}
	return c.Data
}
