// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

type CreateInternChatCompletionRequest struct {
	// The intern to talk to.
	InternID                    string                                 `pathParam:"style=simple,explode=false,name=internId"`
	InternChatCompletionRequest components.InternChatCompletionRequest `request:"mediaType=application/json"`
}

func (c *CreateInternChatCompletionRequest) GetInternID() string {
	if c == nil {
		return ""
	}
	return c.InternID
}

func (c *CreateInternChatCompletionRequest) GetInternChatCompletionRequest() components.InternChatCompletionRequest {
	if c == nil {
		return components.InternChatCompletionRequest{}
	}
	return c.InternChatCompletionRequest
}
