// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetEndUserRequest struct {
	// Immutable case-sensitive tracking string supplied as user on inference requests. URL-encode it in resource paths.
	User string `pathParam:"style=simple,explode=false,name=user"`
}

func (g *GetEndUserRequest) GetUser() string {
	if g == nil {
		return ""
	}
	return g.User
}
