// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

// Category - Filter models by use case category
type Category string

const (
	CategoryProgramming  Category = "programming"
	CategoryRoleplay     Category = "roleplay"
	CategoryMarketing    Category = "marketing"
	CategoryMarketingSeo Category = "marketing/seo"
	CategoryTechnology   Category = "technology"
	CategoryScience      Category = "science"
	CategoryTranslation  Category = "translation"
	CategoryLegal        Category = "legal"
	CategoryFinance      Category = "finance"
	CategoryHealth       Category = "health"
	CategoryTrivia       Category = "trivia"
	CategoryAcademia     Category = "academia"
)

func (e Category) ToPointer() *Category {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Category) IsExact() bool {
	if e != nil {
		switch *e {
		case "programming", "roleplay", "marketing", "marketing/seo", "technology", "science", "translation", "legal", "finance", "health", "trivia", "academia":
			return true
		}
	}
	return false
}

type GetModelsRequest struct {
	// Filter models by use case category
	Category            *Category `queryParam:"style=form,explode=true,name=category"`
	SupportedParameters *string   `queryParam:"style=form,explode=true,name=supported_parameters"`
	// Filter models by output modality. Accepts a comma-separated list of modalities (text, image, audio, embeddings) or "all" to include all models. Defaults to "text".
	OutputModalities *string `queryParam:"style=form,explode=true,name=output_modalities"`
}

func (g *GetModelsRequest) GetCategory() *Category {
	if g == nil {
		return nil
	}
	return g.Category
}

func (g *GetModelsRequest) GetSupportedParameters() *string {
	if g == nil {
		return nil
	}
	return g.SupportedParameters
}

func (g *GetModelsRequest) GetOutputModalities() *string {
	if g == nil {
		return nil
	}
	return g.OutputModalities
}
