// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

// GetOrganizationSettingsResponse - Organization settings
type GetOrganizationSettingsResponse struct {
	Data components.OrganizationSettings `json:"data"`
}

func (g *GetOrganizationSettingsResponse) GetData() components.OrganizationSettings {
	if g == nil {
		return components.OrganizationSettings{}
	}
	return g.Data
}
