// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetPrivateEndpointRequest struct {
	// Stable identifier of the private endpoint.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPrivateEndpointRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
