// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

type GetWorkspaceBudgetRequest struct {
	// The workspace ID (UUID) or slug
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Budget reset interval. Use "lifetime" for a one-time budget that never resets.
	Interval components.WorkspaceBudgetInterval `pathParam:"style=simple,explode=false,name=interval"`
}

func (g *GetWorkspaceBudgetRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetWorkspaceBudgetRequest) GetInterval() components.WorkspaceBudgetInterval {
	if g == nil {
		return components.WorkspaceBudgetInterval("")
	}
	return g.Interval
}
