// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/models/components"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type ListGuardrailKeyAssignmentsRequest struct {
	// The unique identifier of the guardrail
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Number of records to skip for pagination
	Offset optionalnullable.OptionalNullable[int64] `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Maximum number of records to return (max 100)
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
}

func (l ListGuardrailKeyAssignmentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListGuardrailKeyAssignmentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListGuardrailKeyAssignmentsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListGuardrailKeyAssignmentsRequest) GetOffset() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListGuardrailKeyAssignmentsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

type ListGuardrailKeyAssignmentsResponse struct {
	Result components.ListKeyAssignmentsResponse

	Next func() (*ListGuardrailKeyAssignmentsResponse, error)
}

func (l *ListGuardrailKeyAssignmentsResponse) GetResult() components.ListKeyAssignmentsResponse {
	if l == nil {
		return components.ListKeyAssignmentsResponse{}
	}
	return l.Result
}
