// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/models/components"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type ListMemberAssignmentsRequest struct {
	// Number of records to skip for pagination
	Offset optionalnullable.OptionalNullable[int64] `queryParam:"style=form,explode=true,name=offset"`
	// Maximum number of records to return (max 100)
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
}

func (l *ListMemberAssignmentsRequest) GetOffset() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListMemberAssignmentsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

type ListMemberAssignmentsResponse struct {
	Result components.ListMemberAssignmentsResponse

	Next func() (*ListMemberAssignmentsResponse, error)
}

func (l *ListMemberAssignmentsResponse) GetResult() components.ListMemberAssignmentsResponse {
	if l == nil {
		return components.ListMemberAssignmentsResponse{}
	}
	return l.Result
}
