// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

type ListGuardrailKeyAssignmentsRequest struct {
	// The unique identifier of the guardrail
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Number of records to skip for pagination
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// Maximum number of records to return (max 100)
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
}

func (l *ListGuardrailKeyAssignmentsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListGuardrailKeyAssignmentsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListGuardrailKeyAssignmentsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

type ListGuardrailKeyAssignmentsResponse struct {
	Result components.ListKeyAssignmentsResponse

	Next func() (*ListGuardrailKeyAssignmentsResponse, error)
}

func (l *ListGuardrailKeyAssignmentsResponse) GetResult() components.ListKeyAssignmentsResponse {
	if l == nil {
		return components.ListKeyAssignmentsResponse{}
	}
	return l.Result
}
