// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/models/components"
	"github.com/OpenRouterTeam/go-sdk/types/stream"
)

type SendChatCompletionRequestResponseType string

const (
	SendChatCompletionRequestResponseTypeChatResponse SendChatCompletionRequestResponseType = "ChatResponse"
	SendChatCompletionRequestResponseTypeEventStream  SendChatCompletionRequestResponseType = "event-stream"
)

type SendChatCompletionRequestResponse struct {
	ChatResponse *components.ChatResponse                                   `queryParam:"inline,name=sendChatCompletionRequest_response" union:"member"`
	EventStream  *stream.EventStream[components.ChatStreamingResponseChunk] `queryParam:"inline,name=sendChatCompletionRequest_response" union:"member"`

	Type SendChatCompletionRequestResponseType
}

func CreateSendChatCompletionRequestResponseChatResponse(chatResponse components.ChatResponse) SendChatCompletionRequestResponse {
	typ := SendChatCompletionRequestResponseTypeChatResponse

	return SendChatCompletionRequestResponse{
		ChatResponse: &chatResponse,
		Type:         typ,
	}
}

func CreateSendChatCompletionRequestResponseEventStream(eventStream *stream.EventStream[components.ChatStreamingResponseChunk]) SendChatCompletionRequestResponse {
	typ := SendChatCompletionRequestResponseTypeEventStream

	return SendChatCompletionRequestResponse{
		EventStream: eventStream,
		Type:        typ,
	}
}

func (u *SendChatCompletionRequestResponse) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var chatResponse components.ChatResponse = components.ChatResponse{}
	if err := utils.UnmarshalJSON(data, &chatResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SendChatCompletionRequestResponseTypeChatResponse,
			Value: &chatResponse,
		})
	}

	var eventStream *stream.EventStream[components.ChatStreamingResponseChunk] = &stream.EventStream[components.ChatStreamingResponseChunk]{}
	if err := utils.UnmarshalJSON(data, &eventStream, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SendChatCompletionRequestResponseTypeEventStream,
			Value: eventStream,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendChatCompletionRequestResponse", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendChatCompletionRequestResponse", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(SendChatCompletionRequestResponseType)
	switch best.Type {
	case SendChatCompletionRequestResponseTypeChatResponse:
		u.ChatResponse = best.Value.(*components.ChatResponse)
		return nil
	case SendChatCompletionRequestResponseTypeEventStream:
		u.EventStream = best.Value.(*stream.EventStream[components.ChatStreamingResponseChunk])
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SendChatCompletionRequestResponse", string(data))
}

func (u SendChatCompletionRequestResponse) MarshalJSON() ([]byte, error) {
	if u.ChatResponse != nil {
		return utils.MarshalJSON(u.ChatResponse, "", true)
	}

	if u.EventStream != nil {
		return utils.MarshalJSON(u.EventStream, "", true)
	}

	return nil, errors.New("could not marshal union type SendChatCompletionRequestResponse: all fields are null")
}
