// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

type UpdateScimGroupMappingRequest struct {
	ID                            string                                   `pathParam:"style=simple,explode=false,name=id"`
	UpdateScimGroupMappingRequest components.UpdateScimGroupMappingRequest `request:"mediaType=application/json"`
}

func (u *UpdateScimGroupMappingRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateScimGroupMappingRequest) GetUpdateScimGroupMappingRequest() components.UpdateScimGroupMappingRequest {
	if u == nil {
		return components.UpdateScimGroupMappingRequest{}
	}
	return u.UpdateScimGroupMappingRequest
}
