// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type File struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (f *File) GetFileName() string {
	if f == nil {
		return ""
	}
	return f.FileName
}

func (f *File) GetContent() any {
	if f == nil {
		return nil
	}
	return f.Content
}

type UploadFileRequestBody struct {
	File File `multipartForm:"file,name=file"`
}

func (u *UploadFileRequestBody) GetFile() File {
	if u == nil {
		return File{}
	}
	return u.File
}

type UploadFileRequest struct {
	// Workspace to scope the request to. Defaults to the caller’s default workspace.
	WorkspaceID *string               `queryParam:"style=form,explode=true,name=workspace_id"`
	RequestBody UploadFileRequestBody `request:"mediaType=multipart/form-data"`
}

func (u *UploadFileRequest) GetWorkspaceID() *string {
	if u == nil {
		return nil
	}
	return u.WorkspaceID
}

func (u *UploadFileRequest) GetRequestBody() UploadFileRequestBody {
	if u == nil {
		return UploadFileRequestBody{}
	}
	return u.RequestBody
}
