// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

// ForbiddenResponseError - Forbidden - Authentication successful but insufficient permissions
type ForbiddenResponseError struct {
	// Error data for ForbiddenResponse
	Error_ components.ForbiddenResponseErrorData `json:"error"`
	UserID *string                               `json:"user_id,omitzero"`
}

var _ error = &ForbiddenResponseError{}

func (e *ForbiddenResponseError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
