// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

// InternChatErrorResponse - A refusal before the stream opens. Once the response is `200` and streaming, failures arrive as a chunk with `finish_reason: "error"` instead.
type InternChatErrorResponse struct {
	// The OpenAI-compatible error object. `metadata` is present on refusals from the chat route. Authentication refusals (`401`), the departed-creator `403` and the programme `404` carry only `code` and `message`.
	Error_ components.InternChatError `json:"error"`
}

var _ error = &InternChatErrorResponse{}

func (e *InternChatErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
