// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

// PaymentRequiredResponseError - Payment Required - Insufficient credits or quota to complete request
type PaymentRequiredResponseError struct {
	// Error data for PaymentRequiredResponse
	Error_ components.PaymentRequiredResponseErrorData `json:"error"`
	UserID *string                                     `json:"user_id,omitzero"`
}

var _ error = &PaymentRequiredResponseError{}

func (e *PaymentRequiredResponseError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
