// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/OpenRouterTeam/go-sdk/models/components"
)

// UnauthorizedResponseError - Unauthorized - Authentication required or invalid credentials
type UnauthorizedResponseError struct {
	// Error data for UnauthorizedResponse
	Error_ components.UnauthorizedResponseErrorData `json:"error"`
	UserID *string                                  `json:"user_id,omitzero"`
}

var _ error = &UnauthorizedResponseError{}

func (e *UnauthorizedResponseError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
