// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

// AdvisorReasoningEffort - Reasoning effort level for the advisor call.
type AdvisorReasoningEffort string

const (
	AdvisorReasoningEffortMax     AdvisorReasoningEffort = "max"
	AdvisorReasoningEffortXhigh   AdvisorReasoningEffort = "xhigh"
	AdvisorReasoningEffortHigh    AdvisorReasoningEffort = "high"
	AdvisorReasoningEffortMedium  AdvisorReasoningEffort = "medium"
	AdvisorReasoningEffortLow     AdvisorReasoningEffort = "low"
	AdvisorReasoningEffortMinimal AdvisorReasoningEffort = "minimal"
	AdvisorReasoningEffortNone    AdvisorReasoningEffort = "none"
)

func (e AdvisorReasoningEffort) ToPointer() *AdvisorReasoningEffort {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AdvisorReasoningEffort) IsExact() bool {
	if e != nil {
		switch *e {
		case "max", "xhigh", "high", "medium", "low", "minimal", "none":
			return true
		}
	}
	return false
}

// AdvisorReasoning - Reasoning configuration forwarded to the advisor call. Use this to control reasoning effort and token budget for models that support extended thinking.
type AdvisorReasoning struct {
	// Reasoning effort level for the advisor call.
	Effort *AdvisorReasoningEffort `json:"effort,omitzero"`
	// Maximum number of reasoning tokens the advisor may use.
	MaxTokens *int64 `json:"max_tokens,omitzero"`
}

func (a AdvisorReasoning) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AdvisorReasoning) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AdvisorReasoning) GetEffort() *AdvisorReasoningEffort {
	if a == nil {
		return nil
	}
	return a.Effort
}

func (a *AdvisorReasoning) GetMaxTokens() *int64 {
	if a == nil {
		return nil
	}
	return a.MaxTokens
}
