// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type Agent struct {
	AgentName            string         `json:"agent_name"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (a Agent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Agent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Agent) GetAgentName() string {
	if a == nil {
		return ""
	}
	return a.AgentName
}

func (a *Agent) GetAdditionalProperties() map[string]any {
	if a == nil {
		return nil
	}
	return a.AdditionalProperties
}

type TypeEncryptedContent string

const (
	TypeEncryptedContentEncryptedContent TypeEncryptedContent = "encrypted_content"
)

func (e TypeEncryptedContent) ToPointer() *TypeEncryptedContent {
	return &e
}
func (e *TypeEncryptedContent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "encrypted_content":
		*e = TypeEncryptedContent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeEncryptedContent: %v", v)
	}
}

type ContentEncryptedContent struct {
	EncryptedContent     string               `json:"encrypted_content"`
	Type                 TypeEncryptedContent `json:"type"`
	AdditionalProperties map[string]any       `additionalProperties:"true" json:"-"`
}

func (c ContentEncryptedContent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentEncryptedContent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentEncryptedContent) GetEncryptedContent() string {
	if c == nil {
		return ""
	}
	return c.EncryptedContent
}

func (c *ContentEncryptedContent) GetType() TypeEncryptedContent {
	if c == nil {
		return TypeEncryptedContent("")
	}
	return c.Type
}

func (c *ContentEncryptedContent) GetAdditionalProperties() map[string]any {
	if c == nil {
		return nil
	}
	return c.AdditionalProperties
}

type AgentMessageItemDetail string

const (
	AgentMessageItemDetailAuto     AgentMessageItemDetail = "auto"
	AgentMessageItemDetailHigh     AgentMessageItemDetail = "high"
	AgentMessageItemDetailLow      AgentMessageItemDetail = "low"
	AgentMessageItemDetailOriginal AgentMessageItemDetail = "original"
)

func (e AgentMessageItemDetail) ToPointer() *AgentMessageItemDetail {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentMessageItemDetail) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "high", "low", "original":
			return true
		}
	}
	return false
}

type AgentMessageItemTypeInputImage string

const (
	AgentMessageItemTypeInputImageInputImage AgentMessageItemTypeInputImage = "input_image"
)

func (e AgentMessageItemTypeInputImage) ToPointer() *AgentMessageItemTypeInputImage {
	return &e
}
func (e *AgentMessageItemTypeInputImage) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input_image":
		*e = AgentMessageItemTypeInputImage(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentMessageItemTypeInputImage: %v", v)
	}
}

// AgentMessageItemContentInputImage - Image input content item
type AgentMessageItemContentInputImage struct {
	Detail   AgentMessageItemDetail                    `json:"detail"`
	ImageURL optionalnullable.OptionalNullable[string] `json:"image_url,omitzero"`
	Type     AgentMessageItemTypeInputImage            `json:"type"`
}

func (a AgentMessageItemContentInputImage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentMessageItemContentInputImage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentMessageItemContentInputImage) GetDetail() AgentMessageItemDetail {
	if a == nil {
		return AgentMessageItemDetail("")
	}
	return a.Detail
}

func (a *AgentMessageItemContentInputImage) GetImageURL() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.ImageURL
}

func (a *AgentMessageItemContentInputImage) GetType() AgentMessageItemTypeInputImage {
	if a == nil {
		return AgentMessageItemTypeInputImage("")
	}
	return a.Type
}

type AgentMessageItemContentUnionType string

const (
	AgentMessageItemContentUnionTypeInputText        AgentMessageItemContentUnionType = "input_text"
	AgentMessageItemContentUnionTypeInputImage       AgentMessageItemContentUnionType = "input_image"
	AgentMessageItemContentUnionTypeEncryptedContent AgentMessageItemContentUnionType = "encrypted_content"
)

type AgentMessageItemContentUnion struct {
	InputText                         *InputText                         `queryParam:"inline" union:"member"`
	AgentMessageItemContentInputImage *AgentMessageItemContentInputImage `queryParam:"inline" union:"member"`
	ContentEncryptedContent           *ContentEncryptedContent           `queryParam:"inline" union:"member"`

	Type AgentMessageItemContentUnionType
}

func CreateAgentMessageItemContentUnionInputText(inputText InputText) AgentMessageItemContentUnion {
	typ := AgentMessageItemContentUnionTypeInputText

	typStr := InputTextType(typ)
	inputText.Type = typStr

	return AgentMessageItemContentUnion{
		InputText: &inputText,
		Type:      typ,
	}
}

func CreateAgentMessageItemContentUnionInputImage(inputImage AgentMessageItemContentInputImage) AgentMessageItemContentUnion {
	typ := AgentMessageItemContentUnionTypeInputImage

	typStr := AgentMessageItemTypeInputImage(typ)
	inputImage.Type = typStr

	return AgentMessageItemContentUnion{
		AgentMessageItemContentInputImage: &inputImage,
		Type:                              typ,
	}
}

func CreateAgentMessageItemContentUnionEncryptedContent(encryptedContent ContentEncryptedContent) AgentMessageItemContentUnion {
	typ := AgentMessageItemContentUnionTypeEncryptedContent

	typStr := TypeEncryptedContent(typ)
	encryptedContent.Type = typStr

	return AgentMessageItemContentUnion{
		ContentEncryptedContent: &encryptedContent,
		Type:                    typ,
	}
}

func (u *AgentMessageItemContentUnion) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "input_text":
		inputText := new(InputText)
		if err := utils.UnmarshalJSON(data, &inputText, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_text) type InputText within AgentMessageItemContentUnion: %w", string(data), err)
		}

		u.InputText = inputText
		u.Type = AgentMessageItemContentUnionTypeInputText
		return nil
	case "input_image":
		agentMessageItemContentInputImage := new(AgentMessageItemContentInputImage)
		if err := utils.UnmarshalJSON(data, &agentMessageItemContentInputImage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_image) type AgentMessageItemContentInputImage within AgentMessageItemContentUnion: %w", string(data), err)
		}

		u.AgentMessageItemContentInputImage = agentMessageItemContentInputImage
		u.Type = AgentMessageItemContentUnionTypeInputImage
		return nil
	case "encrypted_content":
		contentEncryptedContent := new(ContentEncryptedContent)
		if err := utils.UnmarshalJSON(data, &contentEncryptedContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == encrypted_content) type ContentEncryptedContent within AgentMessageItemContentUnion: %w", string(data), err)
		}

		u.ContentEncryptedContent = contentEncryptedContent
		u.Type = AgentMessageItemContentUnionTypeEncryptedContent
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AgentMessageItemContentUnion", string(data))
}

func (u AgentMessageItemContentUnion) MarshalJSON() ([]byte, error) {
	if u.InputText != nil {
		return utils.MarshalJSON(u.InputText, "", true)
	}

	if u.AgentMessageItemContentInputImage != nil {
		return utils.MarshalJSON(u.AgentMessageItemContentInputImage, "", true)
	}

	if u.ContentEncryptedContent != nil {
		return utils.MarshalJSON(u.ContentEncryptedContent, "", true)
	}

	return nil, errors.New("could not marshal union type AgentMessageItemContentUnion: all fields are null")
}

type TypeAgentMessage string

const (
	TypeAgentMessageAgentMessage TypeAgentMessage = "agent_message"
)

func (e TypeAgentMessage) ToPointer() *TypeAgentMessage {
	return &e
}
func (e *TypeAgentMessage) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent_message":
		*e = TypeAgentMessage(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeAgentMessage: %v", v)
	}
}

// AgentMessageItem - A message routed between agents in a multi-agent session
type AgentMessageItem struct {
	Agent                optionalnullable.OptionalNullable[Agent]  `json:"agent,omitzero"`
	Author               string                                    `json:"author"`
	Content              []AgentMessageItemContentUnion            `json:"content"`
	ID                   optionalnullable.OptionalNullable[string] `json:"id,omitzero"`
	Recipient            string                                    `json:"recipient"`
	Type                 TypeAgentMessage                          `json:"type"`
	AdditionalProperties map[string]any                            `additionalProperties:"true" json:"-"`
}

func (a AgentMessageItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentMessageItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentMessageItem) GetAgent() optionalnullable.OptionalNullable[Agent] {
	if a == nil {
		return nil
	}
	return a.Agent
}

func (a *AgentMessageItem) GetAuthor() string {
	if a == nil {
		return ""
	}
	return a.Author
}

func (a *AgentMessageItem) GetContent() []AgentMessageItemContentUnion {
	if a == nil {
		return []AgentMessageItemContentUnion{}
	}
	return a.Content
}

func (a *AgentMessageItem) GetID() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AgentMessageItem) GetRecipient() string {
	if a == nil {
		return ""
	}
	return a.Recipient
}

func (a *AgentMessageItem) GetType() TypeAgentMessage {
	if a == nil {
		return TypeAgentMessage("")
	}
	return a.Type
}

func (a *AgentMessageItem) GetAdditionalProperties() map[string]any {
	if a == nil {
		return nil
	}
	return a.AdditionalProperties
}
