// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type AlignmentUnavailableCallRecordOutcome string

const (
	AlignmentUnavailableCallRecordOutcomeUnavailable AlignmentUnavailableCallRecordOutcome = "unavailable"
)

func (e AlignmentUnavailableCallRecordOutcome) ToPointer() *AlignmentUnavailableCallRecordOutcome {
	return &e
}
func (e *AlignmentUnavailableCallRecordOutcome) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unavailable":
		*e = AlignmentUnavailableCallRecordOutcome(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AlignmentUnavailableCallRecordOutcome: %v", v)
	}
}

type AlignmentUnavailableCallRecordReason string

const (
	AlignmentUnavailableCallRecordReasonCut             AlignmentUnavailableCallRecordReason = "cut"
	AlignmentUnavailableCallRecordReasonEvaluatorError  AlignmentUnavailableCallRecordReason = "evaluator_error"
	AlignmentUnavailableCallRecordReasonMalformedAnswer AlignmentUnavailableCallRecordReason = "malformed_answer"
	AlignmentUnavailableCallRecordReasonTimeLimit       AlignmentUnavailableCallRecordReason = "time_limit"
)

func (e AlignmentUnavailableCallRecordReason) ToPointer() *AlignmentUnavailableCallRecordReason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AlignmentUnavailableCallRecordReason) IsExact() bool {
	if e != nil {
		switch *e {
		case "cut", "evaluator_error", "malformed_answer", "time_limit":
			return true
		}
	}
	return false
}

type AlignmentUnavailableCallRecord struct {
	// Number of the record, from 1. A record is one evaluated assistant message; a model call of a server-tool loop that produces several messages has one record per message, and a retry continues the numbering.
	Call    int64                                 `json:"call"`
	Outcome AlignmentUnavailableCallRecordOutcome `json:"outcome"`
	Reason  AlignmentUnavailableCallRecordReason  `json:"reason"`
}

func (a AlignmentUnavailableCallRecord) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlignmentUnavailableCallRecord) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AlignmentUnavailableCallRecord) GetCall() int64 {
	if a == nil {
		return 0
	}
	return a.Call
}

func (a *AlignmentUnavailableCallRecord) GetOutcome() AlignmentUnavailableCallRecordOutcome {
	if a == nil {
		return AlignmentUnavailableCallRecordOutcome("")
	}
	return a.Outcome
}

func (a *AlignmentUnavailableCallRecord) GetReason() AlignmentUnavailableCallRecordReason {
	if a == nil {
		return AlignmentUnavailableCallRecordReason("")
	}
	return a.Reason
}
