// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

// AlignmentChatAudio - The audio of the withheld message: its `id` and `transcript`. The plugin does not retain `data` or `expires_at`.
type AlignmentChatAudio struct {
	// The provider id of the audio.
	ID *string `json:"id,omitzero"`
	// The transcript of the audio.
	Transcript string `json:"transcript"`
}

func (a AlignmentChatAudio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlignmentChatAudio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AlignmentChatAudio) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AlignmentChatAudio) GetTranscript() string {
	if a == nil {
		return ""
	}
	return a.Transcript
}
