// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type AnthropicCitationWebSearchResultLocationParamType string

const (
	AnthropicCitationWebSearchResultLocationParamTypeWebSearchResultLocation AnthropicCitationWebSearchResultLocationParamType = "web_search_result_location"
)

func (e AnthropicCitationWebSearchResultLocationParamType) ToPointer() *AnthropicCitationWebSearchResultLocationParamType {
	return &e
}
func (e *AnthropicCitationWebSearchResultLocationParamType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "web_search_result_location":
		*e = AnthropicCitationWebSearchResultLocationParamType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicCitationWebSearchResultLocationParamType: %v", v)
	}
}

type AnthropicCitationWebSearchResultLocationParam struct {
	CitedText      string                                            `json:"cited_text"`
	EncryptedIndex string                                            `json:"encrypted_index"`
	Title          *string                                           `json:"title"`
	Type           AnthropicCitationWebSearchResultLocationParamType `json:"type"`
	URL            string                                            `json:"url"`
}

func (a AnthropicCitationWebSearchResultLocationParam) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicCitationWebSearchResultLocationParam) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicCitationWebSearchResultLocationParam) GetCitedText() string {
	if a == nil {
		return ""
	}
	return a.CitedText
}

func (a *AnthropicCitationWebSearchResultLocationParam) GetEncryptedIndex() string {
	if a == nil {
		return ""
	}
	return a.EncryptedIndex
}

func (a *AnthropicCitationWebSearchResultLocationParam) GetTitle() *string {
	if a == nil {
		return nil
	}
	return a.Title
}

func (a *AnthropicCitationWebSearchResultLocationParam) GetType() AnthropicCitationWebSearchResultLocationParamType {
	if a == nil {
		return AnthropicCitationWebSearchResultLocationParamType("")
	}
	return a.Type
}

func (a *AnthropicCitationWebSearchResultLocationParam) GetURL() string {
	if a == nil {
		return ""
	}
	return a.URL
}
