// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type AnthropicRedactedThinkingBlockType string

const (
	AnthropicRedactedThinkingBlockTypeRedactedThinking AnthropicRedactedThinkingBlockType = "redacted_thinking"
)

func (e AnthropicRedactedThinkingBlockType) ToPointer() *AnthropicRedactedThinkingBlockType {
	return &e
}
func (e *AnthropicRedactedThinkingBlockType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "redacted_thinking":
		*e = AnthropicRedactedThinkingBlockType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicRedactedThinkingBlockType: %v", v)
	}
}

type AnthropicRedactedThinkingBlock struct {
	Data string                             `json:"data"`
	Type AnthropicRedactedThinkingBlockType `json:"type"`
}

func (a AnthropicRedactedThinkingBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicRedactedThinkingBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicRedactedThinkingBlock) GetData() string {
	if a == nil {
		return ""
	}
	return a.Data
}

func (a *AnthropicRedactedThinkingBlock) GetType() AnthropicRedactedThinkingBlockType {
	if a == nil {
		return AnthropicRedactedThinkingBlockType("")
	}
	return a.Type
}
