// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type AnthropicCompactionBlockType string

const (
	AnthropicCompactionBlockTypeCompaction AnthropicCompactionBlockType = "compaction"
)

func (e AnthropicCompactionBlockType) ToPointer() *AnthropicCompactionBlockType {
	return &e
}
func (e *AnthropicCompactionBlockType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "compaction":
		*e = AnthropicCompactionBlockType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicCompactionBlockType: %v", v)
	}
}

type AnthropicCompactionBlock struct {
	Content          *string                                   `json:"content"`
	EncryptedContent optionalnullable.OptionalNullable[string] `json:"encrypted_content,omitzero"`
	Type             AnthropicCompactionBlockType              `json:"type"`
}

func (a AnthropicCompactionBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicCompactionBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicCompactionBlock) GetContent() *string {
	if a == nil {
		return nil
	}
	return a.Content
}

func (a *AnthropicCompactionBlock) GetEncryptedContent() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.EncryptedContent
}

func (a *AnthropicCompactionBlock) GetType() AnthropicCompactionBlockType {
	if a == nil {
		return AnthropicCompactionBlockType("")
	}
	return a.Type
}
