// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type AnthropicCallerType string

const (
	AnthropicCallerTypeCodeExecution20250825 AnthropicCallerType = "code_execution_20250825"
	AnthropicCallerTypeCodeExecution20260120 AnthropicCallerType = "code_execution_20260120"
	AnthropicCallerTypeDirect                AnthropicCallerType = "direct"
	AnthropicCallerTypeUnknown               AnthropicCallerType = "UNKNOWN"
)

type AnthropicCaller struct {
	AnthropicDirectCaller                *AnthropicDirectCaller                `queryParam:"inline" union:"member"`
	AnthropicCodeExecution20250825Caller *AnthropicCodeExecution20250825Caller `queryParam:"inline" union:"member"`
	AnthropicCodeExecution20260120Caller *AnthropicCodeExecution20260120Caller `queryParam:"inline" union:"member"`
	UnknownRaw                           json.RawMessage                       `json:"-" union:"unknown"`

	Type AnthropicCallerType
}

func CreateAnthropicCallerCodeExecution20250825(codeExecution20250825 AnthropicCodeExecution20250825Caller) AnthropicCaller {
	typ := AnthropicCallerTypeCodeExecution20250825

	typStr := AnthropicCodeExecution20250825CallerType(typ)
	codeExecution20250825.Type = typStr

	return AnthropicCaller{
		AnthropicCodeExecution20250825Caller: &codeExecution20250825,
		Type:                                 typ,
	}
}

func CreateAnthropicCallerCodeExecution20260120(codeExecution20260120 AnthropicCodeExecution20260120Caller) AnthropicCaller {
	typ := AnthropicCallerTypeCodeExecution20260120

	typStr := AnthropicCodeExecution20260120CallerType(typ)
	codeExecution20260120.Type = typStr

	return AnthropicCaller{
		AnthropicCodeExecution20260120Caller: &codeExecution20260120,
		Type:                                 typ,
	}
}

func CreateAnthropicCallerDirect(direct AnthropicDirectCaller) AnthropicCaller {
	typ := AnthropicCallerTypeDirect

	typStr := AnthropicDirectCallerType(typ)
	direct.Type = typStr

	return AnthropicCaller{
		AnthropicDirectCaller: &direct,
		Type:                  typ,
	}
}

func CreateAnthropicCallerUnknown(raw json.RawMessage) AnthropicCaller {
	return AnthropicCaller{
		UnknownRaw: raw,
		Type:       AnthropicCallerTypeUnknown,
	}
}

func (u AnthropicCaller) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u AnthropicCaller) IsUnknown() bool {
	return u.Type == AnthropicCallerTypeUnknown
}

func (u *AnthropicCaller) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnthropicCallerTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnthropicCallerTypeUnknown
		return nil
	}

	switch dis.Type {
	case "code_execution_20250825":
		anthropicCodeExecution20250825Caller := new(AnthropicCodeExecution20250825Caller)
		if err := utils.UnmarshalJSON(data, &anthropicCodeExecution20250825Caller, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution_20250825) type AnthropicCodeExecution20250825Caller within AnthropicCaller: %w", string(data), err)
		}

		u.AnthropicCodeExecution20250825Caller = anthropicCodeExecution20250825Caller
		u.Type = AnthropicCallerTypeCodeExecution20250825
		return nil
	case "code_execution_20260120":
		anthropicCodeExecution20260120Caller := new(AnthropicCodeExecution20260120Caller)
		if err := utils.UnmarshalJSON(data, &anthropicCodeExecution20260120Caller, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution_20260120) type AnthropicCodeExecution20260120Caller within AnthropicCaller: %w", string(data), err)
		}

		u.AnthropicCodeExecution20260120Caller = anthropicCodeExecution20260120Caller
		u.Type = AnthropicCallerTypeCodeExecution20260120
		return nil
	case "direct":
		anthropicDirectCaller := new(AnthropicDirectCaller)
		if err := utils.UnmarshalJSON(data, &anthropicDirectCaller, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == direct) type AnthropicDirectCaller within AnthropicCaller: %w", string(data), err)
		}

		u.AnthropicDirectCaller = anthropicDirectCaller
		u.Type = AnthropicCallerTypeDirect
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnthropicCallerTypeUnknown
		return nil
	}

}

func (u AnthropicCaller) MarshalJSON() ([]byte, error) {
	if u.AnthropicDirectCaller != nil {
		return utils.MarshalJSON(u.AnthropicDirectCaller, "", true)
	}

	if u.AnthropicCodeExecution20250825Caller != nil {
		return utils.MarshalJSON(u.AnthropicCodeExecution20250825Caller, "", true)
	}

	if u.AnthropicCodeExecution20260120Caller != nil {
		return utils.MarshalJSON(u.AnthropicCodeExecution20260120Caller, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type AnthropicCaller: all fields are null")
}
