// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type AnthropicMessageOutputConfig struct {
	Effort optionalnullable.OptionalNullable[AnthropicOutputEffort] `json:"effort,omitzero"`
}

func (a *AnthropicMessageOutputConfig) GetEffort() optionalnullable.OptionalNullable[AnthropicOutputEffort] {
	if a == nil {
		return nil
	}
	return a.Effort
}
