// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type AnthropicWebFetchContentType string

const (
	AnthropicWebFetchContentTypeWebFetchResult          AnthropicWebFetchContentType = "web_fetch_result"
	AnthropicWebFetchContentTypeWebFetchToolResultError AnthropicWebFetchContentType = "web_fetch_tool_result_error"
	AnthropicWebFetchContentTypeUnknown                 AnthropicWebFetchContentType = "UNKNOWN"
)

type AnthropicWebFetchContent struct {
	AnthropicWebFetchToolResultError *AnthropicWebFetchToolResultError `queryParam:"inline" union:"member"`
	AnthropicWebFetchBlock           *AnthropicWebFetchBlock           `queryParam:"inline" union:"member"`
	UnknownRaw                       json.RawMessage                   `json:"-" union:"unknown"`

	Type AnthropicWebFetchContentType
}

func CreateAnthropicWebFetchContentWebFetchResult(webFetchResult AnthropicWebFetchBlock) AnthropicWebFetchContent {
	typ := AnthropicWebFetchContentTypeWebFetchResult

	typStr := AnthropicWebFetchBlockType(typ)
	webFetchResult.Type = typStr

	return AnthropicWebFetchContent{
		AnthropicWebFetchBlock: &webFetchResult,
		Type:                   typ,
	}
}

func CreateAnthropicWebFetchContentWebFetchToolResultError(webFetchToolResultError AnthropicWebFetchToolResultError) AnthropicWebFetchContent {
	typ := AnthropicWebFetchContentTypeWebFetchToolResultError

	typStr := AnthropicWebFetchToolResultErrorType(typ)
	webFetchToolResultError.Type = typStr

	return AnthropicWebFetchContent{
		AnthropicWebFetchToolResultError: &webFetchToolResultError,
		Type:                             typ,
	}
}

func CreateAnthropicWebFetchContentUnknown(raw json.RawMessage) AnthropicWebFetchContent {
	return AnthropicWebFetchContent{
		UnknownRaw: raw,
		Type:       AnthropicWebFetchContentTypeUnknown,
	}
}

func (u AnthropicWebFetchContent) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u AnthropicWebFetchContent) IsUnknown() bool {
	return u.Type == AnthropicWebFetchContentTypeUnknown
}

func (u *AnthropicWebFetchContent) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnthropicWebFetchContentTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnthropicWebFetchContentTypeUnknown
		return nil
	}

	switch dis.Type {
	case "web_fetch_result":
		anthropicWebFetchBlock := new(AnthropicWebFetchBlock)
		if err := utils.UnmarshalJSON(data, &anthropicWebFetchBlock, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == web_fetch_result) type AnthropicWebFetchBlock within AnthropicWebFetchContent: %w", string(data), err)
		}

		u.AnthropicWebFetchBlock = anthropicWebFetchBlock
		u.Type = AnthropicWebFetchContentTypeWebFetchResult
		return nil
	case "web_fetch_tool_result_error":
		anthropicWebFetchToolResultError := new(AnthropicWebFetchToolResultError)
		if err := utils.UnmarshalJSON(data, &anthropicWebFetchToolResultError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == web_fetch_tool_result_error) type AnthropicWebFetchToolResultError within AnthropicWebFetchContent: %w", string(data), err)
		}

		u.AnthropicWebFetchToolResultError = anthropicWebFetchToolResultError
		u.Type = AnthropicWebFetchContentTypeWebFetchToolResultError
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnthropicWebFetchContentTypeUnknown
		return nil
	}

}

func (u AnthropicWebFetchContent) MarshalJSON() ([]byte, error) {
	if u.AnthropicWebFetchToolResultError != nil {
		return utils.MarshalJSON(u.AnthropicWebFetchToolResultError, "", true)
	}

	if u.AnthropicWebFetchBlock != nil {
		return utils.MarshalJSON(u.AnthropicWebFetchBlock, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type AnthropicWebFetchContent: all fields are null")
}
