// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type BatchSubmitBodyCompletionWindow string

const (
	BatchSubmitBodyCompletionWindowTwentyFourh BatchSubmitBodyCompletionWindow = "24h"
)

func (e BatchSubmitBodyCompletionWindow) ToPointer() *BatchSubmitBodyCompletionWindow {
	return &e
}
func (e *BatchSubmitBodyCompletionWindow) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "24h":
		*e = BatchSubmitBodyCompletionWindow(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BatchSubmitBodyCompletionWindow: %v", v)
	}
}

type Endpoint string

const (
	EndpointRootV1ChatCompletions Endpoint = "/v1/chat/completions"
	EndpointRootV1Responses       Endpoint = "/v1/responses"
	EndpointRootV1Messages        Endpoint = "/v1/messages"
	EndpointRootV1Embeddings      Endpoint = "/v1/embeddings"
)

func (e Endpoint) ToPointer() *Endpoint {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Endpoint) IsExact() bool {
	if e != nil {
		switch *e {
		case "/v1/chat/completions", "/v1/responses", "/v1/messages", "/v1/embeddings":
			return true
		}
	}
	return false
}

type Request struct {
	// Request payload for the batch `endpoint`.
	Body     map[string]any `json:"body"`
	CustomID string         `json:"custom_id"`
}

func (r *Request) GetBody() map[string]any {
	if r == nil {
		return map[string]any{}
	}
	return r.Body
}

func (r *Request) GetCustomID() string {
	if r == nil {
		return ""
	}
	return r.CustomID
}

// BatchSubmitBody - Batch submit request body.
type BatchSubmitBody struct {
	CompletionWindow *BatchSubmitBodyCompletionWindow `default:"24h" json:"completion_window"`
	Endpoint         Endpoint                         `json:"endpoint"`
	Model            string                           `json:"model"`
	// Batch provider routing preferences. Only `provider.only` is supported.
	Provider optionalnullable.OptionalNullable[BatchProviderPreferences] `json:"provider,omitzero"`
	Requests []Request                                                   `json:"requests"`
}

func (b BatchSubmitBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchSubmitBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BatchSubmitBody) GetCompletionWindow() *BatchSubmitBodyCompletionWindow {
	if b == nil {
		return nil
	}
	return b.CompletionWindow
}

func (b *BatchSubmitBody) GetEndpoint() Endpoint {
	if b == nil {
		return Endpoint("")
	}
	return b.Endpoint
}

func (b *BatchSubmitBody) GetModel() string {
	if b == nil {
		return ""
	}
	return b.Model
}

func (b *BatchSubmitBody) GetProvider() optionalnullable.OptionalNullable[BatchProviderPreferences] {
	if b == nil {
		return nil
	}
	return b.Provider
}

func (b *BatchSubmitBody) GetRequests() []Request {
	if b == nil {
		return []Request{}
	}
	return b.Requests
}
