// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type BatchPaymentRequiredResponseCompletionWindow string

const (
	BatchPaymentRequiredResponseCompletionWindowTwentyFourh BatchPaymentRequiredResponseCompletionWindow = "24h"
)

func (e BatchPaymentRequiredResponseCompletionWindow) ToPointer() *BatchPaymentRequiredResponseCompletionWindow {
	return &e
}
func (e *BatchPaymentRequiredResponseCompletionWindow) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "24h":
		*e = BatchPaymentRequiredResponseCompletionWindow(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BatchPaymentRequiredResponseCompletionWindow: %v", v)
	}
}

type BatchPaymentRequiredResponseError struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

func (b *BatchPaymentRequiredResponseError) GetCode() int64 {
	if b == nil {
		return 0
	}
	return b.Code
}

func (b *BatchPaymentRequiredResponseError) GetMessage() string {
	if b == nil {
		return ""
	}
	return b.Message
}

type BatchPaymentRequiredResponseObject string

const (
	BatchPaymentRequiredResponseObjectBatch BatchPaymentRequiredResponseObject = "batch"
)

func (e BatchPaymentRequiredResponseObject) ToPointer() *BatchPaymentRequiredResponseObject {
	return &e
}
func (e *BatchPaymentRequiredResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "batch":
		*e = BatchPaymentRequiredResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BatchPaymentRequiredResponseObject: %v", v)
	}
}

type BatchPaymentRequiredResponseRequestCounts struct {
	Completed int64 `json:"completed"`
	Failed    int64 `json:"failed"`
	Total     int64 `json:"total"`
}

func (b *BatchPaymentRequiredResponseRequestCounts) GetCompleted() int64 {
	if b == nil {
		return 0
	}
	return b.Completed
}

func (b *BatchPaymentRequiredResponseRequestCounts) GetFailed() int64 {
	if b == nil {
		return 0
	}
	return b.Failed
}

func (b *BatchPaymentRequiredResponseRequestCounts) GetTotal() int64 {
	if b == nil {
		return 0
	}
	return b.Total
}

type BatchPaymentRequiredResponseStatus string

const (
	BatchPaymentRequiredResponseStatusValidating BatchPaymentRequiredResponseStatus = "validating"
	BatchPaymentRequiredResponseStatusInProgress BatchPaymentRequiredResponseStatus = "in_progress"
	BatchPaymentRequiredResponseStatusFinalizing BatchPaymentRequiredResponseStatus = "finalizing"
	BatchPaymentRequiredResponseStatusCompleted  BatchPaymentRequiredResponseStatus = "completed"
	BatchPaymentRequiredResponseStatusFailed     BatchPaymentRequiredResponseStatus = "failed"
	BatchPaymentRequiredResponseStatusExpired    BatchPaymentRequiredResponseStatus = "expired"
	BatchPaymentRequiredResponseStatusCancelling BatchPaymentRequiredResponseStatus = "cancelling"
	BatchPaymentRequiredResponseStatusCancelled  BatchPaymentRequiredResponseStatus = "cancelled"
)

func (e BatchPaymentRequiredResponseStatus) ToPointer() *BatchPaymentRequiredResponseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BatchPaymentRequiredResponseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "validating", "in_progress", "finalizing", "completed", "failed", "expired", "cancelling", "cancelled":
			return true
		}
	}
	return false
}

type BatchPaymentRequiredResponseCompletionTokensDetails struct {
	// Tokens generated by the model for audio output.
	AudioTokens optionalnullable.OptionalNullable[int64] `json:"audio_tokens,omitzero"`
	// Tokens generated by the model for image output.
	ImageTokens optionalnullable.OptionalNullable[int64] `json:"image_tokens,omitzero"`
	// Tokens generated by the model for reasoning.
	ReasoningTokens optionalnullable.OptionalNullable[int64] `json:"reasoning_tokens,omitzero"`
}

func (b *BatchPaymentRequiredResponseCompletionTokensDetails) GetAudioTokens() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.AudioTokens
}

func (b *BatchPaymentRequiredResponseCompletionTokensDetails) GetImageTokens() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.ImageTokens
}

func (b *BatchPaymentRequiredResponseCompletionTokensDetails) GetReasoningTokens() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.ReasoningTokens
}

// BatchPaymentRequiredResponsePromptTokensDetails - Breakdown of tokens used in the prompt.
type BatchPaymentRequiredResponsePromptTokensDetails struct {
	// Tokens used for input audio.
	AudioTokens optionalnullable.OptionalNullable[int64] `json:"audio_tokens,omitzero"`
	// Tokens written to cache. Only returned for models with explicit caching and cache write pricing.
	CacheWriteTokens optionalnullable.OptionalNullable[int64] `json:"cache_write_tokens,omitzero"`
	// Tokens cached by the endpoint.
	CachedTokens optionalnullable.OptionalNullable[int64] `json:"cached_tokens,omitzero"`
	// Tokens used for input files/documents.
	FileTokens optionalnullable.OptionalNullable[int64] `json:"file_tokens,omitzero"`
	// Tokens used for input video.
	VideoTokens optionalnullable.OptionalNullable[int64] `json:"video_tokens,omitzero"`
}

func (b *BatchPaymentRequiredResponsePromptTokensDetails) GetAudioTokens() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.AudioTokens
}

func (b *BatchPaymentRequiredResponsePromptTokensDetails) GetCacheWriteTokens() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.CacheWriteTokens
}

func (b *BatchPaymentRequiredResponsePromptTokensDetails) GetCachedTokens() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.CachedTokens
}

func (b *BatchPaymentRequiredResponsePromptTokensDetails) GetFileTokens() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.FileTokens
}

func (b *BatchPaymentRequiredResponsePromptTokensDetails) GetVideoTokens() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.VideoTokens
}

// BatchPaymentRequiredResponseServerToolUse - Usage for server-side tool execution (e.g., web search)
type BatchPaymentRequiredResponseServerToolUse struct {
	// Number of OpenRouter server tool calls that executed and produced a result.
	ToolCallsExecuted optionalnullable.OptionalNullable[int64] `json:"tool_calls_executed,omitzero"`
	// Total number of OpenRouter server-orchestrated tool calls the model requested, across all tool types. Provider-native tools (e.g. native web search) are not counted here.
	ToolCallsRequested optionalnullable.OptionalNullable[int64] `json:"tool_calls_requested,omitzero"`
	// Number of web searches performed by server-side tools. For server-orchestrated tool calls a web search is also counted in tool_calls_requested; provider-native web search may report web_search_requests only. Do not sum the two.
	WebSearchRequests optionalnullable.OptionalNullable[int64] `json:"web_search_requests,omitzero"`
}

func (b *BatchPaymentRequiredResponseServerToolUse) GetToolCallsExecuted() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.ToolCallsExecuted
}

func (b *BatchPaymentRequiredResponseServerToolUse) GetToolCallsRequested() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.ToolCallsRequested
}

func (b *BatchPaymentRequiredResponseServerToolUse) GetWebSearchRequests() optionalnullable.OptionalNullable[int64] {
	if b == nil {
		return nil
	}
	return b.WebSearchRequests
}

type BatchPaymentRequiredResponseUsage struct {
	CacheCreation optionalnullable.OptionalNullable[AnthropicCacheCreation] `json:"cache_creation,omitzero"`
	// The tokens generated
	CompletionTokens        int64                                                                                  `json:"completion_tokens"`
	CompletionTokensDetails optionalnullable.OptionalNullable[BatchPaymentRequiredResponseCompletionTokensDetails] `json:"completion_tokens_details,omitzero"`
	// Cost of the completion
	Cost optionalnullable.OptionalNullable[float64] `json:"cost,omitzero"`
	// Breakdown of upstream inference costs
	CostDetails optionalnullable.OptionalNullable[CostDetails] `json:"cost_details,omitzero"`
	// Whether a request was made using a Bring Your Own Key configuration
	IsBYOK     *bool                                                        `json:"is_byok,omitzero"`
	Iterations optionalnullable.OptionalNullable[[]AnthropicUsageIteration] `json:"iterations,omitzero"`
	// Including images, input audio, and tools if any
	PromptTokens int64 `json:"prompt_tokens"`
	// Breakdown of tokens used in the prompt.
	PromptTokensDetails optionalnullable.OptionalNullable[BatchPaymentRequiredResponsePromptTokensDetails] `json:"prompt_tokens_details,omitzero"`
	// Usage for server-side tool execution (e.g., web search)
	ServerToolUse optionalnullable.OptionalNullable[BatchPaymentRequiredResponseServerToolUse] `json:"server_tool_use,omitzero"`
	// The service tier used by the upstream provider for this request
	ServiceTier optionalnullable.OptionalNullable[string]         `json:"service_tier,omitzero"`
	Speed       optionalnullable.OptionalNullable[AnthropicSpeed] `json:"speed,omitzero"`
	// Sum of the above two fields
	TotalTokens int64 `json:"total_tokens"`
}

func (b BatchPaymentRequiredResponseUsage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchPaymentRequiredResponseUsage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BatchPaymentRequiredResponseUsage) GetCacheCreation() optionalnullable.OptionalNullable[AnthropicCacheCreation] {
	if b == nil {
		return nil
	}
	return b.CacheCreation
}

func (b *BatchPaymentRequiredResponseUsage) GetCompletionTokens() int64 {
	if b == nil {
		return 0
	}
	return b.CompletionTokens
}

func (b *BatchPaymentRequiredResponseUsage) GetCompletionTokensDetails() optionalnullable.OptionalNullable[BatchPaymentRequiredResponseCompletionTokensDetails] {
	if b == nil {
		return nil
	}
	return b.CompletionTokensDetails
}

func (b *BatchPaymentRequiredResponseUsage) GetCost() optionalnullable.OptionalNullable[float64] {
	if b == nil {
		return nil
	}
	return b.Cost
}

func (b *BatchPaymentRequiredResponseUsage) GetCostDetails() optionalnullable.OptionalNullable[CostDetails] {
	if b == nil {
		return nil
	}
	return b.CostDetails
}

func (b *BatchPaymentRequiredResponseUsage) GetIsBYOK() *bool {
	if b == nil {
		return nil
	}
	return b.IsBYOK
}

func (b *BatchPaymentRequiredResponseUsage) GetIterations() optionalnullable.OptionalNullable[[]AnthropicUsageIteration] {
	if b == nil {
		return nil
	}
	return b.Iterations
}

func (b *BatchPaymentRequiredResponseUsage) GetPromptTokens() int64 {
	if b == nil {
		return 0
	}
	return b.PromptTokens
}

func (b *BatchPaymentRequiredResponseUsage) GetPromptTokensDetails() optionalnullable.OptionalNullable[BatchPaymentRequiredResponsePromptTokensDetails] {
	if b == nil {
		return nil
	}
	return b.PromptTokensDetails
}

func (b *BatchPaymentRequiredResponseUsage) GetServerToolUse() optionalnullable.OptionalNullable[BatchPaymentRequiredResponseServerToolUse] {
	if b == nil {
		return nil
	}
	return b.ServerToolUse
}

func (b *BatchPaymentRequiredResponseUsage) GetServiceTier() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.ServiceTier
}

func (b *BatchPaymentRequiredResponseUsage) GetSpeed() optionalnullable.OptionalNullable[AnthropicSpeed] {
	if b == nil {
		return nil
	}
	return b.Speed
}

func (b *BatchPaymentRequiredResponseUsage) GetTotalTokens() int64 {
	if b == nil {
		return 0
	}
	return b.TotalTokens
}
