// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChatTokenLogprobTopLogprob struct {
	Token   string  `json:"token"`
	Logprob float64 `json:"logprob"`
	Bytes   []int64 `json:"bytes"`
}

func (c *ChatTokenLogprobTopLogprob) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *ChatTokenLogprobTopLogprob) GetLogprob() float64 {
	if c == nil {
		return 0.0
	}
	return c.Logprob
}

func (c *ChatTokenLogprobTopLogprob) GetBytes() []int64 {
	if c == nil {
		return nil
	}
	return c.Bytes
}

// ChatTokenLogprob - Token log probability information
type ChatTokenLogprob struct {
	// The token
	Token string `json:"token"`
	// Log probability of the token
	Logprob float64 `json:"logprob"`
	// UTF-8 bytes of the token
	Bytes []int64 `json:"bytes"`
	// Top alternative tokens with probabilities
	TopLogprobs []ChatTokenLogprobTopLogprob `json:"top_logprobs"`
}

func (c *ChatTokenLogprob) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *ChatTokenLogprob) GetLogprob() float64 {
	if c == nil {
		return 0.0
	}
	return c.Logprob
}

func (c *ChatTokenLogprob) GetBytes() []int64 {
	if c == nil {
		return nil
	}
	return c.Bytes
}

func (c *ChatTokenLogprob) GetTopLogprobs() []ChatTokenLogprobTopLogprob {
	if c == nil {
		return []ChatTokenLogprobTopLogprob{}
	}
	return c.TopLogprobs
}
