// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type ContainerReferenceEnvironmentType string

const (
	ContainerReferenceEnvironmentTypeContainerReference ContainerReferenceEnvironmentType = "container_reference"
)

func (e ContainerReferenceEnvironmentType) ToPointer() *ContainerReferenceEnvironmentType {
	return &e
}
func (e *ContainerReferenceEnvironmentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "container_reference":
		*e = ContainerReferenceEnvironmentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContainerReferenceEnvironmentType: %v", v)
	}
}

// ContainerReferenceEnvironment - Reference to a previously created container to reuse.
type ContainerReferenceEnvironment struct {
	// Identifier of an existing container to reuse (max 20 characters).
	ContainerID string                            `json:"container_id"`
	Type        ContainerReferenceEnvironmentType `json:"type"`
}

func (c ContainerReferenceEnvironment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContainerReferenceEnvironment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContainerReferenceEnvironment) GetContainerID() string {
	if c == nil {
		return ""
	}
	return c.ContainerID
}

func (c *ContainerReferenceEnvironment) GetType() ContainerReferenceEnvironmentType {
	if c == nil {
		return ContainerReferenceEnvironmentType("")
	}
	return c.Type
}
