// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type ContentPartImageImageURL struct {
	URL string `json:"url"`
}

func (c ContentPartImageImageURL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentPartImageImageURL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentPartImageImageURL) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

type ContentPartImageType string

const (
	ContentPartImageTypeImageURL ContentPartImageType = "image_url"
)

func (e ContentPartImageType) ToPointer() *ContentPartImageType {
	return &e
}
func (e *ContentPartImageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "image_url":
		*e = ContentPartImageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContentPartImageType: %v", v)
	}
}

type ContentPartImage struct {
	ImageURL ContentPartImageImageURL `json:"image_url"`
	Type     ContentPartImageType     `json:"type"`
}

func (c ContentPartImage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentPartImage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentPartImage) GetImageURL() ContentPartImageImageURL {
	if c == nil {
		return ContentPartImageImageURL{}
	}
	return c.ImageURL
}

func (c *ContentPartImage) GetType() ContentPartImageType {
	if c == nil {
		return ContentPartImageType("")
	}
	return c.Type
}
