// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type ContainerAutoEnvironmentType string

const (
	ContainerAutoEnvironmentTypeContainerAuto ContainerAutoEnvironmentType = "container_auto"
)

func (e ContainerAutoEnvironmentType) ToPointer() *ContainerAutoEnvironmentType {
	return &e
}
func (e *ContainerAutoEnvironmentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "container_auto":
		*e = ContainerAutoEnvironmentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContainerAutoEnvironmentType: %v", v)
	}
}

// ContainerAutoEnvironment - An OpenRouter-managed, auto-provisioned ephemeral container.
type ContainerAutoEnvironment struct {
	Type ContainerAutoEnvironmentType `json:"type"`
}

func (c ContainerAutoEnvironment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContainerAutoEnvironment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContainerAutoEnvironment) GetType() ContainerAutoEnvironmentType {
	if c == nil {
		return ContainerAutoEnvironmentType("")
	}
	return c.Type
}
