// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type CustomToolCallItemType string

const (
	CustomToolCallItemTypeCustomToolCall CustomToolCallItemType = "custom_tool_call"
)

func (e CustomToolCallItemType) ToPointer() *CustomToolCallItemType {
	return &e
}
func (e *CustomToolCallItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom_tool_call":
		*e = CustomToolCallItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomToolCallItemType: %v", v)
	}
}

// CustomToolCallItem - A call to a custom (freeform-grammar) tool created by the model — distinct from `function_call`. Used for tools like Codex CLI's `apply_patch` whose payload is opaque text rather than JSON arguments.
type CustomToolCallItem struct {
	// True when the model called a tool declared with `async: true` and may continue its turn before the output is returned. Return the result in a later request as a `function_call_output` with this `call_id`.
	Async  optionalnullable.OptionalNullable[bool]   `json:"async,omitzero"`
	CallID string                                    `json:"call_id"`
	ID     optionalnullable.OptionalNullable[string] `json:"id,omitzero"`
	Input  string                                    `json:"input"`
	Name   string                                    `json:"name"`
	// Namespace qualifier for tools registered as part of a namespace tool group (e.g. an MCP server)
	Namespace optionalnullable.OptionalNullable[string]         `json:"namespace,omitzero"`
	Status    optionalnullable.OptionalNullable[ToolCallStatus] `json:"status,omitzero"`
	Type      CustomToolCallItemType                            `json:"type"`
}

func (c CustomToolCallItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomToolCallItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomToolCallItem) GetAsync() optionalnullable.OptionalNullable[bool] {
	if c == nil {
		return nil
	}
	return c.Async
}

func (c *CustomToolCallItem) GetCallID() string {
	if c == nil {
		return ""
	}
	return c.CallID
}

func (c *CustomToolCallItem) GetID() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CustomToolCallItem) GetInput() string {
	if c == nil {
		return ""
	}
	return c.Input
}

func (c *CustomToolCallItem) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomToolCallItem) GetNamespace() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Namespace
}

func (c *CustomToolCallItem) GetStatus() optionalnullable.OptionalNullable[ToolCallStatus] {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CustomToolCallItem) GetType() CustomToolCallItemType {
	if c == nil {
		return CustomToolCallItemType("")
	}
	return c.Type
}
