// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type Syntax string

const (
	SyntaxLark  Syntax = "lark"
	SyntaxRegex Syntax = "regex"
)

func (e Syntax) ToPointer() *Syntax {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Syntax) IsExact() bool {
	if e != nil {
		switch *e {
		case "lark", "regex":
			return true
		}
	}
	return false
}

type FormatTypeGrammar string

const (
	FormatTypeGrammarGrammar FormatTypeGrammar = "grammar"
)

func (e FormatTypeGrammar) ToPointer() *FormatTypeGrammar {
	return &e
}
func (e *FormatTypeGrammar) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "grammar":
		*e = FormatTypeGrammar(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FormatTypeGrammar: %v", v)
	}
}

type FormatGrammar struct {
	Definition string            `json:"definition"`
	Syntax     Syntax            `json:"syntax"`
	Type       FormatTypeGrammar `json:"type"`
}

func (f FormatGrammar) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FormatGrammar) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FormatGrammar) GetDefinition() string {
	if f == nil {
		return ""
	}
	return f.Definition
}

func (f *FormatGrammar) GetSyntax() Syntax {
	if f == nil {
		return Syntax("")
	}
	return f.Syntax
}

func (f *FormatGrammar) GetType() FormatTypeGrammar {
	if f == nil {
		return FormatTypeGrammar("")
	}
	return f.Type
}

type FormatTypeText string

const (
	FormatTypeTextText FormatTypeText = "text"
)

func (e FormatTypeText) ToPointer() *FormatTypeText {
	return &e
}
func (e *FormatTypeText) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		*e = FormatTypeText(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FormatTypeText: %v", v)
	}
}

type FormatText struct {
	Type FormatTypeText `json:"type"`
}

func (f FormatText) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FormatText) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FormatText) GetType() FormatTypeText {
	if f == nil {
		return FormatTypeText("")
	}
	return f.Type
}

type FormatType string

const (
	FormatTypeTextValue    FormatType = "text"
	FormatTypeGrammarValue FormatType = "grammar"
	FormatTypeUnknown      FormatType = "UNKNOWN"
)

type Format struct {
	FormatText    *FormatText     `queryParam:"inline" union:"member"`
	FormatGrammar *FormatGrammar  `queryParam:"inline" union:"member"`
	UnknownRaw    json.RawMessage `json:"-" union:"unknown"`

	Type FormatType
}

func CreateFormatText(text FormatText) Format {
	typ := FormatTypeTextValue

	typStr := FormatTypeText(typ)
	text.Type = typStr

	return Format{
		FormatText: &text,
		Type:       typ,
	}
}

func CreateFormatGrammar(grammar FormatGrammar) Format {
	typ := FormatTypeGrammarValue

	typStr := FormatTypeGrammar(typ)
	grammar.Type = typStr

	return Format{
		FormatGrammar: &grammar,
		Type:          typ,
	}
}

func CreateFormatUnknown(raw json.RawMessage) Format {
	return Format{
		UnknownRaw: raw,
		Type:       FormatTypeUnknown,
	}
}

func (u Format) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Format) IsUnknown() bool {
	return u.Type == FormatTypeUnknown
}

func (u *Format) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FormatTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FormatTypeUnknown
		return nil
	}

	switch dis.Type {
	case "text":
		formatText := new(FormatText)
		if err := utils.UnmarshalJSON(data, &formatText, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type FormatText within Format: %w", string(data), err)
		}

		u.FormatText = formatText
		u.Type = FormatTypeTextValue
		return nil
	case "grammar":
		formatGrammar := new(FormatGrammar)
		if err := utils.UnmarshalJSON(data, &formatGrammar, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == grammar) type FormatGrammar within Format: %w", string(data), err)
		}

		u.FormatGrammar = formatGrammar
		u.Type = FormatTypeGrammarValue
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FormatTypeUnknown
		return nil
	}

}

func (u Format) MarshalJSON() ([]byte, error) {
	if u.FormatText != nil {
		return utils.MarshalJSON(u.FormatText, "", true)
	}

	if u.FormatGrammar != nil {
		return utils.MarshalJSON(u.FormatGrammar, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Format: all fields are null")
}

type TypeCustom string

const (
	TypeCustomCustom TypeCustom = "custom"
)

func (e TypeCustom) ToPointer() *TypeCustom {
	return &e
}
func (e *TypeCustom) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom":
		*e = TypeCustom(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeCustom: %v", v)
	}
}

// CustomTool - Custom tool configuration
type CustomTool struct {
	Description *string    `json:"description,omitzero"`
	Format      *Format    `json:"format,omitzero"`
	Name        string     `json:"name"`
	Type        TypeCustom `json:"type"`
}

func (c CustomTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomTool) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomTool) GetFormat() *Format {
	if c == nil {
		return nil
	}
	return c.Format
}

func (c *CustomTool) GetFormatText() *FormatText {
	if v := c.GetFormat(); v != nil {
		return v.FormatText
	}
	return nil
}

func (c *CustomTool) GetFormatGrammar() *FormatGrammar {
	if v := c.GetFormat(); v != nil {
		return v.FormatGrammar
	}
	return nil
}

func (c *CustomTool) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomTool) GetType() TypeCustom {
	if c == nil {
		return TypeCustom("")
	}
	return c.Type
}
