// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type EnumCapabilityType string

const (
	EnumCapabilityTypeEnum EnumCapabilityType = "enum"
)

func (e EnumCapabilityType) ToPointer() *EnumCapabilityType {
	return &e
}
func (e *EnumCapabilityType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "enum":
		*e = EnumCapabilityType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnumCapabilityType: %v", v)
	}
}

// EnumCapability - A parameter that accepts one of a discrete set of string values.
type EnumCapability struct {
	Type   EnumCapabilityType `json:"type"`
	Values []string           `json:"values"`
}

func (e EnumCapability) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnumCapability) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnumCapability) GetType() EnumCapabilityType {
	if e == nil {
		return EnumCapabilityType("")
	}
	return e.Type
}

func (e *EnumCapability) GetValues() []string {
	if e == nil {
		return []string{}
	}
	return e.Values
}
