// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type FiltersType string

const (
	FiltersTypeEq  FiltersType = "eq"
	FiltersTypeNe  FiltersType = "ne"
	FiltersTypeGt  FiltersType = "gt"
	FiltersTypeGte FiltersType = "gte"
	FiltersTypeLt  FiltersType = "lt"
	FiltersTypeLte FiltersType = "lte"
)

func (e FiltersType) ToPointer() *FiltersType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FiltersType) IsExact() bool {
	if e != nil {
		switch *e {
		case "eq", "ne", "gt", "gte", "lt", "lte":
			return true
		}
	}
	return false
}

type Value1Type string

const (
	Value1TypeStr    Value1Type = "str"
	Value1TypeNumber Value1Type = "number"
)

type Value1 struct {
	Str    *string  `queryParam:"inline" union:"member"`
	Number *float64 `queryParam:"inline" union:"member"`

	Type Value1Type
}

func CreateValue1Str(str string) Value1 {
	typ := Value1TypeStr

	return Value1{
		Str:  &str,
		Type: typ,
	}
}

func CreateValue1Number(number float64) Value1 {
	typ := Value1TypeNumber

	return Value1{
		Number: &number,
		Type:   typ,
	}
}

func (u *Value1) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeNumber,
			Value: &number,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value1", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value1", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(Value1Type)
	switch best.Type {
	case Value1TypeStr:
		u.Str = best.Value.(*string)
		return nil
	case Value1TypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value1", string(data))
}

func (u Value1) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type Value1: all fields are null")
}

type Value2Type string

const (
	Value2TypeStr           Value2Type = "str"
	Value2TypeNumber        Value2Type = "number"
	Value2TypeBoolean       Value2Type = "boolean"
	Value2TypeArrayOfValue1 Value2Type = "arrayOfValue1"
)

type Value2 struct {
	Str           *string  `queryParam:"inline" union:"member"`
	Number        *float64 `queryParam:"inline" union:"member"`
	Boolean       *bool    `queryParam:"inline" union:"member"`
	ArrayOfValue1 []Value1 `queryParam:"inline" union:"member"`

	Type Value2Type
}

func CreateValue2Str(str string) Value2 {
	typ := Value2TypeStr

	return Value2{
		Str:  &str,
		Type: typ,
	}
}

func CreateValue2Number(number float64) Value2 {
	typ := Value2TypeNumber

	return Value2{
		Number: &number,
		Type:   typ,
	}
}

func CreateValue2Boolean(boolean bool) Value2 {
	typ := Value2TypeBoolean

	return Value2{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateValue2ArrayOfValue1(arrayOfValue1 []Value1) Value2 {
	typ := Value2TypeArrayOfValue1

	return Value2{
		ArrayOfValue1: arrayOfValue1,
		Type:          typ,
	}
}

func (u *Value2) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeNumber,
			Value: &number,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeBoolean,
			Value: &boolean,
		})
	}

	var arrayOfValue1 []Value1 = []Value1{}
	if err := utils.UnmarshalJSON(data, &arrayOfValue1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeArrayOfValue1,
			Value: arrayOfValue1,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value2", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value2", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(Value2Type)
	switch best.Type {
	case Value2TypeStr:
		u.Str = best.Value.(*string)
		return nil
	case Value2TypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case Value2TypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case Value2TypeArrayOfValue1:
		u.ArrayOfValue1 = best.Value.([]Value1)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value2", string(data))
}

func (u Value2) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.ArrayOfValue1 != nil {
		return utils.MarshalJSON(u.ArrayOfValue1, "", true)
	}

	return nil, errors.New("could not marshal union type Value2: all fields are null")
}

type Filters struct {
	Key   string      `json:"key"`
	Type  FiltersType `json:"type"`
	Value Value2      `json:"value"`
}

func (f Filters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *Filters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *Filters) GetKey() string {
	if f == nil {
		return ""
	}
	return f.Key
}

func (f *Filters) GetType() FiltersType {
	if f == nil {
		return FiltersType("")
	}
	return f.Type
}

func (f *Filters) GetValue() Value2 {
	if f == nil {
		return Value2{}
	}
	return f.Value
}

type FiltersUnionType string

const (
	FiltersUnionTypeFilters        FiltersUnionType = "filters"
	FiltersUnionTypeCompoundFilter FiltersUnionType = "CompoundFilter"
	FiltersUnionTypeAny            FiltersUnionType = "any"
)

type FiltersUnion struct {
	Filters        *Filters        `queryParam:"inline" union:"member"`
	CompoundFilter *CompoundFilter `queryParam:"inline" union:"member"`
	Any            any             `queryParam:"inline" union:"member"`

	Type FiltersUnionType
}

func CreateFiltersUnionFilters(filters Filters) FiltersUnion {
	typ := FiltersUnionTypeFilters

	return FiltersUnion{
		Filters: &filters,
		Type:    typ,
	}
}

func CreateFiltersUnionCompoundFilter(compoundFilter CompoundFilter) FiltersUnion {
	typ := FiltersUnionTypeCompoundFilter

	return FiltersUnion{
		CompoundFilter: &compoundFilter,
		Type:           typ,
	}
}

func CreateFiltersUnionAny(anyT any) FiltersUnion {
	typ := FiltersUnionTypeAny

	return FiltersUnion{
		Any:  anyT,
		Type: typ,
	}
}

func (u *FiltersUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var filters Filters = Filters{}
	if err := utils.UnmarshalJSON(data, &filters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiltersUnionTypeFilters,
			Value: &filters,
		})
	}

	var compoundFilter CompoundFilter = CompoundFilter{}
	if err := utils.UnmarshalJSON(data, &compoundFilter, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiltersUnionTypeCompoundFilter,
			Value: &compoundFilter,
		})
	}

	var anyVar any = nil
	if err := utils.UnmarshalJSON(data, &anyVar, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiltersUnionTypeAny,
			Value: anyVar,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FiltersUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FiltersUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FiltersUnionType)
	switch best.Type {
	case FiltersUnionTypeFilters:
		u.Filters = best.Value.(*Filters)
		return nil
	case FiltersUnionTypeCompoundFilter:
		u.CompoundFilter = best.Value.(*CompoundFilter)
		return nil
	case FiltersUnionTypeAny:
		u.Any = best.Value.(any)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FiltersUnion", string(data))
}

func (u FiltersUnion) MarshalJSON() ([]byte, error) {
	if u.Filters != nil {
		return utils.MarshalJSON(u.Filters, "", true)
	}

	if u.CompoundFilter != nil {
		return utils.MarshalJSON(u.CompoundFilter, "", true)
	}

	if u.Any != nil {
		return utils.MarshalJSON(u.Any, "", true)
	}

	return nil, errors.New("could not marshal union type FiltersUnion: all fields are null")
}

type Ranker string

const (
	RankerAuto            Ranker = "auto"
	RankerDefault20241115 Ranker = "default-2024-11-15"
)

func (e Ranker) ToPointer() *Ranker {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Ranker) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "default-2024-11-15":
			return true
		}
	}
	return false
}

type RankingOptions struct {
	Ranker         *Ranker  `json:"ranker,omitzero"`
	ScoreThreshold *float64 `json:"score_threshold,omitzero"`
}

func (r RankingOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RankingOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RankingOptions) GetRanker() *Ranker {
	if r == nil {
		return nil
	}
	return r.Ranker
}

func (r *RankingOptions) GetScoreThreshold() *float64 {
	if r == nil {
		return nil
	}
	return r.ScoreThreshold
}

type TypeFileSearch string

const (
	TypeFileSearchFileSearch TypeFileSearch = "file_search"
)

func (e TypeFileSearch) ToPointer() *TypeFileSearch {
	return &e
}
func (e *TypeFileSearch) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "file_search":
		*e = TypeFileSearch(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeFileSearch: %v", v)
	}
}

// FileSearchServerTool - File search tool configuration
type FileSearchServerTool struct {
	Filters        optionalnullable.OptionalNullable[FiltersUnion] `json:"filters,omitzero"`
	MaxNumResults  *int64                                          `json:"max_num_results,omitzero"`
	RankingOptions *RankingOptions                                 `json:"ranking_options,omitzero"`
	Type           TypeFileSearch                                  `json:"type"`
	VectorStoreIds []string                                        `json:"vector_store_ids"`
}

func (f FileSearchServerTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileSearchServerTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileSearchServerTool) GetFilters() optionalnullable.OptionalNullable[FiltersUnion] {
	if f == nil {
		return nil
	}
	return f.Filters
}

func (f *FileSearchServerTool) GetMaxNumResults() *int64 {
	if f == nil {
		return nil
	}
	return f.MaxNumResults
}

func (f *FileSearchServerTool) GetRankingOptions() *RankingOptions {
	if f == nil {
		return nil
	}
	return f.RankingOptions
}

func (f *FileSearchServerTool) GetType() TypeFileSearch {
	if f == nil {
		return TypeFileSearch("")
	}
	return f.Type
}

func (f *FileSearchServerTool) GetVectorStoreIds() []string {
	if f == nil {
		return []string{}
	}
	return f.VectorStoreIds
}
