// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type FusionCallPanelDeltaEventType string

const (
	FusionCallPanelDeltaEventTypeResponseFusionCallPanelDelta FusionCallPanelDeltaEventType = "response.fusion_call.panel.delta"
)

func (e FusionCallPanelDeltaEventType) ToPointer() *FusionCallPanelDeltaEventType {
	return &e
}
func (e *FusionCallPanelDeltaEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.fusion_call.panel.delta":
		*e = FusionCallPanelDeltaEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FusionCallPanelDeltaEventType: %v", v)
	}
}

// FusionCallPanelDeltaEvent - Incremental content token from a fusion panel model.
type FusionCallPanelDeltaEvent struct {
	Delta          string                        `json:"delta"`
	ItemID         string                        `json:"item_id"`
	Model          string                        `json:"model"`
	OutputIndex    int64                         `json:"output_index"`
	SequenceNumber int64                         `json:"sequence_number"`
	Type           FusionCallPanelDeltaEventType `json:"type"`
}

func (f FusionCallPanelDeltaEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FusionCallPanelDeltaEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FusionCallPanelDeltaEvent) GetDelta() string {
	if f == nil {
		return ""
	}
	return f.Delta
}

func (f *FusionCallPanelDeltaEvent) GetItemID() string {
	if f == nil {
		return ""
	}
	return f.ItemID
}

func (f *FusionCallPanelDeltaEvent) GetModel() string {
	if f == nil {
		return ""
	}
	return f.Model
}

func (f *FusionCallPanelDeltaEvent) GetOutputIndex() int64 {
	if f == nil {
		return 0
	}
	return f.OutputIndex
}

func (f *FusionCallPanelDeltaEvent) GetSequenceNumber() int64 {
	if f == nil {
		return 0
	}
	return f.SequenceNumber
}

func (f *FusionCallPanelDeltaEvent) GetType() FusionCallPanelDeltaEventType {
	if f == nil {
		return FusionCallPanelDeltaEventType("")
	}
	return f.Type
}
