// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type FusionCallAnalysisCompletedEventType string

const (
	FusionCallAnalysisCompletedEventTypeResponseFusionCallAnalysisCompleted FusionCallAnalysisCompletedEventType = "response.fusion_call.analysis.completed"
)

func (e FusionCallAnalysisCompletedEventType) ToPointer() *FusionCallAnalysisCompletedEventType {
	return &e
}
func (e *FusionCallAnalysisCompletedEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.fusion_call.analysis.completed":
		*e = FusionCallAnalysisCompletedEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FusionCallAnalysisCompletedEventType: %v", v)
	}
}

// FusionCallAnalysisCompletedEvent - Emitted when the fusion judge completes with the structured analysis.
type FusionCallAnalysisCompletedEvent struct {
	// Structured analysis produced by the fusion judge model.
	Analysis       FusionAnalysisResult                 `json:"analysis"`
	ItemID         string                               `json:"item_id"`
	OutputIndex    int64                                `json:"output_index"`
	SequenceNumber int64                                `json:"sequence_number"`
	Type           FusionCallAnalysisCompletedEventType `json:"type"`
}

func (f FusionCallAnalysisCompletedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FusionCallAnalysisCompletedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FusionCallAnalysisCompletedEvent) GetAnalysis() FusionAnalysisResult {
	if f == nil {
		return FusionAnalysisResult{}
	}
	return f.Analysis
}

func (f *FusionCallAnalysisCompletedEvent) GetItemID() string {
	if f == nil {
		return ""
	}
	return f.ItemID
}

func (f *FusionCallAnalysisCompletedEvent) GetOutputIndex() int64 {
	if f == nil {
		return 0
	}
	return f.OutputIndex
}

func (f *FusionCallAnalysisCompletedEvent) GetSequenceNumber() int64 {
	if f == nil {
		return 0
	}
	return f.SequenceNumber
}

func (f *FusionCallAnalysisCompletedEvent) GetType() FusionCallAnalysisCompletedEventType {
	if f == nil {
		return FusionCallAnalysisCompletedEventType("")
	}
	return f.Type
}
