// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type FusionCallPanelAddedEventType string

const (
	FusionCallPanelAddedEventTypeResponseFusionCallPanelAdded FusionCallPanelAddedEventType = "response.fusion_call.panel.added"
)

func (e FusionCallPanelAddedEventType) ToPointer() *FusionCallPanelAddedEventType {
	return &e
}
func (e *FusionCallPanelAddedEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.fusion_call.panel.added":
		*e = FusionCallPanelAddedEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FusionCallPanelAddedEventType: %v", v)
	}
}

// FusionCallPanelAddedEvent - Emitted when a fusion analysis-panel model starts.
type FusionCallPanelAddedEvent struct {
	ItemID         string                        `json:"item_id"`
	Model          string                        `json:"model"`
	OutputIndex    int64                         `json:"output_index"`
	SequenceNumber int64                         `json:"sequence_number"`
	Type           FusionCallPanelAddedEventType `json:"type"`
}

func (f FusionCallPanelAddedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FusionCallPanelAddedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FusionCallPanelAddedEvent) GetItemID() string {
	if f == nil {
		return ""
	}
	return f.ItemID
}

func (f *FusionCallPanelAddedEvent) GetModel() string {
	if f == nil {
		return ""
	}
	return f.Model
}

func (f *FusionCallPanelAddedEvent) GetOutputIndex() int64 {
	if f == nil {
		return 0
	}
	return f.OutputIndex
}

func (f *FusionCallPanelAddedEvent) GetSequenceNumber() int64 {
	if f == nil {
		return 0
	}
	return f.SequenceNumber
}

func (f *FusionCallPanelAddedEvent) GetType() FusionCallPanelAddedEventType {
	if f == nil {
		return FusionCallPanelAddedEventType("")
	}
	return f.Type
}
