// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type FusionCallInProgressEventType string

const (
	FusionCallInProgressEventTypeResponseFusionCallInProgress FusionCallInProgressEventType = "response.fusion_call.in_progress"
)

func (e FusionCallInProgressEventType) ToPointer() *FusionCallInProgressEventType {
	return &e
}
func (e *FusionCallInProgressEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.fusion_call.in_progress":
		*e = FusionCallInProgressEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FusionCallInProgressEventType: %v", v)
	}
}

// FusionCallInProgressEvent - Emitted when an openrouter:fusion tool call begins executing.
type FusionCallInProgressEvent struct {
	ItemID         string                        `json:"item_id"`
	OutputIndex    int64                         `json:"output_index"`
	SequenceNumber int64                         `json:"sequence_number"`
	Type           FusionCallInProgressEventType `json:"type"`
}

func (f FusionCallInProgressEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FusionCallInProgressEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FusionCallInProgressEvent) GetItemID() string {
	if f == nil {
		return ""
	}
	return f.ItemID
}

func (f *FusionCallInProgressEvent) GetOutputIndex() int64 {
	if f == nil {
		return 0
	}
	return f.OutputIndex
}

func (f *FusionCallInProgressEvent) GetSequenceNumber() int64 {
	if f == nil {
		return 0
	}
	return f.SequenceNumber
}

func (f *FusionCallInProgressEvent) GetType() FusionCallInProgressEventType {
	if f == nil {
		return FusionCallInProgressEventType("")
	}
	return f.Type
}
