// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

// GatewayTimeoutResponseErrorData - Error data for GatewayTimeoutResponse
type GatewayTimeoutResponseErrorData struct {
	Code     int64                                             `json:"code"`
	Message  string                                            `json:"message"`
	Metadata optionalnullable.OptionalNullable[map[string]any] `json:"metadata,omitzero"`
}

func (g GatewayTimeoutResponseErrorData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GatewayTimeoutResponseErrorData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GatewayTimeoutResponseErrorData) GetCode() int64 {
	if g == nil {
		return 0
	}
	return g.Code
}

func (g *GatewayTimeoutResponseErrorData) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GatewayTimeoutResponseErrorData) GetMetadata() optionalnullable.OptionalNullable[map[string]any] {
	if g == nil {
		return nil
	}
	return g.Metadata
}
