// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GuardrailDataRegion - An OpenRouter data region: `global` (https://openrouter.ai), `europe` (https://eu.openrouter.ai), or `us` (https://us.openrouter.ai)
type GuardrailDataRegion string

const (
	GuardrailDataRegionGlobal GuardrailDataRegion = "global"
	GuardrailDataRegionEurope GuardrailDataRegion = "europe"
	GuardrailDataRegionUs     GuardrailDataRegion = "us"
)

func (e GuardrailDataRegion) ToPointer() *GuardrailDataRegion {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GuardrailDataRegion) IsExact() bool {
	if e != nil {
		switch *e {
		case "global", "europe", "us":
			return true
		}
	}
	return false
}
