// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type ImageGenerationProviderPreferencesIgnoreType string

const (
	ImageGenerationProviderPreferencesIgnoreTypeProviderName ImageGenerationProviderPreferencesIgnoreType = "ProviderName"
	ImageGenerationProviderPreferencesIgnoreTypeStr          ImageGenerationProviderPreferencesIgnoreType = "str"
)

type ImageGenerationProviderPreferencesIgnore struct {
	ProviderName *ProviderName `queryParam:"inline" union:"member"`
	Str          *string       `queryParam:"inline" union:"member"`

	Type ImageGenerationProviderPreferencesIgnoreType
}

func CreateImageGenerationProviderPreferencesIgnoreProviderName(providerName ProviderName) ImageGenerationProviderPreferencesIgnore {
	typ := ImageGenerationProviderPreferencesIgnoreTypeProviderName

	return ImageGenerationProviderPreferencesIgnore{
		ProviderName: &providerName,
		Type:         typ,
	}
}

func CreateImageGenerationProviderPreferencesIgnoreStr(str string) ImageGenerationProviderPreferencesIgnore {
	typ := ImageGenerationProviderPreferencesIgnoreTypeStr

	return ImageGenerationProviderPreferencesIgnore{
		Str:  &str,
		Type: typ,
	}
}

func (u *ImageGenerationProviderPreferencesIgnore) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var providerName ProviderName = ProviderName("")
	if err := utils.UnmarshalJSON(data, &providerName, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ImageGenerationProviderPreferencesIgnoreTypeProviderName,
			Value: &providerName,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ImageGenerationProviderPreferencesIgnoreTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesIgnore", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesIgnore", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ImageGenerationProviderPreferencesIgnoreType)
	switch best.Type {
	case ImageGenerationProviderPreferencesIgnoreTypeProviderName:
		u.ProviderName = best.Value.(*ProviderName)
		return nil
	case ImageGenerationProviderPreferencesIgnoreTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesIgnore", string(data))
}

func (u ImageGenerationProviderPreferencesIgnore) MarshalJSON() ([]byte, error) {
	if u.ProviderName != nil {
		return utils.MarshalJSON(u.ProviderName, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type ImageGenerationProviderPreferencesIgnore: all fields are null")
}

type ImageGenerationProviderPreferencesOnlyType string

const (
	ImageGenerationProviderPreferencesOnlyTypeProviderName ImageGenerationProviderPreferencesOnlyType = "ProviderName"
	ImageGenerationProviderPreferencesOnlyTypeStr          ImageGenerationProviderPreferencesOnlyType = "str"
)

type ImageGenerationProviderPreferencesOnly struct {
	ProviderName *ProviderName `queryParam:"inline" union:"member"`
	Str          *string       `queryParam:"inline" union:"member"`

	Type ImageGenerationProviderPreferencesOnlyType
}

func CreateImageGenerationProviderPreferencesOnlyProviderName(providerName ProviderName) ImageGenerationProviderPreferencesOnly {
	typ := ImageGenerationProviderPreferencesOnlyTypeProviderName

	return ImageGenerationProviderPreferencesOnly{
		ProviderName: &providerName,
		Type:         typ,
	}
}

func CreateImageGenerationProviderPreferencesOnlyStr(str string) ImageGenerationProviderPreferencesOnly {
	typ := ImageGenerationProviderPreferencesOnlyTypeStr

	return ImageGenerationProviderPreferencesOnly{
		Str:  &str,
		Type: typ,
	}
}

func (u *ImageGenerationProviderPreferencesOnly) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var providerName ProviderName = ProviderName("")
	if err := utils.UnmarshalJSON(data, &providerName, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ImageGenerationProviderPreferencesOnlyTypeProviderName,
			Value: &providerName,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ImageGenerationProviderPreferencesOnlyTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesOnly", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesOnly", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ImageGenerationProviderPreferencesOnlyType)
	switch best.Type {
	case ImageGenerationProviderPreferencesOnlyTypeProviderName:
		u.ProviderName = best.Value.(*ProviderName)
		return nil
	case ImageGenerationProviderPreferencesOnlyTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesOnly", string(data))
}

func (u ImageGenerationProviderPreferencesOnly) MarshalJSON() ([]byte, error) {
	if u.ProviderName != nil {
		return utils.MarshalJSON(u.ProviderName, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type ImageGenerationProviderPreferencesOnly: all fields are null")
}

// ImageGenerationProviderPreferencesOptions - Provider-specific options keyed by provider slug. Only options for the matched provider are forwarded; the rest are ignored. Unrecognized keys are silently dropped.
type ImageGenerationProviderPreferencesOptions struct {
	Oneai               map[string]any `json:"01ai,omitzero"`
	Ai21                map[string]any `json:"ai21,omitzero"`
	AionLabs            map[string]any `json:"aion-labs,omitzero"`
	Akashml             map[string]any `json:"akashml,omitzero"`
	Alibaba             map[string]any `json:"alibaba,omitzero"`
	AmazonBedrock       map[string]any `json:"amazon-bedrock,omitzero"`
	AmazonNova          map[string]any `json:"amazon-nova,omitzero"`
	Ambient             map[string]any `json:"ambient,omitzero"`
	Anthropic           map[string]any `json:"anthropic,omitzero"`
	Anyscale            map[string]any `json:"anyscale,omitzero"`
	ArceeAi             map[string]any `json:"arcee-ai,omitzero"`
	AtlasCloud          map[string]any `json:"atlas-cloud,omitzero"`
	Atoma               map[string]any `json:"atoma,omitzero"`
	Avian               map[string]any `json:"avian,omitzero"`
	Azure               map[string]any `json:"azure,omitzero"`
	Baidu               map[string]any `json:"baidu,omitzero"`
	Baseten             map[string]any `json:"baseten,omitzero"`
	BlackForestLabs     map[string]any `json:"black-forest-labs,omitzero"`
	Byteplus            map[string]any `json:"byteplus,omitzero"`
	Centml              map[string]any `json:"centml,omitzero"`
	Cerebras            map[string]any `json:"cerebras,omitzero"`
	Chutes              map[string]any `json:"chutes,omitzero"`
	Cirrascale          map[string]any `json:"cirrascale,omitzero"`
	Clarifai            map[string]any `json:"clarifai,omitzero"`
	Cloudflare          map[string]any `json:"cloudflare,omitzero"`
	Cohere              map[string]any `json:"cohere,omitzero"`
	Crofai              map[string]any `json:"crofai,omitzero"`
	Crucible            map[string]any `json:"crucible,omitzero"`
	Crusoe              map[string]any `json:"crusoe,omitzero"`
	Darkbloom           map[string]any `json:"darkbloom,omitzero"`
	Decart              map[string]any `json:"decart,omitzero"`
	Deepgram            map[string]any `json:"deepgram,omitzero"`
	Deepinfra           map[string]any `json:"deepinfra,omitzero"`
	Deepseek            map[string]any `json:"deepseek,omitzero"`
	Dekallm             map[string]any `json:"dekallm,omitzero"`
	Digitalocean        map[string]any `json:"digitalocean,omitzero"`
	Enfer               map[string]any `json:"enfer,omitzero"`
	FakeProvider        map[string]any `json:"fake-provider,omitzero"`
	Featherless         map[string]any `json:"featherless,omitzero"`
	Fireworks           map[string]any `json:"fireworks,omitzero"`
	FishAudio           map[string]any `json:"fish-audio,omitzero"`
	Friendli            map[string]any `json:"friendli,omitzero"`
	Gmicloud            map[string]any `json:"gmicloud,omitzero"`
	GoogleAiStudio      map[string]any `json:"google-ai-studio,omitzero"`
	GoogleVertex        map[string]any `json:"google-vertex,omitzero"`
	Gopomelo            map[string]any `json:"gopomelo,omitzero"`
	Groq                map[string]any `json:"groq,omitzero"`
	Heygen              map[string]any `json:"heygen,omitzero"`
	Huggingface         map[string]any `json:"huggingface,omitzero"`
	Hyperbolic          map[string]any `json:"hyperbolic,omitzero"`
	HyperbolicQuantized map[string]any `json:"hyperbolic-quantized,omitzero"`
	Inception           map[string]any `json:"inception,omitzero"`
	Inceptron           map[string]any `json:"inceptron,omitzero"`
	InferactVllm        map[string]any `json:"inferact-vllm,omitzero"`
	InferenceNet        map[string]any `json:"inference-net,omitzero"`
	Infermatic          map[string]any `json:"infermatic,omitzero"`
	Inflection          map[string]any `json:"inflection,omitzero"`
	Inocloud            map[string]any `json:"inocloud,omitzero"`
	IoNet               map[string]any `json:"io-net,omitzero"`
	Ionstream           map[string]any `json:"ionstream,omitzero"`
	Klusterai           map[string]any `json:"klusterai,omitzero"`
	Krea                map[string]any `json:"krea,omitzero"`
	Lambda              map[string]any `json:"lambda,omitzero"`
	Lepton              map[string]any `json:"lepton,omitzero"`
	Liquid              map[string]any `json:"liquid,omitzero"`
	Lynn                map[string]any `json:"lynn,omitzero"`
	LynnPrivate         map[string]any `json:"lynn-private,omitzero"`
	Mancer              map[string]any `json:"mancer,omitzero"`
	MancerOld           map[string]any `json:"mancer-old,omitzero"`
	Mara                map[string]any `json:"mara,omitzero"`
	Meta                map[string]any `json:"meta,omitzero"`
	Minimax             map[string]any `json:"minimax,omitzero"`
	Mistral             map[string]any `json:"mistral,omitzero"`
	Modal               map[string]any `json:"modal,omitzero"`
	Modelrun            map[string]any `json:"modelrun,omitzero"`
	Modular             map[string]any `json:"modular,omitzero"`
	Moonshotai          map[string]any `json:"moonshotai,omitzero"`
	Morph               map[string]any `json:"morph,omitzero"`
	Ncompass            map[string]any `json:"ncompass,omitzero"`
	Nebius              map[string]any `json:"nebius,omitzero"`
	NexAgi              map[string]any `json:"nex-agi,omitzero"`
	Nextbit             map[string]any `json:"nextbit,omitzero"`
	Nineteen            map[string]any `json:"nineteen,omitzero"`
	Novita              map[string]any `json:"novita,omitzero"`
	Nvidia              map[string]any `json:"nvidia,omitzero"`
	Octoai              map[string]any `json:"octoai,omitzero"`
	OpenInference       map[string]any `json:"open-inference,omitzero"`
	Openai              map[string]any `json:"openai,omitzero"`
	Parasail            map[string]any `json:"parasail,omitzero"`
	Perceptron          map[string]any `json:"perceptron,omitzero"`
	Perplexity          map[string]any `json:"perplexity,omitzero"`
	Phala               map[string]any `json:"phala,omitzero"`
	Poolside            map[string]any `json:"poolside,omitzero"`
	Quiver              map[string]any `json:"quiver,omitzero"`
	Recraft             map[string]any `json:"recraft,omitzero"`
	Recursal            map[string]any `json:"recursal,omitzero"`
	Reflection          map[string]any `json:"reflection,omitzero"`
	Reka                map[string]any `json:"reka,omitzero"`
	Relace              map[string]any `json:"relace,omitzero"`
	Replicate           map[string]any `json:"replicate,omitzero"`
	Runway              map[string]any `json:"runway,omitzero"`
	SailResearch        map[string]any `json:"sail-research,omitzero"`
	Sakana              map[string]any `json:"sakana,omitzero"`
	Sambanova           map[string]any `json:"sambanova,omitzero"`
	SambanovaCloaked    map[string]any `json:"sambanova-cloaked,omitzero"`
	Seed                map[string]any `json:"seed,omitzero"`
	SfCompute           map[string]any `json:"sf-compute,omitzero"`
	Siliconflow         map[string]any `json:"siliconflow,omitzero"`
	Sourceful           map[string]any `json:"sourceful,omitzero"`
	Stealth             map[string]any `json:"stealth,omitzero"`
	Stepfun             map[string]any `json:"stepfun,omitzero"`
	Streamlake          map[string]any `json:"streamlake,omitzero"`
	Switchpoint         map[string]any `json:"switchpoint,omitzero"`
	Targon              map[string]any `json:"targon,omitzero"`
	Tencent             map[string]any `json:"tencent,omitzero"`
	Tenstorrent         map[string]any `json:"tenstorrent,omitzero"`
	Together            map[string]any `json:"together,omitzero"`
	TogetherLite        map[string]any `json:"together-lite,omitzero"`
	Ubicloud            map[string]any `json:"ubicloud,omitzero"`
	Upstage             map[string]any `json:"upstage,omitzero"`
	Venice              map[string]any `json:"venice,omitzero"`
	Wafer               map[string]any `json:"wafer,omitzero"`
	Wandb               map[string]any `json:"wandb,omitzero"`
	Xai                 map[string]any `json:"xai,omitzero"`
	Xiaomi              map[string]any `json:"xiaomi,omitzero"`
	ZAi                 map[string]any `json:"z-ai,omitzero"`
}

func (i ImageGenerationProviderPreferencesOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageGenerationProviderPreferencesOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageGenerationProviderPreferencesOptions) GetOneai() map[string]any {
	if i == nil {
		return nil
	}
	return i.Oneai
}

func (i *ImageGenerationProviderPreferencesOptions) GetAi21() map[string]any {
	if i == nil {
		return nil
	}
	return i.Ai21
}

func (i *ImageGenerationProviderPreferencesOptions) GetAionLabs() map[string]any {
	if i == nil {
		return nil
	}
	return i.AionLabs
}

func (i *ImageGenerationProviderPreferencesOptions) GetAkashml() map[string]any {
	if i == nil {
		return nil
	}
	return i.Akashml
}

func (i *ImageGenerationProviderPreferencesOptions) GetAlibaba() map[string]any {
	if i == nil {
		return nil
	}
	return i.Alibaba
}

func (i *ImageGenerationProviderPreferencesOptions) GetAmazonBedrock() map[string]any {
	if i == nil {
		return nil
	}
	return i.AmazonBedrock
}

func (i *ImageGenerationProviderPreferencesOptions) GetAmazonNova() map[string]any {
	if i == nil {
		return nil
	}
	return i.AmazonNova
}

func (i *ImageGenerationProviderPreferencesOptions) GetAmbient() map[string]any {
	if i == nil {
		return nil
	}
	return i.Ambient
}

func (i *ImageGenerationProviderPreferencesOptions) GetAnthropic() map[string]any {
	if i == nil {
		return nil
	}
	return i.Anthropic
}

func (i *ImageGenerationProviderPreferencesOptions) GetAnyscale() map[string]any {
	if i == nil {
		return nil
	}
	return i.Anyscale
}

func (i *ImageGenerationProviderPreferencesOptions) GetArceeAi() map[string]any {
	if i == nil {
		return nil
	}
	return i.ArceeAi
}

func (i *ImageGenerationProviderPreferencesOptions) GetAtlasCloud() map[string]any {
	if i == nil {
		return nil
	}
	return i.AtlasCloud
}

func (i *ImageGenerationProviderPreferencesOptions) GetAtoma() map[string]any {
	if i == nil {
		return nil
	}
	return i.Atoma
}

func (i *ImageGenerationProviderPreferencesOptions) GetAvian() map[string]any {
	if i == nil {
		return nil
	}
	return i.Avian
}

func (i *ImageGenerationProviderPreferencesOptions) GetAzure() map[string]any {
	if i == nil {
		return nil
	}
	return i.Azure
}

func (i *ImageGenerationProviderPreferencesOptions) GetBaidu() map[string]any {
	if i == nil {
		return nil
	}
	return i.Baidu
}

func (i *ImageGenerationProviderPreferencesOptions) GetBaseten() map[string]any {
	if i == nil {
		return nil
	}
	return i.Baseten
}

func (i *ImageGenerationProviderPreferencesOptions) GetBlackForestLabs() map[string]any {
	if i == nil {
		return nil
	}
	return i.BlackForestLabs
}

func (i *ImageGenerationProviderPreferencesOptions) GetByteplus() map[string]any {
	if i == nil {
		return nil
	}
	return i.Byteplus
}

func (i *ImageGenerationProviderPreferencesOptions) GetCentml() map[string]any {
	if i == nil {
		return nil
	}
	return i.Centml
}

func (i *ImageGenerationProviderPreferencesOptions) GetCerebras() map[string]any {
	if i == nil {
		return nil
	}
	return i.Cerebras
}

func (i *ImageGenerationProviderPreferencesOptions) GetChutes() map[string]any {
	if i == nil {
		return nil
	}
	return i.Chutes
}

func (i *ImageGenerationProviderPreferencesOptions) GetCirrascale() map[string]any {
	if i == nil {
		return nil
	}
	return i.Cirrascale
}

func (i *ImageGenerationProviderPreferencesOptions) GetClarifai() map[string]any {
	if i == nil {
		return nil
	}
	return i.Clarifai
}

func (i *ImageGenerationProviderPreferencesOptions) GetCloudflare() map[string]any {
	if i == nil {
		return nil
	}
	return i.Cloudflare
}

func (i *ImageGenerationProviderPreferencesOptions) GetCohere() map[string]any {
	if i == nil {
		return nil
	}
	return i.Cohere
}

func (i *ImageGenerationProviderPreferencesOptions) GetCrofai() map[string]any {
	if i == nil {
		return nil
	}
	return i.Crofai
}

func (i *ImageGenerationProviderPreferencesOptions) GetCrucible() map[string]any {
	if i == nil {
		return nil
	}
	return i.Crucible
}

func (i *ImageGenerationProviderPreferencesOptions) GetCrusoe() map[string]any {
	if i == nil {
		return nil
	}
	return i.Crusoe
}

func (i *ImageGenerationProviderPreferencesOptions) GetDarkbloom() map[string]any {
	if i == nil {
		return nil
	}
	return i.Darkbloom
}

func (i *ImageGenerationProviderPreferencesOptions) GetDecart() map[string]any {
	if i == nil {
		return nil
	}
	return i.Decart
}

func (i *ImageGenerationProviderPreferencesOptions) GetDeepgram() map[string]any {
	if i == nil {
		return nil
	}
	return i.Deepgram
}

func (i *ImageGenerationProviderPreferencesOptions) GetDeepinfra() map[string]any {
	if i == nil {
		return nil
	}
	return i.Deepinfra
}

func (i *ImageGenerationProviderPreferencesOptions) GetDeepseek() map[string]any {
	if i == nil {
		return nil
	}
	return i.Deepseek
}

func (i *ImageGenerationProviderPreferencesOptions) GetDekallm() map[string]any {
	if i == nil {
		return nil
	}
	return i.Dekallm
}

func (i *ImageGenerationProviderPreferencesOptions) GetDigitalocean() map[string]any {
	if i == nil {
		return nil
	}
	return i.Digitalocean
}

func (i *ImageGenerationProviderPreferencesOptions) GetEnfer() map[string]any {
	if i == nil {
		return nil
	}
	return i.Enfer
}

func (i *ImageGenerationProviderPreferencesOptions) GetFakeProvider() map[string]any {
	if i == nil {
		return nil
	}
	return i.FakeProvider
}

func (i *ImageGenerationProviderPreferencesOptions) GetFeatherless() map[string]any {
	if i == nil {
		return nil
	}
	return i.Featherless
}

func (i *ImageGenerationProviderPreferencesOptions) GetFireworks() map[string]any {
	if i == nil {
		return nil
	}
	return i.Fireworks
}

func (i *ImageGenerationProviderPreferencesOptions) GetFishAudio() map[string]any {
	if i == nil {
		return nil
	}
	return i.FishAudio
}

func (i *ImageGenerationProviderPreferencesOptions) GetFriendli() map[string]any {
	if i == nil {
		return nil
	}
	return i.Friendli
}

func (i *ImageGenerationProviderPreferencesOptions) GetGmicloud() map[string]any {
	if i == nil {
		return nil
	}
	return i.Gmicloud
}

func (i *ImageGenerationProviderPreferencesOptions) GetGoogleAiStudio() map[string]any {
	if i == nil {
		return nil
	}
	return i.GoogleAiStudio
}

func (i *ImageGenerationProviderPreferencesOptions) GetGoogleVertex() map[string]any {
	if i == nil {
		return nil
	}
	return i.GoogleVertex
}

func (i *ImageGenerationProviderPreferencesOptions) GetGopomelo() map[string]any {
	if i == nil {
		return nil
	}
	return i.Gopomelo
}

func (i *ImageGenerationProviderPreferencesOptions) GetGroq() map[string]any {
	if i == nil {
		return nil
	}
	return i.Groq
}

func (i *ImageGenerationProviderPreferencesOptions) GetHeygen() map[string]any {
	if i == nil {
		return nil
	}
	return i.Heygen
}

func (i *ImageGenerationProviderPreferencesOptions) GetHuggingface() map[string]any {
	if i == nil {
		return nil
	}
	return i.Huggingface
}

func (i *ImageGenerationProviderPreferencesOptions) GetHyperbolic() map[string]any {
	if i == nil {
		return nil
	}
	return i.Hyperbolic
}

func (i *ImageGenerationProviderPreferencesOptions) GetHyperbolicQuantized() map[string]any {
	if i == nil {
		return nil
	}
	return i.HyperbolicQuantized
}

func (i *ImageGenerationProviderPreferencesOptions) GetInception() map[string]any {
	if i == nil {
		return nil
	}
	return i.Inception
}

func (i *ImageGenerationProviderPreferencesOptions) GetInceptron() map[string]any {
	if i == nil {
		return nil
	}
	return i.Inceptron
}

func (i *ImageGenerationProviderPreferencesOptions) GetInferactVllm() map[string]any {
	if i == nil {
		return nil
	}
	return i.InferactVllm
}

func (i *ImageGenerationProviderPreferencesOptions) GetInferenceNet() map[string]any {
	if i == nil {
		return nil
	}
	return i.InferenceNet
}

func (i *ImageGenerationProviderPreferencesOptions) GetInfermatic() map[string]any {
	if i == nil {
		return nil
	}
	return i.Infermatic
}

func (i *ImageGenerationProviderPreferencesOptions) GetInflection() map[string]any {
	if i == nil {
		return nil
	}
	return i.Inflection
}

func (i *ImageGenerationProviderPreferencesOptions) GetInocloud() map[string]any {
	if i == nil {
		return nil
	}
	return i.Inocloud
}

func (i *ImageGenerationProviderPreferencesOptions) GetIoNet() map[string]any {
	if i == nil {
		return nil
	}
	return i.IoNet
}

func (i *ImageGenerationProviderPreferencesOptions) GetIonstream() map[string]any {
	if i == nil {
		return nil
	}
	return i.Ionstream
}

func (i *ImageGenerationProviderPreferencesOptions) GetKlusterai() map[string]any {
	if i == nil {
		return nil
	}
	return i.Klusterai
}

func (i *ImageGenerationProviderPreferencesOptions) GetKrea() map[string]any {
	if i == nil {
		return nil
	}
	return i.Krea
}

func (i *ImageGenerationProviderPreferencesOptions) GetLambda() map[string]any {
	if i == nil {
		return nil
	}
	return i.Lambda
}

func (i *ImageGenerationProviderPreferencesOptions) GetLepton() map[string]any {
	if i == nil {
		return nil
	}
	return i.Lepton
}

func (i *ImageGenerationProviderPreferencesOptions) GetLiquid() map[string]any {
	if i == nil {
		return nil
	}
	return i.Liquid
}

func (i *ImageGenerationProviderPreferencesOptions) GetLynn() map[string]any {
	if i == nil {
		return nil
	}
	return i.Lynn
}

func (i *ImageGenerationProviderPreferencesOptions) GetLynnPrivate() map[string]any {
	if i == nil {
		return nil
	}
	return i.LynnPrivate
}

func (i *ImageGenerationProviderPreferencesOptions) GetMancer() map[string]any {
	if i == nil {
		return nil
	}
	return i.Mancer
}

func (i *ImageGenerationProviderPreferencesOptions) GetMancerOld() map[string]any {
	if i == nil {
		return nil
	}
	return i.MancerOld
}

func (i *ImageGenerationProviderPreferencesOptions) GetMara() map[string]any {
	if i == nil {
		return nil
	}
	return i.Mara
}

func (i *ImageGenerationProviderPreferencesOptions) GetMeta() map[string]any {
	if i == nil {
		return nil
	}
	return i.Meta
}

func (i *ImageGenerationProviderPreferencesOptions) GetMinimax() map[string]any {
	if i == nil {
		return nil
	}
	return i.Minimax
}

func (i *ImageGenerationProviderPreferencesOptions) GetMistral() map[string]any {
	if i == nil {
		return nil
	}
	return i.Mistral
}

func (i *ImageGenerationProviderPreferencesOptions) GetModal() map[string]any {
	if i == nil {
		return nil
	}
	return i.Modal
}

func (i *ImageGenerationProviderPreferencesOptions) GetModelrun() map[string]any {
	if i == nil {
		return nil
	}
	return i.Modelrun
}

func (i *ImageGenerationProviderPreferencesOptions) GetModular() map[string]any {
	if i == nil {
		return nil
	}
	return i.Modular
}

func (i *ImageGenerationProviderPreferencesOptions) GetMoonshotai() map[string]any {
	if i == nil {
		return nil
	}
	return i.Moonshotai
}

func (i *ImageGenerationProviderPreferencesOptions) GetMorph() map[string]any {
	if i == nil {
		return nil
	}
	return i.Morph
}

func (i *ImageGenerationProviderPreferencesOptions) GetNcompass() map[string]any {
	if i == nil {
		return nil
	}
	return i.Ncompass
}

func (i *ImageGenerationProviderPreferencesOptions) GetNebius() map[string]any {
	if i == nil {
		return nil
	}
	return i.Nebius
}

func (i *ImageGenerationProviderPreferencesOptions) GetNexAgi() map[string]any {
	if i == nil {
		return nil
	}
	return i.NexAgi
}

func (i *ImageGenerationProviderPreferencesOptions) GetNextbit() map[string]any {
	if i == nil {
		return nil
	}
	return i.Nextbit
}

func (i *ImageGenerationProviderPreferencesOptions) GetNineteen() map[string]any {
	if i == nil {
		return nil
	}
	return i.Nineteen
}

func (i *ImageGenerationProviderPreferencesOptions) GetNovita() map[string]any {
	if i == nil {
		return nil
	}
	return i.Novita
}

func (i *ImageGenerationProviderPreferencesOptions) GetNvidia() map[string]any {
	if i == nil {
		return nil
	}
	return i.Nvidia
}

func (i *ImageGenerationProviderPreferencesOptions) GetOctoai() map[string]any {
	if i == nil {
		return nil
	}
	return i.Octoai
}

func (i *ImageGenerationProviderPreferencesOptions) GetOpenInference() map[string]any {
	if i == nil {
		return nil
	}
	return i.OpenInference
}

func (i *ImageGenerationProviderPreferencesOptions) GetOpenai() map[string]any {
	if i == nil {
		return nil
	}
	return i.Openai
}

func (i *ImageGenerationProviderPreferencesOptions) GetParasail() map[string]any {
	if i == nil {
		return nil
	}
	return i.Parasail
}

func (i *ImageGenerationProviderPreferencesOptions) GetPerceptron() map[string]any {
	if i == nil {
		return nil
	}
	return i.Perceptron
}

func (i *ImageGenerationProviderPreferencesOptions) GetPerplexity() map[string]any {
	if i == nil {
		return nil
	}
	return i.Perplexity
}

func (i *ImageGenerationProviderPreferencesOptions) GetPhala() map[string]any {
	if i == nil {
		return nil
	}
	return i.Phala
}

func (i *ImageGenerationProviderPreferencesOptions) GetPoolside() map[string]any {
	if i == nil {
		return nil
	}
	return i.Poolside
}

func (i *ImageGenerationProviderPreferencesOptions) GetQuiver() map[string]any {
	if i == nil {
		return nil
	}
	return i.Quiver
}

func (i *ImageGenerationProviderPreferencesOptions) GetRecraft() map[string]any {
	if i == nil {
		return nil
	}
	return i.Recraft
}

func (i *ImageGenerationProviderPreferencesOptions) GetRecursal() map[string]any {
	if i == nil {
		return nil
	}
	return i.Recursal
}

func (i *ImageGenerationProviderPreferencesOptions) GetReflection() map[string]any {
	if i == nil {
		return nil
	}
	return i.Reflection
}

func (i *ImageGenerationProviderPreferencesOptions) GetReka() map[string]any {
	if i == nil {
		return nil
	}
	return i.Reka
}

func (i *ImageGenerationProviderPreferencesOptions) GetRelace() map[string]any {
	if i == nil {
		return nil
	}
	return i.Relace
}

func (i *ImageGenerationProviderPreferencesOptions) GetReplicate() map[string]any {
	if i == nil {
		return nil
	}
	return i.Replicate
}

func (i *ImageGenerationProviderPreferencesOptions) GetRunway() map[string]any {
	if i == nil {
		return nil
	}
	return i.Runway
}

func (i *ImageGenerationProviderPreferencesOptions) GetSailResearch() map[string]any {
	if i == nil {
		return nil
	}
	return i.SailResearch
}

func (i *ImageGenerationProviderPreferencesOptions) GetSakana() map[string]any {
	if i == nil {
		return nil
	}
	return i.Sakana
}

func (i *ImageGenerationProviderPreferencesOptions) GetSambanova() map[string]any {
	if i == nil {
		return nil
	}
	return i.Sambanova
}

func (i *ImageGenerationProviderPreferencesOptions) GetSambanovaCloaked() map[string]any {
	if i == nil {
		return nil
	}
	return i.SambanovaCloaked
}

func (i *ImageGenerationProviderPreferencesOptions) GetSeed() map[string]any {
	if i == nil {
		return nil
	}
	return i.Seed
}

func (i *ImageGenerationProviderPreferencesOptions) GetSfCompute() map[string]any {
	if i == nil {
		return nil
	}
	return i.SfCompute
}

func (i *ImageGenerationProviderPreferencesOptions) GetSiliconflow() map[string]any {
	if i == nil {
		return nil
	}
	return i.Siliconflow
}

func (i *ImageGenerationProviderPreferencesOptions) GetSourceful() map[string]any {
	if i == nil {
		return nil
	}
	return i.Sourceful
}

func (i *ImageGenerationProviderPreferencesOptions) GetStealth() map[string]any {
	if i == nil {
		return nil
	}
	return i.Stealth
}

func (i *ImageGenerationProviderPreferencesOptions) GetStepfun() map[string]any {
	if i == nil {
		return nil
	}
	return i.Stepfun
}

func (i *ImageGenerationProviderPreferencesOptions) GetStreamlake() map[string]any {
	if i == nil {
		return nil
	}
	return i.Streamlake
}

func (i *ImageGenerationProviderPreferencesOptions) GetSwitchpoint() map[string]any {
	if i == nil {
		return nil
	}
	return i.Switchpoint
}

func (i *ImageGenerationProviderPreferencesOptions) GetTargon() map[string]any {
	if i == nil {
		return nil
	}
	return i.Targon
}

func (i *ImageGenerationProviderPreferencesOptions) GetTencent() map[string]any {
	if i == nil {
		return nil
	}
	return i.Tencent
}

func (i *ImageGenerationProviderPreferencesOptions) GetTenstorrent() map[string]any {
	if i == nil {
		return nil
	}
	return i.Tenstorrent
}

func (i *ImageGenerationProviderPreferencesOptions) GetTogether() map[string]any {
	if i == nil {
		return nil
	}
	return i.Together
}

func (i *ImageGenerationProviderPreferencesOptions) GetTogetherLite() map[string]any {
	if i == nil {
		return nil
	}
	return i.TogetherLite
}

func (i *ImageGenerationProviderPreferencesOptions) GetUbicloud() map[string]any {
	if i == nil {
		return nil
	}
	return i.Ubicloud
}

func (i *ImageGenerationProviderPreferencesOptions) GetUpstage() map[string]any {
	if i == nil {
		return nil
	}
	return i.Upstage
}

func (i *ImageGenerationProviderPreferencesOptions) GetVenice() map[string]any {
	if i == nil {
		return nil
	}
	return i.Venice
}

func (i *ImageGenerationProviderPreferencesOptions) GetWafer() map[string]any {
	if i == nil {
		return nil
	}
	return i.Wafer
}

func (i *ImageGenerationProviderPreferencesOptions) GetWandb() map[string]any {
	if i == nil {
		return nil
	}
	return i.Wandb
}

func (i *ImageGenerationProviderPreferencesOptions) GetXai() map[string]any {
	if i == nil {
		return nil
	}
	return i.Xai
}

func (i *ImageGenerationProviderPreferencesOptions) GetXiaomi() map[string]any {
	if i == nil {
		return nil
	}
	return i.Xiaomi
}

func (i *ImageGenerationProviderPreferencesOptions) GetZAi() map[string]any {
	if i == nil {
		return nil
	}
	return i.ZAi
}

type ImageGenerationProviderPreferencesOrderType string

const (
	ImageGenerationProviderPreferencesOrderTypeProviderName ImageGenerationProviderPreferencesOrderType = "ProviderName"
	ImageGenerationProviderPreferencesOrderTypeStr          ImageGenerationProviderPreferencesOrderType = "str"
)

type ImageGenerationProviderPreferencesOrder struct {
	ProviderName *ProviderName `queryParam:"inline" union:"member"`
	Str          *string       `queryParam:"inline" union:"member"`

	Type ImageGenerationProviderPreferencesOrderType
}

func CreateImageGenerationProviderPreferencesOrderProviderName(providerName ProviderName) ImageGenerationProviderPreferencesOrder {
	typ := ImageGenerationProviderPreferencesOrderTypeProviderName

	return ImageGenerationProviderPreferencesOrder{
		ProviderName: &providerName,
		Type:         typ,
	}
}

func CreateImageGenerationProviderPreferencesOrderStr(str string) ImageGenerationProviderPreferencesOrder {
	typ := ImageGenerationProviderPreferencesOrderTypeStr

	return ImageGenerationProviderPreferencesOrder{
		Str:  &str,
		Type: typ,
	}
}

func (u *ImageGenerationProviderPreferencesOrder) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var providerName ProviderName = ProviderName("")
	if err := utils.UnmarshalJSON(data, &providerName, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ImageGenerationProviderPreferencesOrderTypeProviderName,
			Value: &providerName,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ImageGenerationProviderPreferencesOrderTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesOrder", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesOrder", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ImageGenerationProviderPreferencesOrderType)
	switch best.Type {
	case ImageGenerationProviderPreferencesOrderTypeProviderName:
		u.ProviderName = best.Value.(*ProviderName)
		return nil
	case ImageGenerationProviderPreferencesOrderTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesOrder", string(data))
}

func (u ImageGenerationProviderPreferencesOrder) MarshalJSON() ([]byte, error) {
	if u.ProviderName != nil {
		return utils.MarshalJSON(u.ProviderName, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type ImageGenerationProviderPreferencesOrder: all fields are null")
}

type ImageGenerationProviderPreferencesSortType string

const (
	ImageGenerationProviderPreferencesSortTypeProviderSort       ImageGenerationProviderPreferencesSortType = "ProviderSort"
	ImageGenerationProviderPreferencesSortTypeProviderSortConfig ImageGenerationProviderPreferencesSortType = "ProviderSortConfig"
)

// ImageGenerationProviderPreferencesSort - The sorting strategy to use for this request, if "order" is not specified. When set, no load balancing is performed.
type ImageGenerationProviderPreferencesSort struct {
	ProviderSort       *ProviderSort       `queryParam:"inline" union:"member"`
	ProviderSortConfig *ProviderSortConfig `queryParam:"inline" union:"member"`

	Type ImageGenerationProviderPreferencesSortType
}

func CreateImageGenerationProviderPreferencesSortProviderSort(providerSort ProviderSort) ImageGenerationProviderPreferencesSort {
	typ := ImageGenerationProviderPreferencesSortTypeProviderSort

	return ImageGenerationProviderPreferencesSort{
		ProviderSort: &providerSort,
		Type:         typ,
	}
}

func CreateImageGenerationProviderPreferencesSortProviderSortConfig(providerSortConfig ProviderSortConfig) ImageGenerationProviderPreferencesSort {
	typ := ImageGenerationProviderPreferencesSortTypeProviderSortConfig

	return ImageGenerationProviderPreferencesSort{
		ProviderSortConfig: &providerSortConfig,
		Type:               typ,
	}
}

func (u *ImageGenerationProviderPreferencesSort) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var providerSort ProviderSort = ProviderSort("")
	if err := utils.UnmarshalJSON(data, &providerSort, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ImageGenerationProviderPreferencesSortTypeProviderSort,
			Value: &providerSort,
		})
	}

	var providerSortConfig ProviderSortConfig = ProviderSortConfig{}
	if err := utils.UnmarshalJSON(data, &providerSortConfig, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ImageGenerationProviderPreferencesSortTypeProviderSortConfig,
			Value: &providerSortConfig,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesSort", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesSort", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ImageGenerationProviderPreferencesSortType)
	switch best.Type {
	case ImageGenerationProviderPreferencesSortTypeProviderSort:
		u.ProviderSort = best.Value.(*ProviderSort)
		return nil
	case ImageGenerationProviderPreferencesSortTypeProviderSortConfig:
		u.ProviderSortConfig = best.Value.(*ProviderSortConfig)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ImageGenerationProviderPreferencesSort", string(data))
}

func (u ImageGenerationProviderPreferencesSort) MarshalJSON() ([]byte, error) {
	if u.ProviderSort != nil {
		return utils.MarshalJSON(u.ProviderSort, "", true)
	}

	if u.ProviderSortConfig != nil {
		return utils.MarshalJSON(u.ProviderSortConfig, "", true)
	}

	return nil, errors.New("could not marshal union type ImageGenerationProviderPreferencesSort: all fields are null")
}

// ImageGenerationProviderPreferences - Provider routing preferences and provider-specific passthrough configuration.
type ImageGenerationProviderPreferences struct {
	// Whether to allow backup providers to serve requests
	// - true: (default) when the primary provider (or your custom providers in "order") is unavailable, use the next best provider.
	// - false: use only the primary/custom provider, and return the upstream error if it's unavailable.
	//
	AllowFallbacks optionalnullable.OptionalNullable[bool] `json:"allow_fallbacks,omitzero"`
	// List of provider slugs to ignore. If provided, this list is merged with your account-wide ignored provider settings for this request.
	Ignore optionalnullable.OptionalNullable[[]ImageGenerationProviderPreferencesIgnore] `json:"ignore,omitzero"`
	// List of provider slugs to allow. If provided, this list is merged with your account-wide allowed provider settings for this request.
	Only    optionalnullable.OptionalNullable[[]ImageGenerationProviderPreferencesOnly] `json:"only,omitzero"`
	Options *ImageGenerationProviderPreferencesOptions                                  `json:"options,omitzero"`
	// An ordered list of provider slugs. The router will attempt to use the first provider in the subset of this list that supports your requested model, and fall back to the next if it is unavailable. If no providers are available, the request will fail with an error message.
	Order optionalnullable.OptionalNullable[[]ImageGenerationProviderPreferencesOrder] `json:"order,omitzero"`
	// The sorting strategy to use for this request, if "order" is not specified. When set, no load balancing is performed.
	Sort optionalnullable.OptionalNullable[ImageGenerationProviderPreferencesSort] `json:"sort,omitzero"`
}

func (i ImageGenerationProviderPreferences) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageGenerationProviderPreferences) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageGenerationProviderPreferences) GetAllowFallbacks() optionalnullable.OptionalNullable[bool] {
	if i == nil {
		return nil
	}
	return i.AllowFallbacks
}

func (i *ImageGenerationProviderPreferences) GetIgnore() optionalnullable.OptionalNullable[[]ImageGenerationProviderPreferencesIgnore] {
	if i == nil {
		return nil
	}
	return i.Ignore
}

func (i *ImageGenerationProviderPreferences) GetOnly() optionalnullable.OptionalNullable[[]ImageGenerationProviderPreferencesOnly] {
	if i == nil {
		return nil
	}
	return i.Only
}

func (i *ImageGenerationProviderPreferences) GetOptions() *ImageGenerationProviderPreferencesOptions {
	if i == nil {
		return nil
	}
	return i.Options
}

func (i *ImageGenerationProviderPreferences) GetOrder() optionalnullable.OptionalNullable[[]ImageGenerationProviderPreferencesOrder] {
	if i == nil {
		return nil
	}
	return i.Order
}

func (i *ImageGenerationProviderPreferences) GetSort() optionalnullable.OptionalNullable[ImageGenerationProviderPreferencesSort] {
	if i == nil {
		return nil
	}
	return i.Sort
}
