// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

// ImageGenCompletedEventType - The event type
type ImageGenCompletedEventType string

const (
	ImageGenCompletedEventTypeImageGenerationCompleted ImageGenCompletedEventType = "image_generation.completed"
)

func (e ImageGenCompletedEventType) ToPointer() *ImageGenCompletedEventType {
	return &e
}
func (e *ImageGenCompletedEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "image_generation.completed":
		*e = ImageGenCompletedEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ImageGenCompletedEventType: %v", v)
	}
}

// ImageGenCompletedEvent - Emitted when generation completes and the final image is available
type ImageGenCompletedEvent struct {
	// Base64-encoded final image data
	B64JSON string `json:"b64_json"`
	// Unix timestamp (seconds) when the image was generated
	Created int64 `json:"created"`
	// Media type (MIME type) of the image. Omitted when the output is a standard raster format (PNG). Present for non-raster outputs such as SVG (`image/svg+xml`).
	MediaType *string `json:"media_type,omitzero"`
	// The event type
	Type ImageGenCompletedEventType `json:"type"`
	// Token and cost usage for the image generation request, when available
	Usage *ImageGenerationUsage `json:"usage,omitzero"`
}

func (i ImageGenCompletedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageGenCompletedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageGenCompletedEvent) GetB64JSON() string {
	if i == nil {
		return ""
	}
	return i.B64JSON
}

func (i *ImageGenCompletedEvent) GetCreated() int64 {
	if i == nil {
		return 0
	}
	return i.Created
}

func (i *ImageGenCompletedEvent) GetMediaType() *string {
	if i == nil {
		return nil
	}
	return i.MediaType
}

func (i *ImageGenCompletedEvent) GetType() ImageGenCompletedEventType {
	if i == nil {
		return ImageGenCompletedEventType("")
	}
	return i.Type
}

func (i *ImageGenCompletedEvent) GetUsage() *ImageGenerationUsage {
	if i == nil {
		return nil
	}
	return i.Usage
}
