// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ImageOutputModality string

const (
	ImageOutputModalityText          ImageOutputModality = "text"
	ImageOutputModalityImage         ImageOutputModality = "image"
	ImageOutputModalityEmbeddings    ImageOutputModality = "embeddings"
	ImageOutputModalityAudio         ImageOutputModality = "audio"
	ImageOutputModalityVideo         ImageOutputModality = "video"
	ImageOutputModalityRerank        ImageOutputModality = "rerank"
	ImageOutputModalitySpeech        ImageOutputModality = "speech"
	ImageOutputModalityTranscription ImageOutputModality = "transcription"
)

func (e ImageOutputModality) ToPointer() *ImageOutputModality {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ImageOutputModality) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "image", "embeddings", "audio", "video", "rerank", "speech", "transcription":
			return true
		}
	}
	return false
}
