// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type ImageGenerationUsageCompletionTokensDetails struct {
	// Tokens generated by the model for audio output.
	AudioTokens optionalnullable.OptionalNullable[int64] `json:"audio_tokens,omitzero"`
	// Tokens generated by the model for image output.
	ImageTokens optionalnullable.OptionalNullable[int64] `json:"image_tokens,omitzero"`
	// Tokens generated by the model for reasoning.
	ReasoningTokens optionalnullable.OptionalNullable[int64] `json:"reasoning_tokens,omitzero"`
}

func (i ImageGenerationUsageCompletionTokensDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageGenerationUsageCompletionTokensDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageGenerationUsageCompletionTokensDetails) GetAudioTokens() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.AudioTokens
}

func (i *ImageGenerationUsageCompletionTokensDetails) GetImageTokens() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.ImageTokens
}

func (i *ImageGenerationUsageCompletionTokensDetails) GetReasoningTokens() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.ReasoningTokens
}

// ImageGenerationUsagePromptTokensDetails - Breakdown of tokens used in the prompt.
type ImageGenerationUsagePromptTokensDetails struct {
	// Tokens used for input audio.
	AudioTokens optionalnullable.OptionalNullable[int64] `json:"audio_tokens,omitzero"`
	// Tokens written to cache. Only returned for models with explicit caching and cache write pricing.
	CacheWriteTokens optionalnullable.OptionalNullable[int64] `json:"cache_write_tokens,omitzero"`
	// Tokens cached by the endpoint.
	CachedTokens optionalnullable.OptionalNullable[int64] `json:"cached_tokens,omitzero"`
	// Tokens used for input files/documents.
	FileTokens optionalnullable.OptionalNullable[int64] `json:"file_tokens,omitzero"`
	// Tokens used for input video.
	VideoTokens optionalnullable.OptionalNullable[int64] `json:"video_tokens,omitzero"`
}

func (i ImageGenerationUsagePromptTokensDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageGenerationUsagePromptTokensDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageGenerationUsagePromptTokensDetails) GetAudioTokens() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.AudioTokens
}

func (i *ImageGenerationUsagePromptTokensDetails) GetCacheWriteTokens() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.CacheWriteTokens
}

func (i *ImageGenerationUsagePromptTokensDetails) GetCachedTokens() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.CachedTokens
}

func (i *ImageGenerationUsagePromptTokensDetails) GetFileTokens() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.FileTokens
}

func (i *ImageGenerationUsagePromptTokensDetails) GetVideoTokens() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.VideoTokens
}

// ServerToolUse - Usage for server-side tool execution (e.g., web search)
type ServerToolUse struct {
	// Number of OpenRouter server tool calls that executed and produced a result.
	ToolCallsExecuted optionalnullable.OptionalNullable[int64] `json:"tool_calls_executed,omitzero"`
	// Total number of OpenRouter server-orchestrated tool calls the model requested, across all tool types. Provider-native tools (e.g. native web search) are not counted here.
	ToolCallsRequested optionalnullable.OptionalNullable[int64] `json:"tool_calls_requested,omitzero"`
	// Number of web searches performed by server-side tools. For server-orchestrated tool calls a web search is also counted in tool_calls_requested; provider-native web search may report web_search_requests only. Do not sum the two.
	WebSearchRequests optionalnullable.OptionalNullable[int64] `json:"web_search_requests,omitzero"`
}

func (s ServerToolUse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServerToolUse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServerToolUse) GetToolCallsExecuted() optionalnullable.OptionalNullable[int64] {
	if s == nil {
		return nil
	}
	return s.ToolCallsExecuted
}

func (s *ServerToolUse) GetToolCallsRequested() optionalnullable.OptionalNullable[int64] {
	if s == nil {
		return nil
	}
	return s.ToolCallsRequested
}

func (s *ServerToolUse) GetWebSearchRequests() optionalnullable.OptionalNullable[int64] {
	if s == nil {
		return nil
	}
	return s.WebSearchRequests
}

// ImageGenerationUsage - Token and cost usage for the image generation request, when available
type ImageGenerationUsage struct {
	CacheCreation optionalnullable.OptionalNullable[AnthropicCacheCreation] `json:"cache_creation,omitzero"`
	// The tokens generated
	CompletionTokens        int64                                                                          `json:"completion_tokens"`
	CompletionTokensDetails optionalnullable.OptionalNullable[ImageGenerationUsageCompletionTokensDetails] `json:"completion_tokens_details,omitzero"`
	// Cost of the completion
	Cost optionalnullable.OptionalNullable[float64] `json:"cost,omitzero"`
	// Breakdown of upstream inference costs
	CostDetails optionalnullable.OptionalNullable[CostDetails] `json:"cost_details,omitzero"`
	// Whether a request was made using a Bring Your Own Key configuration
	IsByok     *bool                                                        `json:"is_byok,omitzero"`
	Iterations optionalnullable.OptionalNullable[[]AnthropicUsageIteration] `json:"iterations,omitzero"`
	// Including images, input audio, and tools if any
	PromptTokens int64 `json:"prompt_tokens"`
	// Breakdown of tokens used in the prompt.
	PromptTokensDetails optionalnullable.OptionalNullable[ImageGenerationUsagePromptTokensDetails] `json:"prompt_tokens_details,omitzero"`
	// Usage for server-side tool execution (e.g., web search)
	ServerToolUse optionalnullable.OptionalNullable[ServerToolUse] `json:"server_tool_use,omitzero"`
	// The service tier used by the upstream provider for this request
	ServiceTier optionalnullable.OptionalNullable[string]         `json:"service_tier,omitzero"`
	Speed       optionalnullable.OptionalNullable[AnthropicSpeed] `json:"speed,omitzero"`
	// Sum of the above two fields
	TotalTokens int64 `json:"total_tokens"`
}

func (i ImageGenerationUsage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageGenerationUsage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageGenerationUsage) GetCacheCreation() optionalnullable.OptionalNullable[AnthropicCacheCreation] {
	if i == nil {
		return nil
	}
	return i.CacheCreation
}

func (i *ImageGenerationUsage) GetCompletionTokens() int64 {
	if i == nil {
		return 0
	}
	return i.CompletionTokens
}

func (i *ImageGenerationUsage) GetCompletionTokensDetails() optionalnullable.OptionalNullable[ImageGenerationUsageCompletionTokensDetails] {
	if i == nil {
		return nil
	}
	return i.CompletionTokensDetails
}

func (i *ImageGenerationUsage) GetCost() optionalnullable.OptionalNullable[float64] {
	if i == nil {
		return nil
	}
	return i.Cost
}

func (i *ImageGenerationUsage) GetCostDetails() optionalnullable.OptionalNullable[CostDetails] {
	if i == nil {
		return nil
	}
	return i.CostDetails
}

func (i *ImageGenerationUsage) GetIsByok() *bool {
	if i == nil {
		return nil
	}
	return i.IsByok
}

func (i *ImageGenerationUsage) GetIterations() optionalnullable.OptionalNullable[[]AnthropicUsageIteration] {
	if i == nil {
		return nil
	}
	return i.Iterations
}

func (i *ImageGenerationUsage) GetPromptTokens() int64 {
	if i == nil {
		return 0
	}
	return i.PromptTokens
}

func (i *ImageGenerationUsage) GetPromptTokensDetails() optionalnullable.OptionalNullable[ImageGenerationUsagePromptTokensDetails] {
	if i == nil {
		return nil
	}
	return i.PromptTokensDetails
}

func (i *ImageGenerationUsage) GetServerToolUse() optionalnullable.OptionalNullable[ServerToolUse] {
	if i == nil {
		return nil
	}
	return i.ServerToolUse
}

func (i *ImageGenerationUsage) GetServiceTier() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.ServiceTier
}

func (i *ImageGenerationUsage) GetSpeed() optionalnullable.OptionalNullable[AnthropicSpeed] {
	if i == nil {
		return nil
	}
	return i.Speed
}

func (i *ImageGenerationUsage) GetTotalTokens() int64 {
	if i == nil {
		return 0
	}
	return i.TotalTokens
}
