// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// InternListResponse - Interns visible to the authenticated API key.
type InternListResponse struct {
	Data []Intern `json:"data"`
	// True when more interns match the current filters.
	HasMore bool `json:"has_more"`
}

func (i *InternListResponse) GetData() []Intern {
	if i == nil {
		return []Intern{}
	}
	return i.Data
}

func (i *InternListResponse) GetHasMore() bool {
	if i == nil {
		return false
	}
	return i.HasMore
}
