// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// InternChatSteeredResponseStatus - The message was handed to the turn already running on this session.
type InternChatSteeredResponseStatus string

const (
	InternChatSteeredResponseStatusSteered InternChatSteeredResponseStatus = "steered"
)

func (e InternChatSteeredResponseStatus) ToPointer() *InternChatSteeredResponseStatus {
	return &e
}
func (e *InternChatSteeredResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "steered":
		*e = InternChatSteeredResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InternChatSteeredResponseStatus: %v", v)
	}
}

// InternChatSteeredResponse - The message was delivered into the turn already running on the same session. Its effect is streamed on that turn, not here.
type InternChatSteeredResponse struct {
	// The session of the running turn the message was delivered to.
	SessionID string `json:"session_id"`
	// The message was handed to the turn already running on this session.
	Status InternChatSteeredResponseStatus `json:"status"`
}

func (i *InternChatSteeredResponse) GetSessionID() string {
	if i == nil {
		return ""
	}
	return i.SessionID
}

func (i *InternChatSteeredResponse) GetStatus() InternChatSteeredResponseStatus {
	if i == nil {
		return InternChatSteeredResponseStatus("")
	}
	return i.Status
}
