// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type MessagesBashToolResultBlockType string

const (
	MessagesBashToolResultBlockTypeOpenrouterBashToolResult MessagesBashToolResultBlockType = "openrouter_bash_tool_result"
)

func (e MessagesBashToolResultBlockType) ToPointer() *MessagesBashToolResultBlockType {
	return &e
}
func (e *MessagesBashToolResultBlockType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter_bash_tool_result":
		*e = MessagesBashToolResultBlockType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MessagesBashToolResultBlockType: %v", v)
	}
}

// MessagesBashToolResultBlock - Output of a sandbox-executed `openrouter:bash` call from a prior assistant turn. Accepted on replay and dropped before the provider request — Anthropic has no equivalent block.
type MessagesBashToolResultBlock struct {
	Content   map[string]any                  `json:"content"`
	ToolUseID string                          `json:"tool_use_id"`
	Type      MessagesBashToolResultBlockType `json:"type"`
}

func (m MessagesBashToolResultBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessagesBashToolResultBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MessagesBashToolResultBlock) GetContent() map[string]any {
	if m == nil {
		return map[string]any{}
	}
	return m.Content
}

func (m *MessagesBashToolResultBlock) GetToolUseID() string {
	if m == nil {
		return ""
	}
	return m.ToolUseID
}

func (m *MessagesBashToolResultBlock) GetType() MessagesBashToolResultBlockType {
	if m == nil {
		return MessagesBashToolResultBlockType("")
	}
	return m.Type
}
