// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type OpenRouterFileListShape string

const (
	OpenRouterFileListShapeOpenrouter OpenRouterFileListShape = "openrouter"
)

func (e OpenRouterFileListShape) ToPointer() *OpenRouterFileListShape {
	return &e
}
func (e *OpenRouterFileListShape) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter":
		*e = OpenRouterFileListShape(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenRouterFileListShape: %v", v)
	}
}

// OpenRouterFileList - A page of files in the OpenRouter shape.
type OpenRouterFileList struct {
	Shape OpenRouterFileListShape `json:"_shape"`
	// Opaque cursor for the next page; null when there are no more results.
	Cursor  *string          `json:"cursor"`
	Data    []OpenRouterFile `json:"data"`
	FirstID *string          `json:"first_id"`
	HasMore bool             `json:"has_more"`
	LastID  *string          `json:"last_id"`
}

func (o OpenRouterFileList) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenRouterFileList) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenRouterFileList) GetShape() OpenRouterFileListShape {
	if o == nil {
		return OpenRouterFileListShape("")
	}
	return o.Shape
}

func (o *OpenRouterFileList) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *OpenRouterFileList) GetData() []OpenRouterFile {
	if o == nil {
		return []OpenRouterFile{}
	}
	return o.Data
}

func (o *OpenRouterFileList) GetFirstID() *string {
	if o == nil {
		return nil
	}
	return o.FirstID
}

func (o *OpenRouterFileList) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *OpenRouterFileList) GetLastID() *string {
	if o == nil {
		return nil
	}
	return o.LastID
}
