// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type CodeEnum string

const (
	CodeEnumServerError                 CodeEnum = "server_error"
	CodeEnumRateLimitExceeded           CodeEnum = "rate_limit_exceeded"
	CodeEnumInvalidPrompt               CodeEnum = "invalid_prompt"
	CodeEnumVectorStoreTimeout          CodeEnum = "vector_store_timeout"
	CodeEnumInvalidImage                CodeEnum = "invalid_image"
	CodeEnumInvalidImageFormat          CodeEnum = "invalid_image_format"
	CodeEnumInvalidBase64Image          CodeEnum = "invalid_base64_image"
	CodeEnumInvalidImageURL             CodeEnum = "invalid_image_url"
	CodeEnumImageTooLarge               CodeEnum = "image_too_large"
	CodeEnumImageTooSmall               CodeEnum = "image_too_small"
	CodeEnumImageParseError             CodeEnum = "image_parse_error"
	CodeEnumImageContentPolicyViolation CodeEnum = "image_content_policy_violation"
	CodeEnumInvalidImageMode            CodeEnum = "invalid_image_mode"
	CodeEnumImageFileTooLarge           CodeEnum = "image_file_too_large"
	CodeEnumUnsupportedImageMediaType   CodeEnum = "unsupported_image_media_type"
	CodeEnumEmptyImageFile              CodeEnum = "empty_image_file"
	CodeEnumFailedToDownloadImage       CodeEnum = "failed_to_download_image"
	CodeEnumImageFileNotFound           CodeEnum = "image_file_not_found"
	CodeEnumBioPolicy                   CodeEnum = "bio_policy"
	CodeEnumCyberPolicy                 CodeEnum = "cyber_policy"
	CodeEnumMisalignmentPolicyViolation CodeEnum = "misalignment_policy_violation"
	CodeEnumDataResidencyMismatch       CodeEnum = "data_residency_mismatch"
)

func (e CodeEnum) ToPointer() *CodeEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CodeEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "server_error", "rate_limit_exceeded", "invalid_prompt", "vector_store_timeout", "invalid_image", "invalid_image_format", "invalid_base64_image", "invalid_image_url", "image_too_large", "image_too_small", "image_parse_error", "image_content_policy_violation", "invalid_image_mode", "image_file_too_large", "unsupported_image_media_type", "empty_image_file", "failed_to_download_image", "image_file_not_found", "bio_policy", "cyber_policy", "misalignment_policy_violation", "data_residency_mismatch":
			return true
		}
	}
	return false
}

// OpenResponsesErrorField - Error of a failed response; `metadata` carries OpenRouter-specific details.
type OpenResponsesErrorField struct {
	Code    CodeEnum `json:"code"`
	Message string   `json:"message"`
	// OpenRouter-specific details of a failed response, such as the alignment object of an alignment error.
	Metadata *OpenResponsesErrorMetadata `json:"metadata,omitzero"`
}

func (o OpenResponsesErrorField) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenResponsesErrorField) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenResponsesErrorField) GetCode() CodeEnum {
	if o == nil {
		return CodeEnum("")
	}
	return o.Code
}

func (o *OpenResponsesErrorField) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *OpenResponsesErrorField) GetMetadata() *OpenResponsesErrorMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}
