// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type ORAnthropicServerToolUseBlockType string

const (
	ORAnthropicServerToolUseBlockTypeServerToolUse ORAnthropicServerToolUseBlockType = "server_tool_use"
)

func (e ORAnthropicServerToolUseBlockType) ToPointer() *ORAnthropicServerToolUseBlockType {
	return &e
}
func (e *ORAnthropicServerToolUseBlockType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "server_tool_use":
		*e = ORAnthropicServerToolUseBlockType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ORAnthropicServerToolUseBlockType: %v", v)
	}
}

type ORAnthropicServerToolUseBlock struct {
	Caller optionalnullable.OptionalNullable[ORAnthropicNullableCaller] `json:"caller,omitzero"`
	ID     string                                                       `json:"id"`
	Input  any                                                          `json:"input,omitzero"`
	Name   string                                                       `json:"name"`
	Type   ORAnthropicServerToolUseBlockType                            `json:"type"`
}

func (o ORAnthropicServerToolUseBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ORAnthropicServerToolUseBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ORAnthropicServerToolUseBlock) GetCaller() optionalnullable.OptionalNullable[ORAnthropicNullableCaller] {
	if o == nil {
		return nil
	}
	return o.Caller
}

func (o *ORAnthropicServerToolUseBlock) GetCallerCodeExecution20250825() *AnthropicCodeExecution20250825Caller {
	if v := o.GetCaller(); v != nil {
		if actualValue, ok := v.Get(); ok && actualValue != nil {
			return actualValue.AnthropicCodeExecution20250825Caller
		}
		return nil
	}
	return nil
}

func (o *ORAnthropicServerToolUseBlock) GetCallerCodeExecution20260120() *AnthropicCodeExecution20260120Caller {
	if v := o.GetCaller(); v != nil {
		if actualValue, ok := v.Get(); ok && actualValue != nil {
			return actualValue.AnthropicCodeExecution20260120Caller
		}
		return nil
	}
	return nil
}

func (o *ORAnthropicServerToolUseBlock) GetCallerDirect() *AnthropicDirectCaller {
	if v := o.GetCaller(); v != nil {
		if actualValue, ok := v.Get(); ok && actualValue != nil {
			return actualValue.AnthropicDirectCaller
		}
		return nil
	}
	return nil
}

func (o *ORAnthropicServerToolUseBlock) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ORAnthropicServerToolUseBlock) GetInput() any {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *ORAnthropicServerToolUseBlock) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ORAnthropicServerToolUseBlock) GetType() ORAnthropicServerToolUseBlockType {
	if o == nil {
		return ORAnthropicServerToolUseBlockType("")
	}
	return o.Type
}
