// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type OutputShellCallOutputItemType string

const (
	OutputShellCallOutputItemTypeShellCallOutput OutputShellCallOutputItemType = "shell_call_output"
)

func (e OutputShellCallOutputItemType) ToPointer() *OutputShellCallOutputItemType {
	return &e
}
func (e *OutputShellCallOutputItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "shell_call_output":
		*e = OutputShellCallOutputItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputShellCallOutputItemType: %v", v)
	}
}

// OutputShellCallOutputItem - A native `shell_call_output` item matching OpenAI's Responses API shape. Carries per-command stdout, stderr, and the exit/timeout outcome.
type OutputShellCallOutputItem struct {
	CallID          string                                   `json:"call_id"`
	ID              string                                   `json:"id"`
	MaxOutputLength optionalnullable.OptionalNullable[int64] `json:"max_output_length,omitzero"`
	Output          []ShellCallOutputContent                 `json:"output"`
	// Status of a shell call or its output.
	Status ShellCallStatus               `json:"status"`
	Type   OutputShellCallOutputItemType `json:"type"`
}

func (o OutputShellCallOutputItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputShellCallOutputItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputShellCallOutputItem) GetCallID() string {
	if o == nil {
		return ""
	}
	return o.CallID
}

func (o *OutputShellCallOutputItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OutputShellCallOutputItem) GetMaxOutputLength() optionalnullable.OptionalNullable[int64] {
	if o == nil {
		return nil
	}
	return o.MaxOutputLength
}

func (o *OutputShellCallOutputItem) GetOutput() []ShellCallOutputContent {
	if o == nil {
		return []ShellCallOutputContent{}
	}
	return o.Output
}

func (o *OutputShellCallOutputItem) GetStatus() ShellCallStatus {
	if o == nil {
		return ShellCallStatus("")
	}
	return o.Status
}

func (o *OutputShellCallOutputItem) GetType() OutputShellCallOutputItemType {
	if o == nil {
		return OutputShellCallOutputItemType("")
	}
	return o.Type
}
