// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type OutputApplyPatchServerToolItemType string

const (
	OutputApplyPatchServerToolItemTypeOpenrouterApplyPatch OutputApplyPatchServerToolItemType = "openrouter:apply_patch"
)

func (e OutputApplyPatchServerToolItemType) ToPointer() *OutputApplyPatchServerToolItemType {
	return &e
}
func (e *OutputApplyPatchServerToolItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:apply_patch":
		*e = OutputApplyPatchServerToolItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputApplyPatchServerToolItemType: %v", v)
	}
}

// OutputApplyPatchServerToolItem - An openrouter:apply_patch server tool output item
type OutputApplyPatchServerToolItem struct {
	FilePath *string                            `json:"filePath,omitzero"`
	ID       *string                            `json:"id,omitzero"`
	Patch    *string                            `json:"patch,omitzero"`
	Status   ToolCallStatus                     `json:"status"`
	Type     OutputApplyPatchServerToolItemType `json:"type"`
}

func (o OutputApplyPatchServerToolItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputApplyPatchServerToolItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputApplyPatchServerToolItem) GetFilePath() *string {
	if o == nil {
		return nil
	}
	return o.FilePath
}

func (o *OutputApplyPatchServerToolItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputApplyPatchServerToolItem) GetPatch() *string {
	if o == nil {
		return nil
	}
	return o.Patch
}

func (o *OutputApplyPatchServerToolItem) GetStatus() ToolCallStatus {
	if o == nil {
		return ToolCallStatus("")
	}
	return o.Status
}

func (o *OutputApplyPatchServerToolItem) GetType() OutputApplyPatchServerToolItemType {
	if o == nil {
		return OutputApplyPatchServerToolItemType("")
	}
	return o.Type
}
