// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type OutputShellCallItemAction struct {
	Commands        []string `json:"commands"`
	MaxOutputLength *int64   `json:"max_output_length"`
	TimeoutMs       *int64   `json:"timeout_ms"`
}

func (o OutputShellCallItemAction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputShellCallItemAction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputShellCallItemAction) GetCommands() []string {
	if o == nil {
		return []string{}
	}
	return o.Commands
}

func (o *OutputShellCallItemAction) GetMaxOutputLength() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxOutputLength
}

func (o *OutputShellCallItemAction) GetTimeoutMs() *int64 {
	if o == nil {
		return nil
	}
	return o.TimeoutMs
}

type OutputShellCallItemType string

const (
	OutputShellCallItemTypeShellCall OutputShellCallItemType = "shell_call"
)

func (e OutputShellCallItemType) ToPointer() *OutputShellCallItemType {
	return &e
}
func (e *OutputShellCallItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "shell_call":
		*e = OutputShellCallItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputShellCallItemType: %v", v)
	}
}

// OutputShellCallItem - A native `shell_call` output item matching OpenAI's Responses API shape. Emitted for the sandbox-backed `shell` tool.
type OutputShellCallItem struct {
	Action *OutputShellCallItemAction `json:"action,omitzero"`
	CallID string                     `json:"call_id"`
	ID     string                     `json:"id"`
	// Status of a shell call or its output.
	Status ShellCallStatus         `json:"status"`
	Type   OutputShellCallItemType `json:"type"`
}

func (o OutputShellCallItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputShellCallItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputShellCallItem) GetAction() *OutputShellCallItemAction {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *OutputShellCallItem) GetCallID() string {
	if o == nil {
		return ""
	}
	return o.CallID
}

func (o *OutputShellCallItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OutputShellCallItem) GetStatus() ShellCallStatus {
	if o == nil {
		return ShellCallStatus("")
	}
	return o.Status
}

func (o *OutputShellCallItem) GetType() OutputShellCallItemType {
	if o == nil {
		return OutputShellCallItemType("")
	}
	return o.Type
}
