// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type OutputItemCodeInterpreterCallOutputType string

const (
	OutputItemCodeInterpreterCallOutputTypeFile    OutputItemCodeInterpreterCallOutputType = "file"
	OutputItemCodeInterpreterCallOutputTypeImage   OutputItemCodeInterpreterCallOutputType = "image"
	OutputItemCodeInterpreterCallOutputTypeLogs    OutputItemCodeInterpreterCallOutputType = "logs"
	OutputItemCodeInterpreterCallOutputTypeUnknown OutputItemCodeInterpreterCallOutputType = "UNKNOWN"
)

type OutputItemCodeInterpreterCallOutput struct {
	CodeInterpreterLogsOutput  *CodeInterpreterLogsOutput  `queryParam:"inline" union:"member"`
	CodeInterpreterImageOutput *CodeInterpreterImageOutput `queryParam:"inline" union:"member"`
	CodeInterpreterFileOutput  *CodeInterpreterFileOutput  `queryParam:"inline" union:"member"`
	UnknownRaw                 json.RawMessage             `json:"-" union:"unknown"`

	Type OutputItemCodeInterpreterCallOutputType
}

func CreateOutputItemCodeInterpreterCallOutputFile(file CodeInterpreterFileOutput) OutputItemCodeInterpreterCallOutput {
	typ := OutputItemCodeInterpreterCallOutputTypeFile

	typStr := CodeInterpreterFileOutputType(typ)
	file.Type = typStr

	return OutputItemCodeInterpreterCallOutput{
		CodeInterpreterFileOutput: &file,
		Type:                      typ,
	}
}

func CreateOutputItemCodeInterpreterCallOutputImage(image CodeInterpreterImageOutput) OutputItemCodeInterpreterCallOutput {
	typ := OutputItemCodeInterpreterCallOutputTypeImage

	typStr := CodeInterpreterImageOutputType(typ)
	image.Type = typStr

	return OutputItemCodeInterpreterCallOutput{
		CodeInterpreterImageOutput: &image,
		Type:                       typ,
	}
}

func CreateOutputItemCodeInterpreterCallOutputLogs(logs CodeInterpreterLogsOutput) OutputItemCodeInterpreterCallOutput {
	typ := OutputItemCodeInterpreterCallOutputTypeLogs

	typStr := CodeInterpreterLogsOutputType(typ)
	logs.Type = typStr

	return OutputItemCodeInterpreterCallOutput{
		CodeInterpreterLogsOutput: &logs,
		Type:                      typ,
	}
}

func CreateOutputItemCodeInterpreterCallOutputUnknown(raw json.RawMessage) OutputItemCodeInterpreterCallOutput {
	return OutputItemCodeInterpreterCallOutput{
		UnknownRaw: raw,
		Type:       OutputItemCodeInterpreterCallOutputTypeUnknown,
	}
}

func (u OutputItemCodeInterpreterCallOutput) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u OutputItemCodeInterpreterCallOutput) IsUnknown() bool {
	return u.Type == OutputItemCodeInterpreterCallOutputTypeUnknown
}

func (u *OutputItemCodeInterpreterCallOutput) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OutputItemCodeInterpreterCallOutputTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OutputItemCodeInterpreterCallOutputTypeUnknown
		return nil
	}

	switch dis.Type {
	case "file":
		codeInterpreterFileOutput := new(CodeInterpreterFileOutput)
		if err := utils.UnmarshalJSON(data, &codeInterpreterFileOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file) type CodeInterpreterFileOutput within OutputItemCodeInterpreterCallOutput: %w", string(data), err)
		}

		u.CodeInterpreterFileOutput = codeInterpreterFileOutput
		u.Type = OutputItemCodeInterpreterCallOutputTypeFile
		return nil
	case "image":
		codeInterpreterImageOutput := new(CodeInterpreterImageOutput)
		if err := utils.UnmarshalJSON(data, &codeInterpreterImageOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == image) type CodeInterpreterImageOutput within OutputItemCodeInterpreterCallOutput: %w", string(data), err)
		}

		u.CodeInterpreterImageOutput = codeInterpreterImageOutput
		u.Type = OutputItemCodeInterpreterCallOutputTypeImage
		return nil
	case "logs":
		codeInterpreterLogsOutput := new(CodeInterpreterLogsOutput)
		if err := utils.UnmarshalJSON(data, &codeInterpreterLogsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == logs) type CodeInterpreterLogsOutput within OutputItemCodeInterpreterCallOutput: %w", string(data), err)
		}

		u.CodeInterpreterLogsOutput = codeInterpreterLogsOutput
		u.Type = OutputItemCodeInterpreterCallOutputTypeLogs
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OutputItemCodeInterpreterCallOutputTypeUnknown
		return nil
	}

}

func (u OutputItemCodeInterpreterCallOutput) MarshalJSON() ([]byte, error) {
	if u.CodeInterpreterLogsOutput != nil {
		return utils.MarshalJSON(u.CodeInterpreterLogsOutput, "", true)
	}

	if u.CodeInterpreterImageOutput != nil {
		return utils.MarshalJSON(u.CodeInterpreterImageOutput, "", true)
	}

	if u.CodeInterpreterFileOutput != nil {
		return utils.MarshalJSON(u.CodeInterpreterFileOutput, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type OutputItemCodeInterpreterCallOutput: all fields are null")
}

type OutputItemCodeInterpreterCallStatus string

const (
	OutputItemCodeInterpreterCallStatusInProgress   OutputItemCodeInterpreterCallStatus = "in_progress"
	OutputItemCodeInterpreterCallStatusCompleted    OutputItemCodeInterpreterCallStatus = "completed"
	OutputItemCodeInterpreterCallStatusIncomplete   OutputItemCodeInterpreterCallStatus = "incomplete"
	OutputItemCodeInterpreterCallStatusInterpreting OutputItemCodeInterpreterCallStatus = "interpreting"
	OutputItemCodeInterpreterCallStatusFailed       OutputItemCodeInterpreterCallStatus = "failed"
)

func (e OutputItemCodeInterpreterCallStatus) ToPointer() *OutputItemCodeInterpreterCallStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OutputItemCodeInterpreterCallStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "in_progress", "completed", "incomplete", "interpreting", "failed":
			return true
		}
	}
	return false
}

type OutputItemCodeInterpreterCallType string

const (
	OutputItemCodeInterpreterCallTypeCodeInterpreterCall OutputItemCodeInterpreterCallType = "code_interpreter_call"
)

func (e OutputItemCodeInterpreterCallType) ToPointer() *OutputItemCodeInterpreterCallType {
	return &e
}
func (e *OutputItemCodeInterpreterCallType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "code_interpreter_call":
		*e = OutputItemCodeInterpreterCallType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputItemCodeInterpreterCallType: %v", v)
	}
}

type OutputItemCodeInterpreterCall struct {
	Code                 optionalnullable.OptionalNullable[string]                                `json:"code,omitzero"`
	ContainerID          *string                                                                  `json:"container_id,omitzero"`
	ID                   string                                                                   `json:"id"`
	Outputs              optionalnullable.OptionalNullable[[]OutputItemCodeInterpreterCallOutput] `json:"outputs,omitzero"`
	Status               OutputItemCodeInterpreterCallStatus                                      `json:"status"`
	Type                 OutputItemCodeInterpreterCallType                                        `json:"type"`
	AdditionalProperties map[string]any                                                           `additionalProperties:"true" json:"-"`
}

func (o OutputItemCodeInterpreterCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputItemCodeInterpreterCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputItemCodeInterpreterCall) GetCode() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *OutputItemCodeInterpreterCall) GetContainerID() *string {
	if o == nil {
		return nil
	}
	return o.ContainerID
}

func (o *OutputItemCodeInterpreterCall) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OutputItemCodeInterpreterCall) GetOutputs() optionalnullable.OptionalNullable[[]OutputItemCodeInterpreterCallOutput] {
	if o == nil {
		return nil
	}
	return o.Outputs
}

func (o *OutputItemCodeInterpreterCall) GetStatus() OutputItemCodeInterpreterCallStatus {
	if o == nil {
		return OutputItemCodeInterpreterCallStatus("")
	}
	return o.Status
}

func (o *OutputItemCodeInterpreterCall) GetType() OutputItemCodeInterpreterCallType {
	if o == nil {
		return OutputItemCodeInterpreterCallType("")
	}
	return o.Type
}

func (o *OutputItemCodeInterpreterCall) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
