// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PresetStatus - The status of a preset.
type PresetStatus string

const (
	PresetStatusActive   PresetStatus = "active"
	PresetStatusDisabled PresetStatus = "disabled"
	PresetStatusArchived PresetStatus = "archived"
)

func (e PresetStatus) ToPointer() *PresetStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PresetStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "disabled", "archived":
			return true
		}
	}
	return false
}
