// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PrivateEndpointResponse struct {
	Data PrivateEndpoint `json:"data"`
}

func (p *PrivateEndpointResponse) GetData() PrivateEndpoint {
	if p == nil {
		return PrivateEndpoint{}
	}
	return p.Data
}
