// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type PrivateEndpointCheck struct {
	// Model the upstream reported serving, when it differs from the request.
	ActualModel optionalnullable.OptionalNullable[string] `json:"actual_model,omitzero"`
	// Check name.
	Name   string `json:"name"`
	Passed bool   `json:"passed"`
	// Why the check failed.
	Reason *PrivateEndpointCheckReason `json:"reason,omitzero"`
	// Error message returned by your deployment when the call failed.
	UpstreamMessage optionalnullable.OptionalNullable[string] `json:"upstream_message,omitzero"`
	// HTTP status returned by your deployment when the call failed.
	UpstreamStatus *int64 `json:"upstream_status,omitzero"`
}

func (p PrivateEndpointCheck) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrivateEndpointCheck) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PrivateEndpointCheck) GetActualModel() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ActualModel
}

func (p *PrivateEndpointCheck) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PrivateEndpointCheck) GetPassed() bool {
	if p == nil {
		return false
	}
	return p.Passed
}

func (p *PrivateEndpointCheck) GetReason() *PrivateEndpointCheckReason {
	if p == nil {
		return nil
	}
	return p.Reason
}

func (p *PrivateEndpointCheck) GetUpstreamMessage() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.UpstreamMessage
}

func (p *PrivateEndpointCheck) GetUpstreamStatus() *int64 {
	if p == nil {
		return nil
	}
	return p.UpstreamStatus
}
