// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReasoningSummaryVerbosityEnum string

const (
	ReasoningSummaryVerbosityEnumAuto     ReasoningSummaryVerbosityEnum = "auto"
	ReasoningSummaryVerbosityEnumConcise  ReasoningSummaryVerbosityEnum = "concise"
	ReasoningSummaryVerbosityEnumDetailed ReasoningSummaryVerbosityEnum = "detailed"
)

func (e ReasoningSummaryVerbosityEnum) ToPointer() *ReasoningSummaryVerbosityEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ReasoningSummaryVerbosityEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "concise", "detailed":
			return true
		}
	}
	return false
}
