// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SearchQualityLevel - How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search.
type SearchQualityLevel string

const (
	SearchQualityLevelLow    SearchQualityLevel = "low"
	SearchQualityLevelMedium SearchQualityLevel = "medium"
	SearchQualityLevelHigh   SearchQualityLevel = "high"
)

func (e SearchQualityLevel) ToPointer() *SearchQualityLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SearchQualityLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "low", "medium", "high":
			return true
		}
	}
	return false
}
