// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// STTTimestampGranularity - A timestamp detail level for verbose_json transcription responses.
type STTTimestampGranularity string

const (
	STTTimestampGranularityWord    STTTimestampGranularity = "word"
	STTTimestampGranularitySegment STTTimestampGranularity = "segment"
)

func (e STTTimestampGranularity) ToPointer() *STTTimestampGranularity {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *STTTimestampGranularity) IsExact() bool {
	if e != nil {
		switch *e {
		case "word", "segment":
			return true
		}
	}
	return false
}
