// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type TextConfigVerbosity string

const (
	TextConfigVerbosityHigh   TextConfigVerbosity = "high"
	TextConfigVerbosityLow    TextConfigVerbosity = "low"
	TextConfigVerbosityMedium TextConfigVerbosity = "medium"
)

func (e TextConfigVerbosity) ToPointer() *TextConfigVerbosity {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TextConfigVerbosity) IsExact() bool {
	if e != nil {
		switch *e {
		case "high", "low", "medium":
			return true
		}
	}
	return false
}

// TextConfig - Text output configuration including format and verbosity
type TextConfig struct {
	// Text response format configuration
	Format    *Formats                                               `json:"format,omitzero"`
	Verbosity optionalnullable.OptionalNullable[TextConfigVerbosity] `json:"verbosity,omitzero"`
}

func (t TextConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TextConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TextConfig) GetFormat() *Formats {
	if t == nil {
		return nil
	}
	return t.Format
}

func (t *TextConfig) GetFormatText() *FormatTextConfig {
	if v := t.GetFormat(); v != nil {
		return v.FormatTextConfig
	}
	return nil
}

func (t *TextConfig) GetFormatJSONObject() *FormatJSONObjectConfig {
	if v := t.GetFormat(); v != nil {
		return v.FormatJSONObjectConfig
	}
	return nil
}

func (t *TextConfig) GetFormatJSONSchema() *FormatJSONSchemaConfig {
	if v := t.GetFormat(); v != nil {
		return v.FormatJSONSchemaConfig
	}
	return nil
}

func (t *TextConfig) GetVerbosity() optionalnullable.OptionalNullable[TextConfigVerbosity] {
	if t == nil {
		return nil
	}
	return t.Verbosity
}
