// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdatePrivateEndpointPricingRequest struct {
	// Negotiated per-token rates reported for requests routed to this endpoint.
	Pricing PrivateEndpointPricing `json:"pricing"`
}

func (u *UpdatePrivateEndpointPricingRequest) GetPricing() PrivateEndpointPricing {
	if u == nil {
		return PrivateEndpointPricing{}
	}
	return u.Pricing
}
