// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

// UpdatePrivateEndpointRequestDeclaredRegion - Attest where this deployment processes data.
type UpdatePrivateEndpointRequestDeclaredRegion string

const (
	UpdatePrivateEndpointRequestDeclaredRegionGlobal UpdatePrivateEndpointRequestDeclaredRegion = "global"
	UpdatePrivateEndpointRequestDeclaredRegionEurope UpdatePrivateEndpointRequestDeclaredRegion = "europe"
	UpdatePrivateEndpointRequestDeclaredRegionUs     UpdatePrivateEndpointRequestDeclaredRegion = "us"
)

func (e UpdatePrivateEndpointRequestDeclaredRegion) ToPointer() *UpdatePrivateEndpointRequestDeclaredRegion {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UpdatePrivateEndpointRequestDeclaredRegion) IsExact() bool {
	if e != nil {
		switch *e {
		case "global", "europe", "us":
			return true
		}
	}
	return false
}

type UpdatePrivateEndpointRequest struct {
	// HTTPS base URL of your deployment. Required unless the provider derives its URL from the BYOK credential (Azure, Amazon Bedrock, Google Vertex).
	BaseURL *string `json:"base_url,omitzero"`
	// Attest where this deployment processes data.
	DeclaredRegion optionalnullable.OptionalNullable[UpdatePrivateEndpointRequestDeclaredRegion] `json:"declared_region,omitzero"`
	// Attest that this deployment retains no prompt or completion data.
	DeclaredZdr optionalnullable.OptionalNullable[bool] `json:"declared_zdr,omitzero"`
	// Model or deployment identifier sent to the upstream provider.
	UpstreamModelID string `json:"upstream_model_id"`
}

func (u *UpdatePrivateEndpointRequest) GetBaseURL() *string {
	if u == nil {
		return nil
	}
	return u.BaseURL
}

func (u *UpdatePrivateEndpointRequest) GetDeclaredRegion() optionalnullable.OptionalNullable[UpdatePrivateEndpointRequestDeclaredRegion] {
	if u == nil {
		return nil
	}
	return u.DeclaredRegion
}

func (u *UpdatePrivateEndpointRequest) GetDeclaredZdr() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.DeclaredZdr
}

func (u *UpdatePrivateEndpointRequest) GetUpstreamModelID() string {
	if u == nil {
		return ""
	}
	return u.UpstreamModelID
}
