// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type UpdateWorkspaceRequest struct {
	// Default image model for this workspace
	DefaultImageModel optionalnullable.OptionalNullable[string] `json:"default_image_model,omitzero"`
	// Default provider sort preference (price, throughput, latency, exacto)
	DefaultProviderSort optionalnullable.OptionalNullable[string] `json:"default_provider_sort,omitzero"`
	// Default text model for this workspace
	DefaultTextModel optionalnullable.OptionalNullable[string] `json:"default_text_model,omitzero"`
	// New description for the workspace
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Whether data discount logging is enabled
	IsDataDiscountLoggingEnabled *bool `json:"is_data_discount_logging_enabled,omitzero"`
	// Whether broadcast is enabled
	IsObservabilityBroadcastEnabled *bool `json:"is_observability_broadcast_enabled,omitzero"`
	// Whether private logging is enabled
	IsObservabilityIoLoggingEnabled *bool `json:"is_observability_io_logging_enabled,omitzero"`
	// New name for the workspace
	Name *string `json:"name,omitzero"`
	// New URL-friendly slug
	Slug *string `json:"slug,omitzero"`
}

func (u *UpdateWorkspaceRequest) GetDefaultImageModel() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.DefaultImageModel
}

func (u *UpdateWorkspaceRequest) GetDefaultProviderSort() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.DefaultProviderSort
}

func (u *UpdateWorkspaceRequest) GetDefaultTextModel() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.DefaultTextModel
}

func (u *UpdateWorkspaceRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateWorkspaceRequest) GetIsDataDiscountLoggingEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsDataDiscountLoggingEnabled
}

func (u *UpdateWorkspaceRequest) GetIsObservabilityBroadcastEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsObservabilityBroadcastEnabled
}

func (u *UpdateWorkspaceRequest) GetIsObservabilityIoLoggingEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsObservabilityIoLoggingEnabled
}

func (u *UpdateWorkspaceRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateWorkspaceRequest) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}
