// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
	"github.com/OpenRouterTeam/go-sdk/optionalnullable"
)

type SupportedAspectRatio string

const (
	SupportedAspectRatioOneHundredAndSixtyNine  SupportedAspectRatio = "16:9"
	SupportedAspectRatioNineHundredAndSixteen   SupportedAspectRatio = "9:16"
	SupportedAspectRatioEleven                  SupportedAspectRatio = "1:1"
	SupportedAspectRatioFortyThree              SupportedAspectRatio = "4:3"
	SupportedAspectRatioThirtyFour              SupportedAspectRatio = "3:4"
	SupportedAspectRatioTwoHundredAndNineteen   SupportedAspectRatio = "21:9"
	SupportedAspectRatioNineHundredAndTwentyOne SupportedAspectRatio = "9:21"
)

func (e SupportedAspectRatio) ToPointer() *SupportedAspectRatio {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SupportedAspectRatio) IsExact() bool {
	if e != nil {
		switch *e {
		case "16:9", "9:16", "1:1", "4:3", "3:4", "21:9", "9:21":
			return true
		}
	}
	return false
}

type SupportedResolution string

const (
	SupportedResolutionFourHundredAndEightyp  SupportedResolution = "480p"
	SupportedResolutionSevenHundredAndTwentyp SupportedResolution = "720p"
	SupportedResolutionOneThousandAndEightyp  SupportedResolution = "1080p"
	SupportedResolutionOneK                   SupportedResolution = "1K"
	SupportedResolutionTwoK                   SupportedResolution = "2K"
	SupportedResolutionFourK                  SupportedResolution = "4K"
)

func (e SupportedResolution) ToPointer() *SupportedResolution {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SupportedResolution) IsExact() bool {
	if e != nil {
		switch *e {
		case "480p", "720p", "1080p", "1K", "2K", "4K":
			return true
		}
	}
	return false
}

type SupportedSize string

const (
	SupportedSizeFourHundredAndEightyx480               SupportedSize = "480x480"
	SupportedSizeFourHundredAndEightyx640               SupportedSize = "480x640"
	SupportedSizeFourHundredAndEightyx854               SupportedSize = "480x854"
	SupportedSizeFourHundredAndEightyx1120              SupportedSize = "480x1120"
	SupportedSizeSixHundredAndFortyx480                 SupportedSize = "640x480"
	SupportedSizeSevenHundredAndTwentyx720              SupportedSize = "720x720"
	SupportedSizeSevenHundredAndTwentyx960              SupportedSize = "720x960"
	SupportedSizeSevenHundredAndTwentyx1280             SupportedSize = "720x1280"
	SupportedSizeSevenHundredAndTwentyx1680             SupportedSize = "720x1680"
	SupportedSizeEightHundredAndFiftyFourx480           SupportedSize = "854x480"
	SupportedSizeNineHundredAndSixtyx720                SupportedSize = "960x720"
	SupportedSizeOneThousandAndEightyx1080              SupportedSize = "1080x1080"
	SupportedSizeOneThousandAndEightyx1440              SupportedSize = "1080x1440"
	SupportedSizeOneThousandAndEightyx1920              SupportedSize = "1080x1920"
	SupportedSizeOneThousandAndEightyx2520              SupportedSize = "1080x2520"
	SupportedSizeOneThousandOneHundredAndTwentyx480     SupportedSize = "1120x480"
	SupportedSizeOneThousandTwoHundredAndEightyx720     SupportedSize = "1280x720"
	SupportedSizeOneThousandFourHundredAndFortyx1080    SupportedSize = "1440x1080"
	SupportedSizeOneThousandSixHundredAndEightyx720     SupportedSize = "1680x720"
	SupportedSizeOneThousandNineHundredAndTwentyx1080   SupportedSize = "1920x1080"
	SupportedSizeTwoThousandOneHundredAndSixtyx2160     SupportedSize = "2160x2160"
	SupportedSizeTwoThousandOneHundredAndSixtyx2880     SupportedSize = "2160x2880"
	SupportedSizeTwoThousandOneHundredAndSixtyx3840     SupportedSize = "2160x3840"
	SupportedSizeTwoThousandOneHundredAndSixtyx5040     SupportedSize = "2160x5040"
	SupportedSizeTwoThousandFiveHundredAndTwentyx1080   SupportedSize = "2520x1080"
	SupportedSizeTwoThousandEightHundredAndEightyx2160  SupportedSize = "2880x2160"
	SupportedSizeThreeThousandEightHundredAndFortyx2160 SupportedSize = "3840x2160"
	SupportedSizeFiveThousandAndFortyx2160              SupportedSize = "5040x2160"
)

func (e SupportedSize) ToPointer() *SupportedSize {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SupportedSize) IsExact() bool {
	if e != nil {
		switch *e {
		case "480x480", "480x640", "480x854", "480x1120", "640x480", "720x720", "720x960", "720x1280", "720x1680", "854x480", "960x720", "1080x1080", "1080x1440", "1080x1920", "1080x2520", "1120x480", "1280x720", "1440x1080", "1680x720", "1920x1080", "2160x2160", "2160x2880", "2160x3840", "2160x5040", "2520x1080", "2880x2160", "3840x2160", "5040x2160":
			return true
		}
	}
	return false
}

type VideoModel struct {
	// List of parameters that are allowed to be passed through to the provider
	AllowedPassthroughParameters []string `json:"allowed_passthrough_parameters"`
	// Canonical slug for the model
	CanonicalSlug string `json:"canonical_slug"`
	// Unix timestamp of when the model was created
	Created int64 `json:"created"`
	// Description of the model
	Description *string `json:"description,omitzero"`
	// Hugging Face model identifier, if applicable
	HuggingFaceID optionalnullable.OptionalNullable[string] `json:"hugging_face_id,omitzero"`
	// Unique identifier for the model
	ID string `json:"id"`
	// Display name of the model
	Name string `json:"name"`
	// Pricing SKUs with provider prefix stripped, values as strings
	PricingSkus optionalnullable.OptionalNullable[map[string]string] `json:"pricing_skus,omitzero"`
	// Supported output aspect ratios
	SupportedAspectRatios []SupportedAspectRatio `json:"supported_aspect_ratios"`
	// Supported video durations in seconds
	SupportedDurations []int64 `json:"supported_durations"`
	// Supported output resolutions
	SupportedResolutions []SupportedResolution `json:"supported_resolutions"`
	// Supported output sizes (width x height)
	SupportedSizes []SupportedSize `json:"supported_sizes"`
}

func (v VideoModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VideoModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VideoModel) GetAllowedPassthroughParameters() []string {
	if v == nil {
		return []string{}
	}
	return v.AllowedPassthroughParameters
}

func (v *VideoModel) GetCanonicalSlug() string {
	if v == nil {
		return ""
	}
	return v.CanonicalSlug
}

func (v *VideoModel) GetCreated() int64 {
	if v == nil {
		return 0
	}
	return v.Created
}

func (v *VideoModel) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *VideoModel) GetHuggingFaceID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.HuggingFaceID
}

func (v *VideoModel) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VideoModel) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *VideoModel) GetPricingSkus() optionalnullable.OptionalNullable[map[string]string] {
	if v == nil {
		return nil
	}
	return v.PricingSkus
}

func (v *VideoModel) GetSupportedAspectRatios() []SupportedAspectRatio {
	if v == nil {
		return nil
	}
	return v.SupportedAspectRatios
}

func (v *VideoModel) GetSupportedDurations() []int64 {
	if v == nil {
		return nil
	}
	return v.SupportedDurations
}

func (v *VideoModel) GetSupportedResolutions() []SupportedResolution {
	if v == nil {
		return nil
	}
	return v.SupportedResolutions
}

func (v *VideoModel) GetSupportedSizes() []SupportedSize {
	if v == nil {
		return nil
	}
	return v.SupportedSizes
}
