// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

// AspectRatio - Aspect ratio of the generated video
type AspectRatio string

const (
	AspectRatioOneHundredAndSixtyNine  AspectRatio = "16:9"
	AspectRatioNineHundredAndSixteen   AspectRatio = "9:16"
	AspectRatioEleven                  AspectRatio = "1:1"
	AspectRatioFortyThree              AspectRatio = "4:3"
	AspectRatioThirtyFour              AspectRatio = "3:4"
	AspectRatioTwoHundredAndNineteen   AspectRatio = "21:9"
	AspectRatioNineHundredAndTwentyOne AspectRatio = "9:21"
)

func (e AspectRatio) ToPointer() *AspectRatio {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AspectRatio) IsExact() bool {
	if e != nil {
		switch *e {
		case "16:9", "9:16", "1:1", "4:3", "3:4", "21:9", "9:21":
			return true
		}
	}
	return false
}

// VideoGenerationRequestOptions - Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
type VideoGenerationRequestOptions struct {
	Oneai               map[string]any `json:"01ai,omitzero"`
	Ai21                map[string]any `json:"ai21,omitzero"`
	AionLabs            map[string]any `json:"aion-labs,omitzero"`
	Akashml             map[string]any `json:"akashml,omitzero"`
	Alibaba             map[string]any `json:"alibaba,omitzero"`
	AmazonBedrock       map[string]any `json:"amazon-bedrock,omitzero"`
	AmazonNova          map[string]any `json:"amazon-nova,omitzero"`
	Ambient             map[string]any `json:"ambient,omitzero"`
	Anthropic           map[string]any `json:"anthropic,omitzero"`
	Anyscale            map[string]any `json:"anyscale,omitzero"`
	ArceeAi             map[string]any `json:"arcee-ai,omitzero"`
	AtlasCloud          map[string]any `json:"atlas-cloud,omitzero"`
	Atoma               map[string]any `json:"atoma,omitzero"`
	Avian               map[string]any `json:"avian,omitzero"`
	Azure               map[string]any `json:"azure,omitzero"`
	Baidu               map[string]any `json:"baidu,omitzero"`
	Baseten             map[string]any `json:"baseten,omitzero"`
	BlackForestLabs     map[string]any `json:"black-forest-labs,omitzero"`
	Byteplus            map[string]any `json:"byteplus,omitzero"`
	Centml              map[string]any `json:"centml,omitzero"`
	Cerebras            map[string]any `json:"cerebras,omitzero"`
	Chutes              map[string]any `json:"chutes,omitzero"`
	Cirrascale          map[string]any `json:"cirrascale,omitzero"`
	Clarifai            map[string]any `json:"clarifai,omitzero"`
	Cloudflare          map[string]any `json:"cloudflare,omitzero"`
	Cohere              map[string]any `json:"cohere,omitzero"`
	Crofai              map[string]any `json:"crofai,omitzero"`
	Crusoe              map[string]any `json:"crusoe,omitzero"`
	Deepinfra           map[string]any `json:"deepinfra,omitzero"`
	Deepseek            map[string]any `json:"deepseek,omitzero"`
	Dekallm             map[string]any `json:"dekallm,omitzero"`
	Enfer               map[string]any `json:"enfer,omitzero"`
	FakeProvider        map[string]any `json:"fake-provider,omitzero"`
	Featherless         map[string]any `json:"featherless,omitzero"`
	Fireworks           map[string]any `json:"fireworks,omitzero"`
	Friendli            map[string]any `json:"friendli,omitzero"`
	Gmicloud            map[string]any `json:"gmicloud,omitzero"`
	GoogleAiStudio      map[string]any `json:"google-ai-studio,omitzero"`
	GoogleVertex        map[string]any `json:"google-vertex,omitzero"`
	Gopomelo            map[string]any `json:"gopomelo,omitzero"`
	Groq                map[string]any `json:"groq,omitzero"`
	Huggingface         map[string]any `json:"huggingface,omitzero"`
	Hyperbolic          map[string]any `json:"hyperbolic,omitzero"`
	HyperbolicQuantized map[string]any `json:"hyperbolic-quantized,omitzero"`
	Inception           map[string]any `json:"inception,omitzero"`
	Inceptron           map[string]any `json:"inceptron,omitzero"`
	InferenceNet        map[string]any `json:"inference-net,omitzero"`
	Infermatic          map[string]any `json:"infermatic,omitzero"`
	Inflection          map[string]any `json:"inflection,omitzero"`
	Inocloud            map[string]any `json:"inocloud,omitzero"`
	IoNet               map[string]any `json:"io-net,omitzero"`
	Ionstream           map[string]any `json:"ionstream,omitzero"`
	Klusterai           map[string]any `json:"klusterai,omitzero"`
	Lambda              map[string]any `json:"lambda,omitzero"`
	Lepton              map[string]any `json:"lepton,omitzero"`
	Liquid              map[string]any `json:"liquid,omitzero"`
	Lynn                map[string]any `json:"lynn,omitzero"`
	LynnPrivate         map[string]any `json:"lynn-private,omitzero"`
	Mancer              map[string]any `json:"mancer,omitzero"`
	MancerOld           map[string]any `json:"mancer-old,omitzero"`
	Mara                map[string]any `json:"mara,omitzero"`
	Meta                map[string]any `json:"meta,omitzero"`
	Minimax             map[string]any `json:"minimax,omitzero"`
	Mistral             map[string]any `json:"mistral,omitzero"`
	Modal               map[string]any `json:"modal,omitzero"`
	Modelrun            map[string]any `json:"modelrun,omitzero"`
	Modular             map[string]any `json:"modular,omitzero"`
	Moonshotai          map[string]any `json:"moonshotai,omitzero"`
	Morph               map[string]any `json:"morph,omitzero"`
	Ncompass            map[string]any `json:"ncompass,omitzero"`
	Nebius              map[string]any `json:"nebius,omitzero"`
	NexAgi              map[string]any `json:"nex-agi,omitzero"`
	Nextbit             map[string]any `json:"nextbit,omitzero"`
	Nineteen            map[string]any `json:"nineteen,omitzero"`
	Novita              map[string]any `json:"novita,omitzero"`
	Nvidia              map[string]any `json:"nvidia,omitzero"`
	Octoai              map[string]any `json:"octoai,omitzero"`
	OpenInference       map[string]any `json:"open-inference,omitzero"`
	Openai              map[string]any `json:"openai,omitzero"`
	Parasail            map[string]any `json:"parasail,omitzero"`
	Perplexity          map[string]any `json:"perplexity,omitzero"`
	Phala               map[string]any `json:"phala,omitzero"`
	Poolside            map[string]any `json:"poolside,omitzero"`
	Recraft             map[string]any `json:"recraft,omitzero"`
	Recursal            map[string]any `json:"recursal,omitzero"`
	Reflection          map[string]any `json:"reflection,omitzero"`
	Reka                map[string]any `json:"reka,omitzero"`
	Relace              map[string]any `json:"relace,omitzero"`
	Replicate           map[string]any `json:"replicate,omitzero"`
	Sambanova           map[string]any `json:"sambanova,omitzero"`
	SambanovaCloaked    map[string]any `json:"sambanova-cloaked,omitzero"`
	Seed                map[string]any `json:"seed,omitzero"`
	SfCompute           map[string]any `json:"sf-compute,omitzero"`
	Siliconflow         map[string]any `json:"siliconflow,omitzero"`
	Sourceful           map[string]any `json:"sourceful,omitzero"`
	Stealth             map[string]any `json:"stealth,omitzero"`
	Stepfun             map[string]any `json:"stepfun,omitzero"`
	Streamlake          map[string]any `json:"streamlake,omitzero"`
	Switchpoint         map[string]any `json:"switchpoint,omitzero"`
	Targon              map[string]any `json:"targon,omitzero"`
	Together            map[string]any `json:"together,omitzero"`
	TogetherLite        map[string]any `json:"together-lite,omitzero"`
	Ubicloud            map[string]any `json:"ubicloud,omitzero"`
	Upstage             map[string]any `json:"upstage,omitzero"`
	Venice              map[string]any `json:"venice,omitzero"`
	Wandb               map[string]any `json:"wandb,omitzero"`
	Xai                 map[string]any `json:"xai,omitzero"`
	Xiaomi              map[string]any `json:"xiaomi,omitzero"`
	ZAi                 map[string]any `json:"z-ai,omitzero"`
}

func (v VideoGenerationRequestOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VideoGenerationRequestOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VideoGenerationRequestOptions) GetOneai() map[string]any {
	if v == nil {
		return nil
	}
	return v.Oneai
}

func (v *VideoGenerationRequestOptions) GetAi21() map[string]any {
	if v == nil {
		return nil
	}
	return v.Ai21
}

func (v *VideoGenerationRequestOptions) GetAionLabs() map[string]any {
	if v == nil {
		return nil
	}
	return v.AionLabs
}

func (v *VideoGenerationRequestOptions) GetAkashml() map[string]any {
	if v == nil {
		return nil
	}
	return v.Akashml
}

func (v *VideoGenerationRequestOptions) GetAlibaba() map[string]any {
	if v == nil {
		return nil
	}
	return v.Alibaba
}

func (v *VideoGenerationRequestOptions) GetAmazonBedrock() map[string]any {
	if v == nil {
		return nil
	}
	return v.AmazonBedrock
}

func (v *VideoGenerationRequestOptions) GetAmazonNova() map[string]any {
	if v == nil {
		return nil
	}
	return v.AmazonNova
}

func (v *VideoGenerationRequestOptions) GetAmbient() map[string]any {
	if v == nil {
		return nil
	}
	return v.Ambient
}

func (v *VideoGenerationRequestOptions) GetAnthropic() map[string]any {
	if v == nil {
		return nil
	}
	return v.Anthropic
}

func (v *VideoGenerationRequestOptions) GetAnyscale() map[string]any {
	if v == nil {
		return nil
	}
	return v.Anyscale
}

func (v *VideoGenerationRequestOptions) GetArceeAi() map[string]any {
	if v == nil {
		return nil
	}
	return v.ArceeAi
}

func (v *VideoGenerationRequestOptions) GetAtlasCloud() map[string]any {
	if v == nil {
		return nil
	}
	return v.AtlasCloud
}

func (v *VideoGenerationRequestOptions) GetAtoma() map[string]any {
	if v == nil {
		return nil
	}
	return v.Atoma
}

func (v *VideoGenerationRequestOptions) GetAvian() map[string]any {
	if v == nil {
		return nil
	}
	return v.Avian
}

func (v *VideoGenerationRequestOptions) GetAzure() map[string]any {
	if v == nil {
		return nil
	}
	return v.Azure
}

func (v *VideoGenerationRequestOptions) GetBaidu() map[string]any {
	if v == nil {
		return nil
	}
	return v.Baidu
}

func (v *VideoGenerationRequestOptions) GetBaseten() map[string]any {
	if v == nil {
		return nil
	}
	return v.Baseten
}

func (v *VideoGenerationRequestOptions) GetBlackForestLabs() map[string]any {
	if v == nil {
		return nil
	}
	return v.BlackForestLabs
}

func (v *VideoGenerationRequestOptions) GetByteplus() map[string]any {
	if v == nil {
		return nil
	}
	return v.Byteplus
}

func (v *VideoGenerationRequestOptions) GetCentml() map[string]any {
	if v == nil {
		return nil
	}
	return v.Centml
}

func (v *VideoGenerationRequestOptions) GetCerebras() map[string]any {
	if v == nil {
		return nil
	}
	return v.Cerebras
}

func (v *VideoGenerationRequestOptions) GetChutes() map[string]any {
	if v == nil {
		return nil
	}
	return v.Chutes
}

func (v *VideoGenerationRequestOptions) GetCirrascale() map[string]any {
	if v == nil {
		return nil
	}
	return v.Cirrascale
}

func (v *VideoGenerationRequestOptions) GetClarifai() map[string]any {
	if v == nil {
		return nil
	}
	return v.Clarifai
}

func (v *VideoGenerationRequestOptions) GetCloudflare() map[string]any {
	if v == nil {
		return nil
	}
	return v.Cloudflare
}

func (v *VideoGenerationRequestOptions) GetCohere() map[string]any {
	if v == nil {
		return nil
	}
	return v.Cohere
}

func (v *VideoGenerationRequestOptions) GetCrofai() map[string]any {
	if v == nil {
		return nil
	}
	return v.Crofai
}

func (v *VideoGenerationRequestOptions) GetCrusoe() map[string]any {
	if v == nil {
		return nil
	}
	return v.Crusoe
}

func (v *VideoGenerationRequestOptions) GetDeepinfra() map[string]any {
	if v == nil {
		return nil
	}
	return v.Deepinfra
}

func (v *VideoGenerationRequestOptions) GetDeepseek() map[string]any {
	if v == nil {
		return nil
	}
	return v.Deepseek
}

func (v *VideoGenerationRequestOptions) GetDekallm() map[string]any {
	if v == nil {
		return nil
	}
	return v.Dekallm
}

func (v *VideoGenerationRequestOptions) GetEnfer() map[string]any {
	if v == nil {
		return nil
	}
	return v.Enfer
}

func (v *VideoGenerationRequestOptions) GetFakeProvider() map[string]any {
	if v == nil {
		return nil
	}
	return v.FakeProvider
}

func (v *VideoGenerationRequestOptions) GetFeatherless() map[string]any {
	if v == nil {
		return nil
	}
	return v.Featherless
}

func (v *VideoGenerationRequestOptions) GetFireworks() map[string]any {
	if v == nil {
		return nil
	}
	return v.Fireworks
}

func (v *VideoGenerationRequestOptions) GetFriendli() map[string]any {
	if v == nil {
		return nil
	}
	return v.Friendli
}

func (v *VideoGenerationRequestOptions) GetGmicloud() map[string]any {
	if v == nil {
		return nil
	}
	return v.Gmicloud
}

func (v *VideoGenerationRequestOptions) GetGoogleAiStudio() map[string]any {
	if v == nil {
		return nil
	}
	return v.GoogleAiStudio
}

func (v *VideoGenerationRequestOptions) GetGoogleVertex() map[string]any {
	if v == nil {
		return nil
	}
	return v.GoogleVertex
}

func (v *VideoGenerationRequestOptions) GetGopomelo() map[string]any {
	if v == nil {
		return nil
	}
	return v.Gopomelo
}

func (v *VideoGenerationRequestOptions) GetGroq() map[string]any {
	if v == nil {
		return nil
	}
	return v.Groq
}

func (v *VideoGenerationRequestOptions) GetHuggingface() map[string]any {
	if v == nil {
		return nil
	}
	return v.Huggingface
}

func (v *VideoGenerationRequestOptions) GetHyperbolic() map[string]any {
	if v == nil {
		return nil
	}
	return v.Hyperbolic
}

func (v *VideoGenerationRequestOptions) GetHyperbolicQuantized() map[string]any {
	if v == nil {
		return nil
	}
	return v.HyperbolicQuantized
}

func (v *VideoGenerationRequestOptions) GetInception() map[string]any {
	if v == nil {
		return nil
	}
	return v.Inception
}

func (v *VideoGenerationRequestOptions) GetInceptron() map[string]any {
	if v == nil {
		return nil
	}
	return v.Inceptron
}

func (v *VideoGenerationRequestOptions) GetInferenceNet() map[string]any {
	if v == nil {
		return nil
	}
	return v.InferenceNet
}

func (v *VideoGenerationRequestOptions) GetInfermatic() map[string]any {
	if v == nil {
		return nil
	}
	return v.Infermatic
}

func (v *VideoGenerationRequestOptions) GetInflection() map[string]any {
	if v == nil {
		return nil
	}
	return v.Inflection
}

func (v *VideoGenerationRequestOptions) GetInocloud() map[string]any {
	if v == nil {
		return nil
	}
	return v.Inocloud
}

func (v *VideoGenerationRequestOptions) GetIoNet() map[string]any {
	if v == nil {
		return nil
	}
	return v.IoNet
}

func (v *VideoGenerationRequestOptions) GetIonstream() map[string]any {
	if v == nil {
		return nil
	}
	return v.Ionstream
}

func (v *VideoGenerationRequestOptions) GetKlusterai() map[string]any {
	if v == nil {
		return nil
	}
	return v.Klusterai
}

func (v *VideoGenerationRequestOptions) GetLambda() map[string]any {
	if v == nil {
		return nil
	}
	return v.Lambda
}

func (v *VideoGenerationRequestOptions) GetLepton() map[string]any {
	if v == nil {
		return nil
	}
	return v.Lepton
}

func (v *VideoGenerationRequestOptions) GetLiquid() map[string]any {
	if v == nil {
		return nil
	}
	return v.Liquid
}

func (v *VideoGenerationRequestOptions) GetLynn() map[string]any {
	if v == nil {
		return nil
	}
	return v.Lynn
}

func (v *VideoGenerationRequestOptions) GetLynnPrivate() map[string]any {
	if v == nil {
		return nil
	}
	return v.LynnPrivate
}

func (v *VideoGenerationRequestOptions) GetMancer() map[string]any {
	if v == nil {
		return nil
	}
	return v.Mancer
}

func (v *VideoGenerationRequestOptions) GetMancerOld() map[string]any {
	if v == nil {
		return nil
	}
	return v.MancerOld
}

func (v *VideoGenerationRequestOptions) GetMara() map[string]any {
	if v == nil {
		return nil
	}
	return v.Mara
}

func (v *VideoGenerationRequestOptions) GetMeta() map[string]any {
	if v == nil {
		return nil
	}
	return v.Meta
}

func (v *VideoGenerationRequestOptions) GetMinimax() map[string]any {
	if v == nil {
		return nil
	}
	return v.Minimax
}

func (v *VideoGenerationRequestOptions) GetMistral() map[string]any {
	if v == nil {
		return nil
	}
	return v.Mistral
}

func (v *VideoGenerationRequestOptions) GetModal() map[string]any {
	if v == nil {
		return nil
	}
	return v.Modal
}

func (v *VideoGenerationRequestOptions) GetModelrun() map[string]any {
	if v == nil {
		return nil
	}
	return v.Modelrun
}

func (v *VideoGenerationRequestOptions) GetModular() map[string]any {
	if v == nil {
		return nil
	}
	return v.Modular
}

func (v *VideoGenerationRequestOptions) GetMoonshotai() map[string]any {
	if v == nil {
		return nil
	}
	return v.Moonshotai
}

func (v *VideoGenerationRequestOptions) GetMorph() map[string]any {
	if v == nil {
		return nil
	}
	return v.Morph
}

func (v *VideoGenerationRequestOptions) GetNcompass() map[string]any {
	if v == nil {
		return nil
	}
	return v.Ncompass
}

func (v *VideoGenerationRequestOptions) GetNebius() map[string]any {
	if v == nil {
		return nil
	}
	return v.Nebius
}

func (v *VideoGenerationRequestOptions) GetNexAgi() map[string]any {
	if v == nil {
		return nil
	}
	return v.NexAgi
}

func (v *VideoGenerationRequestOptions) GetNextbit() map[string]any {
	if v == nil {
		return nil
	}
	return v.Nextbit
}

func (v *VideoGenerationRequestOptions) GetNineteen() map[string]any {
	if v == nil {
		return nil
	}
	return v.Nineteen
}

func (v *VideoGenerationRequestOptions) GetNovita() map[string]any {
	if v == nil {
		return nil
	}
	return v.Novita
}

func (v *VideoGenerationRequestOptions) GetNvidia() map[string]any {
	if v == nil {
		return nil
	}
	return v.Nvidia
}

func (v *VideoGenerationRequestOptions) GetOctoai() map[string]any {
	if v == nil {
		return nil
	}
	return v.Octoai
}

func (v *VideoGenerationRequestOptions) GetOpenInference() map[string]any {
	if v == nil {
		return nil
	}
	return v.OpenInference
}

func (v *VideoGenerationRequestOptions) GetOpenai() map[string]any {
	if v == nil {
		return nil
	}
	return v.Openai
}

func (v *VideoGenerationRequestOptions) GetParasail() map[string]any {
	if v == nil {
		return nil
	}
	return v.Parasail
}

func (v *VideoGenerationRequestOptions) GetPerplexity() map[string]any {
	if v == nil {
		return nil
	}
	return v.Perplexity
}

func (v *VideoGenerationRequestOptions) GetPhala() map[string]any {
	if v == nil {
		return nil
	}
	return v.Phala
}

func (v *VideoGenerationRequestOptions) GetPoolside() map[string]any {
	if v == nil {
		return nil
	}
	return v.Poolside
}

func (v *VideoGenerationRequestOptions) GetRecraft() map[string]any {
	if v == nil {
		return nil
	}
	return v.Recraft
}

func (v *VideoGenerationRequestOptions) GetRecursal() map[string]any {
	if v == nil {
		return nil
	}
	return v.Recursal
}

func (v *VideoGenerationRequestOptions) GetReflection() map[string]any {
	if v == nil {
		return nil
	}
	return v.Reflection
}

func (v *VideoGenerationRequestOptions) GetReka() map[string]any {
	if v == nil {
		return nil
	}
	return v.Reka
}

func (v *VideoGenerationRequestOptions) GetRelace() map[string]any {
	if v == nil {
		return nil
	}
	return v.Relace
}

func (v *VideoGenerationRequestOptions) GetReplicate() map[string]any {
	if v == nil {
		return nil
	}
	return v.Replicate
}

func (v *VideoGenerationRequestOptions) GetSambanova() map[string]any {
	if v == nil {
		return nil
	}
	return v.Sambanova
}

func (v *VideoGenerationRequestOptions) GetSambanovaCloaked() map[string]any {
	if v == nil {
		return nil
	}
	return v.SambanovaCloaked
}

func (v *VideoGenerationRequestOptions) GetSeed() map[string]any {
	if v == nil {
		return nil
	}
	return v.Seed
}

func (v *VideoGenerationRequestOptions) GetSfCompute() map[string]any {
	if v == nil {
		return nil
	}
	return v.SfCompute
}

func (v *VideoGenerationRequestOptions) GetSiliconflow() map[string]any {
	if v == nil {
		return nil
	}
	return v.Siliconflow
}

func (v *VideoGenerationRequestOptions) GetSourceful() map[string]any {
	if v == nil {
		return nil
	}
	return v.Sourceful
}

func (v *VideoGenerationRequestOptions) GetStealth() map[string]any {
	if v == nil {
		return nil
	}
	return v.Stealth
}

func (v *VideoGenerationRequestOptions) GetStepfun() map[string]any {
	if v == nil {
		return nil
	}
	return v.Stepfun
}

func (v *VideoGenerationRequestOptions) GetStreamlake() map[string]any {
	if v == nil {
		return nil
	}
	return v.Streamlake
}

func (v *VideoGenerationRequestOptions) GetSwitchpoint() map[string]any {
	if v == nil {
		return nil
	}
	return v.Switchpoint
}

func (v *VideoGenerationRequestOptions) GetTargon() map[string]any {
	if v == nil {
		return nil
	}
	return v.Targon
}

func (v *VideoGenerationRequestOptions) GetTogether() map[string]any {
	if v == nil {
		return nil
	}
	return v.Together
}

func (v *VideoGenerationRequestOptions) GetTogetherLite() map[string]any {
	if v == nil {
		return nil
	}
	return v.TogetherLite
}

func (v *VideoGenerationRequestOptions) GetUbicloud() map[string]any {
	if v == nil {
		return nil
	}
	return v.Ubicloud
}

func (v *VideoGenerationRequestOptions) GetUpstage() map[string]any {
	if v == nil {
		return nil
	}
	return v.Upstage
}

func (v *VideoGenerationRequestOptions) GetVenice() map[string]any {
	if v == nil {
		return nil
	}
	return v.Venice
}

func (v *VideoGenerationRequestOptions) GetWandb() map[string]any {
	if v == nil {
		return nil
	}
	return v.Wandb
}

func (v *VideoGenerationRequestOptions) GetXai() map[string]any {
	if v == nil {
		return nil
	}
	return v.Xai
}

func (v *VideoGenerationRequestOptions) GetXiaomi() map[string]any {
	if v == nil {
		return nil
	}
	return v.Xiaomi
}

func (v *VideoGenerationRequestOptions) GetZAi() map[string]any {
	if v == nil {
		return nil
	}
	return v.ZAi
}

// VideoGenerationRequestProvider - Provider-specific passthrough configuration
type VideoGenerationRequestProvider struct {
	// Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
	Options *VideoGenerationRequestOptions `json:"options,omitzero"`
}

func (v VideoGenerationRequestProvider) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VideoGenerationRequestProvider) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VideoGenerationRequestProvider) GetOptions() *VideoGenerationRequestOptions {
	if v == nil {
		return nil
	}
	return v.Options
}

// Resolution of the generated video
type Resolution string

const (
	ResolutionFourHundredAndEightyp  Resolution = "480p"
	ResolutionSevenHundredAndTwentyp Resolution = "720p"
	ResolutionOneThousandAndEightyp  Resolution = "1080p"
	ResolutionOneK                   Resolution = "1K"
	ResolutionTwoK                   Resolution = "2K"
	ResolutionFourK                  Resolution = "4K"
)

func (e Resolution) ToPointer() *Resolution {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Resolution) IsExact() bool {
	if e != nil {
		switch *e {
		case "480p", "720p", "1080p", "1K", "2K", "4K":
			return true
		}
	}
	return false
}

type VideoGenerationRequest struct {
	// Aspect ratio of the generated video
	AspectRatio *AspectRatio `json:"aspect_ratio,omitzero"`
	// URL to receive a webhook notification when the video generation job completes. Overrides the workspace-level default callback URL if set. Must be HTTPS.
	CallbackURL *string `json:"callback_url,omitzero"`
	// Duration of the generated video in seconds
	Duration *int64 `json:"duration,omitzero"`
	// Images to use as the first and/or last frame of the generated video. Each image must specify a frame_type of first_frame or last_frame.
	FrameImages []FrameImage `json:"frame_images,omitzero"`
	// Whether to generate audio alongside the video. Defaults to the endpoint's generate_audio capability flag, false if not set.
	GenerateAudio *bool `json:"generate_audio,omitzero"`
	// Reference images to guide video generation
	InputReferences []ContentPartImage `json:"input_references,omitzero"`
	Model           string             `json:"model"`
	Prompt          string             `json:"prompt"`
	// Provider-specific passthrough configuration
	Provider *VideoGenerationRequestProvider `json:"provider,omitzero"`
	// Resolution of the generated video
	Resolution *Resolution `json:"resolution,omitzero"`
	// If specified, the generation will sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed for all providers.
	Seed *int64 `json:"seed,omitzero"`
	// Exact pixel dimensions of the generated video in "WIDTHxHEIGHT" format (e.g. "1280x720"). Interchangeable with resolution + aspect_ratio.
	Size *string `json:"size,omitzero"`
}

func (v VideoGenerationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VideoGenerationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VideoGenerationRequest) GetAspectRatio() *AspectRatio {
	if v == nil {
		return nil
	}
	return v.AspectRatio
}

func (v *VideoGenerationRequest) GetCallbackURL() *string {
	if v == nil {
		return nil
	}
	return v.CallbackURL
}

func (v *VideoGenerationRequest) GetDuration() *int64 {
	if v == nil {
		return nil
	}
	return v.Duration
}

func (v *VideoGenerationRequest) GetFrameImages() []FrameImage {
	if v == nil {
		return nil
	}
	return v.FrameImages
}

func (v *VideoGenerationRequest) GetGenerateAudio() *bool {
	if v == nil {
		return nil
	}
	return v.GenerateAudio
}

func (v *VideoGenerationRequest) GetInputReferences() []ContentPartImage {
	if v == nil {
		return nil
	}
	return v.InputReferences
}

func (v *VideoGenerationRequest) GetModel() string {
	if v == nil {
		return ""
	}
	return v.Model
}

func (v *VideoGenerationRequest) GetPrompt() string {
	if v == nil {
		return ""
	}
	return v.Prompt
}

func (v *VideoGenerationRequest) GetProvider() *VideoGenerationRequestProvider {
	if v == nil {
		return nil
	}
	return v.Provider
}

func (v *VideoGenerationRequest) GetResolution() *Resolution {
	if v == nil {
		return nil
	}
	return v.Resolution
}

func (v *VideoGenerationRequest) GetSeed() *int64 {
	if v == nil {
		return nil
	}
	return v.Seed
}

func (v *VideoGenerationRequest) GetSize() *string {
	if v == nil {
		return nil
	}
	return v.Size
}
