// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/go-sdk/internal/utils"
)

type Parameters struct {
	// Maximum number of search results to return per search call. Defaults to 5.
	MaxResults *int64 `json:"max_results,omitzero"`
	// Maximum total number of search results across all search calls in a single request. Once this limit is reached, the tool will stop returning new results.
	MaxTotalResults *int64 `json:"max_total_results,omitzero"`
}

func (p Parameters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Parameters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Parameters) GetMaxResults() *int64 {
	if p == nil {
		return nil
	}
	return p.MaxResults
}

func (p *Parameters) GetMaxTotalResults() *int64 {
	if p == nil {
		return nil
	}
	return p.MaxTotalResults
}

type WebSearchServerToolOpenRouterType string

const (
	WebSearchServerToolOpenRouterTypeOpenrouterWebSearch WebSearchServerToolOpenRouterType = "openrouter:web_search"
)

func (e WebSearchServerToolOpenRouterType) ToPointer() *WebSearchServerToolOpenRouterType {
	return &e
}
func (e *WebSearchServerToolOpenRouterType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:web_search":
		*e = WebSearchServerToolOpenRouterType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebSearchServerToolOpenRouterType: %v", v)
	}
}

// WebSearchServerToolOpenRouter - OpenRouter built-in server tool: searches the web for current information
type WebSearchServerToolOpenRouter struct {
	Parameters *Parameters                       `json:"parameters,omitzero"`
	Type       WebSearchServerToolOpenRouterType `json:"type"`
}

func (w WebSearchServerToolOpenRouter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebSearchServerToolOpenRouter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebSearchServerToolOpenRouter) GetParameters() *Parameters {
	if w == nil {
		return nil
	}
	return w.Parameters
}

func (w *WebSearchServerToolOpenRouter) GetType() WebSearchServerToolOpenRouterType {
	if w == nil {
		return WebSearchServerToolOpenRouterType("")
	}
	return w.Type
}
